/**
 * Lane V (W5-V7): wave 5's BAYBAY lines for the voice — the inventory of the lanes' fixed lines and the TTS take list.
 *
 *   npx tsx --tsconfig tsconfig.app.json scripts/opus-sf/voice/w5/lines.ts                      the inventory: every line,
 *        its lane and clip id, "rec" when data/sf/voiceW5.ts has it, "NEW" when not, and the recorded lines no source says
 *   npx tsx --tsconfig tsconfig.app.json scripts/opus-sf/voice/w5/lines.ts --takes <work>/takes.json [--batch <n>]
 *        the take list of the NEW lines (zh + en, one take each at speech_rate 1.0; post.py asks for retakes)
 *
 * What counts as a line (BAYBAY's, spoken, fixed): a `{ zh: '…', en: '…' }` literal in a wave-5 source below that reads
 * as a sentence (Chinese text ending in ！？。～… or holding a comma, no `${…}` template, no "Name：" speaker prefix, zh ≤ 45),
 * minus the EXCLUDE list (paper notes, card texts, labels that happen to be sentences), plus the egg registry's own
 * fields (every egg's `lines` and `rumour`, the cookie fortunes), plus lane C's frozen table (data/sf/linesW5.ts
 * W5_C_LINES, read first: those lines keep lane C's ids and lane C plays them itself through its pacer — `own`). A line
 * built from a name, a time or a key stays a text bubble (it is never a literal).
 *
 * The clip id is `w5-<lane>-<8 hex of sha1(zh + "\n" + en)>`, so a line keeps its clip wherever a lane moves it, and a
 * changed word in either language is a new line (its old clip simply stops matching). A line a lane voices itself with a
 * `voice-line` event keeps the lane's id (VOICE_IDS). The runtime side: data/sf/voiceW5.ts (generated by post.py) and
 * game/voiceW5.ts (BAYBAY's bubble → its clip).
 */
import { createHash } from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Z]:)/, '$1')), '../../../..');

export interface W5Line { id: string; lane: string; zh: string; en: string; source: string; mood: string; voiceId?: string; /** lane C's paced lines (data/sf/voiceTour.ts TOUR_VOICE_CLIPS carries them) */ paced?: 1 }

/**
 * Sources per lane (relative to src/opus-bay): a folder = every .ts / .tsx in it (the four feature folders are wave 5's
 * own); `only` = just these exported constants of a shared file. The egg registry is read by its fields (eggLines).
 */
const SOURCES: { lane: string; files: string[]; only?: string[] }[] = [
  { lane: 'a', files: ['play/'] },
  { lane: 'c', files: ['game/pelicanFirst.ts', 'game/goalsStep.ts', 'game/rumours.ts', 'game/welcome.ts'] },
  { lane: 'c', files: ['game/flow.ts'], only: ['PELICAN_NUDGE', 'FREE_AGAIN'] },
  { lane: 'n', files: ['game/goTo.ts', 'game/goToRun.ts'] },
  { lane: 'e', files: ['economy/'] },
  { lane: 'd', files: ['eggs/'] },
  { lane: 'r', files: ['realsf/seasons.ts'], only: ['FIRE_SEASON_LAST_DAY'] },
  { lane: 'r', files: ['realsf/daily.ts'], only: ['DAILY_ALL_LINE'] },
  // JETS_DAY_LINE / JETS_NOW_LINE share the key `jets-day` (one voice-line id for two texts): not recorded until lane R
  // gives the second its own key (Requests)
  { lane: 'r', files: ['realsf/jets.ts'], only: ['JETS_NEAR_LINE', 'JETS_PHOTO_LINE'] },
];
/** read by its fields, not scanned (its facts, names and riddles are sentences no one says) */
const STRUCTURED = new Set(['eggs/registry.ts']);

/** Lines a lane voices itself (`emit({ type: 'voice-line', id })`): the clip takes the lane's id. */
const VOICE_IDS: Record<string, string> = {
  FIRE_SEASON_LAST_DAY: 'realsf-fire-season-end',
  DAILY_ALL_LINE: 'realsf-daily-all',
  JETS_NEAR_LINE: 'realsf-jets-up',
  JETS_PHOTO_LINE: 'realsf-jets-photo',
};

/** Sentences that are not spoken by BAYBAY (paper, cards, UI, other speakers): zh text → why. */
export const EXCLUDE: Record<string, string> = {
  '桥要结实，工期要快，大船还要能从桥下通过。': 'Norton’s scroll (a paper note, lane D)',
  '（BAYBAY 小声说：64 年后，它真的修好啦。）': 'the scroll’s footnote (paper)',
  '我们在这山坡上盖了一座八个角的房子，希望你也喜欢它。': 'the 1861-style time-capsule letter (paper)',
  '愿你一路平安，风景常新。': 'the time-capsule letter (paper)',
  '几点开？': 'the slides prompt’s verb outside the hours (lane A, a button label)',
  '你领先！': 'the stair race chip’s status (lane A)',
  '按住 空格 躺下，滑得更快': 'the slides chip’s hint (lane A)',
};

const LIT = /(?:export\s+const\s+([A-Z0-9_]+)\s*(?::\s*[A-Za-z<>[\]]+)?\s*=\s*)?\{\s*zh:\s*'((?:[^'\\]|\\.)*)'\s*,\s*en:\s*(?:'((?:[^'\\]|\\.)*)'|"((?:[^"\\]|\\.)*)")\s*\}/g;
const unesc = (s: string) => s.replace(/\\(.)/g, '$1');

/** A spoken sentence of BAYBAY's (see the header). */
export function isSentence(zh: string, en: string): boolean {
  if (!/[一-鿿]/.test(zh) || zh.includes('${') || en.includes('${')) return false;
  if ([...zh].length > 45 || [...zh].length < 4) return false;
  if (/^[^\s，。！？]{1,8}[：:]/.test(zh)) return false;
  return /[！？。～…!?~]$/.test(zh) || /[，、]/.test(zh);
}

export const lineId = (lane: string, zh: string, en: string) => `w5-${lane}-${createHash('sha1').update(`${zh}\n${en}`).digest('hex').slice(0, 8)}`;

/** A mood note for the instruction, from the line's own punctuation. */
export function moodOf(zh: string): string {
  if (zh.startsWith('听说')) return 'secret';
  if (zh.startsWith('今日签')) return 'fortune';
  if (/[？?]$/.test(zh)) return 'ask';
  if (/[！!]$/.test(zh)) return 'excited';
  if (/[。…]$/.test(zh)) return 'calm';
  return 'happy';
}

function scan(): W5Line[] {
  const out: W5Line[] = [];
  const seen = new Set<string>();
  const add = (lane: string, zh: string, en: string, source: string, voiceId?: string) => {
    if (!isSentence(zh, en) || EXCLUDE[zh]) return;
    const id = voiceId ?? lineId(lane, zh, en);
    if (seen.has(`${zh}\n${en}`)) return;
    seen.add(`${zh}\n${en}`);
    out.push({ id, lane, zh, en, source, mood: moodOf(zh), ...(voiceId ? { voiceId } : {}) });
  };
  for (const s of SOURCES) {
    const files = s.files.flatMap(f => (f.endsWith('/') && fs.existsSync(path.join(ROOT, 'src/opus-bay', f))
      ? fs.readdirSync(path.join(ROOT, 'src/opus-bay', f)).filter(n => /\.tsx?$/.test(n)).sort().map(n => f + n)
      : [f])).filter(f => !STRUCTURED.has(f));
    for (const f of files) {
      const file = path.join(ROOT, 'src/opus-bay', f);
      if (!fs.existsSync(file)) continue;
      const text = fs.readFileSync(file, 'utf8');
      for (const m of text.matchAll(LIT)) {
        const name = m[1];
        if (s.only && (!name || !s.only.includes(name))) continue;
        add(s.lane, unesc(m[2]), unesc(m[3] ?? m[4]), `${f}${name ? ` ${name}` : ''}`, name ? VOICE_IDS[name] : undefined);
      }
    }
  }
  return out;
}

/** The egg registry's spoken fields (lane D): every egg's lines, then its rumour; the cookie fortunes. */
async function eggLines(): Promise<W5Line[]> {
  const file = path.join(ROOT, 'src/opus-bay/eggs/registry.ts');
  if (!fs.existsSync(file)) return [];
  const R = await import(new URL(`file:///${file.replace(/\\/g, '/')}`).href) as { EGGS: { id: string; lines: { zh: string; en: string }[]; rumour: { zh: string; en: string } }[]; FORTUNES?: { zh: string; en: string }[] };
  const out: W5Line[] = [];
  const push = (zh: string, en: string, source: string) => { if (isSentence(zh, en) && !EXCLUDE[zh]) out.push({ id: lineId('d', zh, en), lane: 'd', zh, en, source, mood: moodOf(zh) }); };
  for (const e of R.EGGS) {
    e.lines.forEach((l, i) => push(l.zh, l.en, `eggs/registry.ts ${e.id}.lines[${i}]`));
    push(e.rumour.zh, e.rumour.en, `eggs/registry.ts ${e.id}.rumour`);
  }
  (R.FORTUNES ?? []).forEach((l, i) => push(l.zh, l.en, `eggs/registry.ts FORTUNES[${i}]`));
  return out;
}

/** Lane C's frozen wave-5 lines (W5-C6): their own ids, voiced by lane C's pacer (cityMoments speakRecorded / offerLineOr). */
async function laneCLines(): Promise<W5Line[]> {
  const file = path.join(ROOT, 'src/opus-bay/data/sf/linesW5.ts');
  if (!fs.existsSync(file)) return [];
  const C = await import(new URL(`file:///${file.replace(/\\/g, '/')}`).href) as { W5_C_LINES: readonly { id: string; zh: string; en: string }[] };
  return C.W5_C_LINES.map(l => ({ id: l.id, lane: 'c', zh: l.zh, en: l.en, source: `data/sf/linesW5.ts ${l.id}`, mood: moodOf(l.zh), voiceId: l.id, paced: 1 as const }));
}

export async function w5Lines(): Promise<W5Line[]> {
  const all = [...await laneCLines(), ...scan(), ...await eggLines()];
  const byText = new Map<string, W5Line>();
  for (const l of all) if (!byText.has(`${l.zh}\n${l.en}`)) byText.set(`${l.zh}\n${l.en}`, l);
  return [...byText.values()];
}

// --- the take list ----------------------------------------------------------------------------------------------------

export const PIXIE = '0178ef57-ada4-43d9-992b-8d9221045bb4';
export const MAX_INSTRUCTION = 128;
/** BAYBAY in a speech bubble: a sentence, said to the player walking beside her (not a bark, not a tour guide) */
export const BUBBLE_INSTRUCTION = 'Cute otter mascot talking to a friend: warm, cheerful, natural, clear, easy chatty pace.';
const MOOD_NOTE: Record<string, string> = {
  excited: 'Bright and happy.',
  happy: 'Happy and warm, relaxed.',
  ask: 'Curious and inviting.',
  calm: 'Calm and warm.',
  secret: 'Sharing a little rumour, curious.',
  fortune: 'Reading a fortune slip, playful.',
};

export interface Take { index: number; clip: string; line: string; lane: string; text: string; language: 'zh' | 'en'; instruction: string; speechRate: number }

export function takesFor(lines: readonly W5Line[], rate = 1.0, start = 0): Take[] {
  const takes: Take[] = [];
  for (const l of lines) {
    for (const language of ['zh', 'en'] as const) {
      const instruction = `${BUBBLE_INSTRUCTION} ${MOOD_NOTE[l.mood] ?? MOOD_NOTE.happy}`;
      if (instruction.length > MAX_INSTRUCTION) throw new Error(`instruction too long for ${l.id}`);
      takes.push({ index: start + takes.length, clip: `${language}-${l.id}`, line: l.id, lane: l.lane, text: l[language], language, instruction, speechRate: rate });
    }
  }
  return takes;
}

/** The recorded clip ids (data/sf/voiceW5.ts, generated), read as text so this script runs before the table exists. */
function recorded(): Set<string> {
  const file = path.join(ROOT, 'src/opus-bay/data/sf/voiceW5.ts');
  if (!fs.existsSync(file)) return new Set();
  return new Set([...fs.readFileSync(file, 'utf8').matchAll(/\bid: "([a-z0-9-]+)"/g)].map(m => m[1]));
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === path.resolve(new URL(import.meta.url).pathname.replace(/^\/([A-Z]:)/, '$1'));
if (isMain) {
  const lines = await w5Lines();
  const rec = recorded();
  const arg = (k: string) => { const i = process.argv.indexOf(k); return i > 0 ? process.argv[i + 1] : undefined; };
  const out = arg('--takes');
  if (out) {
    const fresh = lines.filter(l => !rec.has(l.id));
    const takes = takesFor(fresh);
    // live: every line said today — post.py retires the recorded lines no source says any more
    fs.writeFileSync(out, JSON.stringify({ voice: PIXIE, batch: Number(arg('--batch') ?? 1), live: lines.map(l => l.id), lines: fresh, takes }, null, 1) + '\n');
    console.log(`${fresh.length} new lines, ${takes.length} takes → ${out}`);
  } else {
    for (const l of lines) console.log(`${rec.has(l.id) ? 'rec' : 'NEW'}  ${l.id.padEnd(22)} ${l.zh}  |  ${l.en}  (${l.source})`);
    const live = new Set(lines.map(l => l.id));
    const gone = [...rec].filter(id => !live.has(id));
    console.log(`${lines.length} lines (${lines.filter(l => !rec.has(l.id)).length} new); recorded but no longer said: ${gone.length ? gone.join(' ') : 'none'}`);
  }
}
