import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import { checkLegacyUrls, LEGACY_URLS, resolveHosting } from '../scripts/hosting-routes.mjs';
import { PERMISSIONS_POLICY, tableHostingRoutes, type HostingRoute } from '../scripts/sync-public-routes';
import { ROUTES } from '../src/app/route-table';

// Plan D3 + RC-11 (iii) + RC-24, against the committed vercel.json (generated by scripts/sync-public-routes.ts):
// printed QR codes, the 3D game's links and old shares keep working, and every redirect keeps its query.
const { routes } = JSON.parse(readFileSync(new URL('../vercel.json', import.meta.url), 'utf8')) as { routes: HostingRoute[] };
type Outcome = { kind: string; status?: number; location?: string; file?: string; headers: Record<string, string> };
const hosted = (url: string) => resolveHosting(routes, url) as Outcome;

test('every legacy and shared URL resolves as the route table says, in all three languages', () => {
  assert.ok(LEGACY_URLS.length >= 40);
  assert.deepEqual(checkLegacyUrls(routes), []);
});

test('/events is a prerendered page; /this-week and /recommend are 301s to it; /n/{region} is a 302 that keeps from=card-*', () => {
  for (const prefix of ['', '/en', '/zh-Hant']) {
    assert.deepEqual(hosted(`${prefix}/events`).file, `${prefix}/events.html`);
    assert.deepEqual([hosted(`${prefix}/this-week?region=sf&from=card-sf`).status, hosted(`${prefix}/this-week?region=sf&from=card-sf`).location], [301, `${prefix}/events?region=sf&from=card-sf`]);
    assert.deepEqual([hosted(`${prefix}/recommend`).status, hosted(`${prefix}/recommend`).location], [301, `${prefix}/events`]);
    const card = hosted(`${prefix}/n/peninsula`);
    assert.deepEqual([card.status, card.location, card.headers['Cache-Control']], [302, `${prefix}/events?region=peninsula&from=card-peninsula`, 'no-store']);
  }
  assert.equal(hosted('/n/elsewhere').kind, 'missing', 'only the printed regions');
});

test('?lang= sends an unprefixed URL to its language, keeps date/region/from/stops, and never touches the game or loops', () => {
  const redirect = hosted('/calendar?date=2026-10-10&region=sf&from=opus-title&lang=en');
  assert.equal(redirect.status, 301);
  const target = new URL(redirect.location!, 'https://www.baylink.us');
  assert.equal(target.pathname, '/en/calendar');
  for (const [key, value] of [['date', '2026-10-10'], ['region', 'sf'], ['from', 'opus-title']]) assert.equal(target.searchParams.get(key), value, key);
  assert.equal(hosted(`${target.pathname}${target.search}`).kind, 'page', 'the language URL is a page, not another redirect');
  for (const url of ['/opus-bay?lang=en', '/play?lang=zh-Hant', '/verify-email?lang=en&token=x', '/calendar?lang=zh-Hans', '/calendar?lang=fr']) assert.notEqual(hosted(url).kind, 'redirect', url);
  // every redirect lands on a page or the SPA within two hops
  for (const { url } of LEGACY_URLS) {
    let outcome = hosted(url);
    for (let hop = 0; outcome.kind === 'redirect' && hop < 2; hop++) outcome = hosted(outcome.location!);
    assert.notEqual(outcome.kind, 'redirect', `${url} redirects more than twice`);
    assert.notEqual(outcome.kind, 'missing', `${url} ends in a 404`);
  }
});

test('hosting routes are generated from the route table: static pages, SPA shell, redirects; Permissions-Policy on every response', () => {
  const table = tableHostingRoutes();
  assert.ok(routes.some(route => route.src === table.staticPages.src && route.dest === '/$1.html'), 'the static-page group is the table\'s');
  assert.ok(routes.some(route => route.src === table.spaShell.src && route.dest === '/index.html'), 'the SPA shell is the table\'s');
  for (const route of [...table.legacy, ...table.langRedirects]) assert.ok(routes.some(entry => JSON.stringify(entry) === JSON.stringify(route)), route.src);
  for (const route of routes.filter(entry => typeof entry.status === 'number' && entry.status >= 300 && entry.status < 400)) {
    assert.match(String((route.headers as Record<string, string>).Location), /^\/(?!\/)/, `${route.src}: redirects stay on this site`);
  }
  for (const route of ROUTES) {
    for (const prefix of ['', '/en', '/zh-Hant']) {
      const url = `${prefix}${route.path === '/' ? '/' : route.path.replace(/:[A-Za-z]+/g, 'sample-id-1')}`;
      const outcome = hosted(url);
      if (route.hosting === 'page') assert.equal(outcome.file, `${prefix}${route.path}.html`, url);
      if (route.hosting === 'spa') assert.match(`${outcome.kind} ${outcome.file}`, /^page \/(en\/|zh-Hant\/)?index\.html$|^function /, url);
      if (route.hosting === 'redirect') assert.equal(outcome.location, `${prefix}${route.redirect!.to}`, url);
    }
  }
  for (const url of ['/', '/events', '/en/this-week', '/me', '/assets/app.js']) assert.equal(hosted(url).headers['Permissions-Policy'], PERMISSIONS_POLICY, url);
  for (const url of ['/me', '/en/my-week', '/users/a.b', '/zh-Hant/messages/thread']) assert.equal(hosted(url).headers['X-Robots-Tag'], 'noindex, follow', url);
});
