/**
 * Baked ground of the signature corners (lane L, W5-L4 / W5-L5). GENERATED by scripts/opus-sf/corners-ground.mts from
 * the published city (public/opus-bay/sf/v1: the walked ground raster, core/sfTerrain groundRaster): do not edit by
 * hand, re-run the script after changing a corner's box. Per corner (landmarks/corners.ts CORNERS): WORLD heights in
 * 1/100 u on a grid over the corner's `box`, in the LOCAL frame of the site it dresses (x0, z0, step, cols × rows,
 * row-major). Each point is the highest walked ground within ±0.25 u (kerbs never poke through a stall's feet).
 * tests/opus-bay-w5-corners.test.ts re-measures it against the rasters.
 */
export interface CornerGroundGrid { x0: number; z0: number; step: number; cols: number; rows: number; h: readonly number[] }

export const CORNER_GROUND: Readonly<Record<string, CornerGroundGrid>> = {
  'calle-24': {
    x0: -3, z0: -0.6, step: 1, cols: 10, rows: 7,
    h: [
      314, 313, 312, 311, 310, 308, 307, 305, 304, 304,
      315, 314, 313, 311, 309, 307, 306, 305, 304, 304,
      315, 315, 313, 310, 309, 307, 306, 306, 305, 305,
      316, 315, 313, 311, 309, 307, 306, 306, 305, 305,
      316, 315, 313, 310, 309, 307, 306, 306, 305, 305,
      316, 316, 315, 312, 311, 309, 308, 307, 306, 306,
      319, 319, 321, 320, 319, 316, 314, 311, 308, 308,
    ],
  },
  'japantown': {
    x0: -4, z0: -11, step: 1, cols: 18, rows: 4,
    h: [
      1032, 1039, 1047, 1051, 1056, 1060, 1066, 1067, 1073, 1083, 1092, 1102, 1112, 1123, 1132, 1141, 1150, 1159,
      1023, 1031, 1045, 1048, 1050, 1052, 1056, 1059, 1063, 1073, 1078, 1086, 1097, 1117, 1133, 1140, 1145, 1152,
      1022, 1035, 1045, 1047, 1050, 1051, 1053, 1057, 1064, 1069, 1076, 1082, 1090, 1119, 1134, 1140, 1146, 1155,
      1022, 1037, 1043, 1047, 1050, 1051, 1052, 1056, 1064, 1068, 1074, 1082, 1092, 1117, 1134, 1140, 1147, 1156,
    ],
  },
  'noe-valley': {
    x0: -4, z0: -2.5, step: 1, cols: 11, rows: 6,
    h: [
      1164, 1171, 1182, 1187, 1193, 1193, 1192, 1186, 1178, 1169, 1150,
      1179, 1186, 1198, 1203, 1209, 1212, 1205, 1200, 1194, 1185, 1173,
      1186, 1196, 1208, 1217, 1217, 1217, 1218, 1211, 1205, 1199, 1187,
      1197, 1206, 1216, 1218, 1219, 1219, 1220, 1219, 1218, 1216, 1203,
      1205, 1211, 1216, 1217, 1218, 1219, 1220, 1221, 1221, 1222, 1214,
      1212, 1214, 1216, 1217, 1218, 1219, 1220, 1221, 1221, 1222, 1223,
    ],
  },
  'third-street': {
    x0: -7, z0: 9, step: 1, cols: 13, rows: 8,
    h: [
      425, 427, 431, 434, 435, 436, 437, 439, 444, 447, 449, 452, 465,
      425, 430, 432, 436, 438, 439, 440, 443, 447, 449, 450, 452, 463,
      436, 439, 440, 443, 444, 445, 447, 449, 452, 453, 454, 455, 462,
      444, 446, 446, 448, 449, 449, 450, 453, 456, 457, 457, 458, 463,
      449, 451, 451, 452, 453, 453, 453, 456, 459, 460, 461, 461, 465,
      455, 457, 457, 456, 457, 458, 459, 461, 463, 463, 464, 465, 472,
      462, 463, 463, 460, 461, 462, 464, 467, 467, 467, 467, 470, 496,
      477, 475, 474, 467, 468, 468, 469, 472, 472, 471, 471, 477, 503,
    ],
  },
};
