import * as THREE from 'three';
import type { Obstacle } from '../../../actors/controller';
import { registerObstacleSource } from '../../../actors/view';
import type { Bilingual, Vec2 } from '../../../core/types';
import { bayNow, bayParts } from '../../../game/bayNow';
import { type BatchLike, CONE, CYL, type ColorLike, M, SPHERE } from '../../builder';
import { TOY } from '../../materials';
import { TypedBatch } from '../../typedBatch';
import { type CrowdLane, addCrowdSpots } from '../crowdSpots';
import { SignBatch, signCell, signsMaterial } from '../signsAtlas';
import { CORNER_GROUND } from './cornerGround';
import { GLOW, LIT, NONE, SWAY, box, cbox, cyl, pyramid } from './kit';

/**
 * Wave 5 · lane L · the signature corners' kit (W5-L4 / W5-L5 / W5-L6, plan §3.6): the dressing a neighbourhood corner
 * adds to the site it stands in (Irving St, Clement St, 24th St, 3rd St, Haight, Japantown, Noe Valley, the Castro, and
 * Chinatown's Grant Ave from the Dragon Gate), drawn when that site's lod 0 is (world/sf/sites.ts SiteHooks.mount) and
 * only within CORNER_CULL u of the camera (measured from the corner's middle):
 *
 *   toy     ONE Mesh of the site's own TOY material: sign brackets, lanterns, a bus-stop seat row, a busker on his crate,
 *           market stalls … in the site's LOCAL frame (the same program as every site's lod 0: no new material)
 *   signs   ONE Mesh of lane V's signs atlas (world/sf/signsAtlas.ts SignBatch + signsMaterial, warmed as 'v-signs'):
 *           the painted bilingual plaques (generic trade words only, never a shop's name), flat on the boards or as
 *           double-sided blade signs over the sidewalk
 *   crowd   lane T's crowd spots (world/sf/crowdSpots.ts addCrowdSpots): the corner's "someone doing something" (an
 *           early queue, shoppers, listeners round a busker, neighbours at a stop), each in its Bay-time window
 *   soft    soft obstacles (actors/view registerObstacleSource) for what stands on the sidewalk only in a window (the
 *           busker, the Saturday stalls): the static walk data cannot switch with the clock
 *
 * Budget per corner (plan §4.8, tests/opus-bay-w5-corners.test.ts): ≤ 2 draw calls (the two meshes; no shadows cast),
 * ≤ 2.5k triangles, outer city only, no text meshes (the words are in the atlas texture). Bay-time windows are
 * re-read every WINDOW_POLL_MS while mounted (`?date=` in DEV / QA builds moves them); a change rebuilds the toy mesh and
 * the crowd groups. The corner's coin cache is lane E's (economy/coinSpots.ts COIN_CACHES, `cache`).
 *
 * Ground: `CornerGround.at(x, z)` = the local height over the site's base at a local point, from the corner's baked grid
 * (landmarks/cornerGround.ts, WORLD heights, generated by scripts/opus-sf/corners-ground.mts) minus the base the site
 * was mounted at (a 'terrain' landmark's base is only known then); a site's own grid can stand in (`ground`).
 */

/** a Bay-time window: minutes of the Bay day [from, to), on `days` (0 = Sunday; all days when absent) */
export interface CornerWindow { days?: readonly number[]; from: number; to: number }

/** one plaque of the signs atlas, LOCAL: centre, facing yaw `ry` (three.js), width `w` (height w / 2); `blade` = one face
 *  of a blade sign hung out over the sidewalk (else flat on a wall, a bay or a stall) */
export interface CornerSign { id: string; x: number; y: number; z: number; ry: number; w: number; blade?: true }

/** a crowd group (LOCAL coordinates; world/sf/crowdSpots.ts semantics), shown while its window is on */
export interface CornerCrowd {
  key: string;
  /** the window id (`windows`) it shows in; always when absent */
  when?: string;
  spots: { x: number; z: number; r?: number }[];
  face?: Vec2;
  count?: number;
  lane?: CrowdLane;
}

/** a soft obstacle (LOCAL) while its window is on: someone / something standing on the sidewalk for a while */
export interface CornerSoft { when?: string; x: number; z: number; r: number; kind?: 'static' | 'person' }

export interface CornerGround { at(x: number, z: number): number }

export interface CornerDef {
  /** corner id (`irving`, `clement`, `calle-24`, `third-street`, `haight`, `japantown`, `noe-valley`, `castro`) */
  id: string;
  /** the plan's row (§3.6 table: 1–4 must, 5–8) */
  order: number;
  /** the site (SF_SITES id) whose lod 0 carries the corner */
  site: string;
  /** the site's frame (a copy of its x, z, yaw: the corner's crowd and soft obstacles go to world space with it) */
  frame: { x: number; z: number; yaw: number };
  name: Bilingual;
  /** the ambient, in words (the report and the tests) */
  ambient: Bilingual;
  /** the local box (x0, z0, x1, z1) everything of the corner stays in; its ground is baked over it */
  box: readonly [number, number, number, number];
  windows?: Readonly<Record<string, CornerWindow>>;
  /** the site's own ground instead of the corner's baked grid (a shopping block whose boards the site draws) */
  ground?: CornerGround;
  /** the plaques (LOCAL) */
  signs(ground: CornerGround, on: ReadonlySet<string>): CornerSign[];
  /** the toy dressing (LOCAL, TOY conventions: aInfo.y local; the mount lifts it by the base) */
  build(b: BatchLike, ground: CornerGround, on: ReadonlySet<string>): void;
  crowds?: readonly CornerCrowd[];
  soft?: readonly CornerSoft[];
  /** lane E's cache id near the corner (economy/coinSpots.ts COIN_CACHES), null while E has none there */
  cache: string | null;
  /** the crowd's plaza additions of the corner (LOCAL polygons, already in the site's `plaza`: the tests check the spots) */
  plaza?: readonly Vec2[][];
  /**
   * `plaza` stays the corner's own (W5-L6): its crowd stands there, but the site's sightseers do not (they face the site:
   * Grant Ave's window shoppers stand 30–50 u up the street from the Dragon Gate). The tests check the spots the same way.
   */
  plazaOwn?: true;
}

/** the corner meshes stand only this close to the camera (u): their plaques are unreadable beyond, the site's lod 0 stays */
export const CORNER_CULL = 140;
/** Bay-time windows are re-read this often while a corner is mounted (ms) */
export const WINDOW_POLL_MS = 15_000;
/** budget per corner (plan §4.8) */
export const CORNER_BUDGET = { calls: 2, triangles: 2500 } as const;

// ---------------------------------------------------------------------------
// frames, windows, ground
// ---------------------------------------------------------------------------

/** Local (x, z) of a corner's site → world (landmarks/index.ts landmarkToWorld, without importing the registry). */
export function cornerToWorld(def: CornerDef, p: Vec2): Vec2 {
  const c = Math.cos(def.frame.yaw), s = Math.sin(def.frame.yaw);
  return { x: def.frame.x + p.x * c + p.z * s, z: def.frame.z - p.x * s + p.z * c };
}

/** The windows on at Bay time `parts` (game/bayNow bayParts). */
export function activeWindows(def: CornerDef, parts: { hour: number; minute: number; weekday: number }): Set<string> {
  const out = new Set<string>();
  const m = parts.hour * 60 + parts.minute;
  for (const [id, w] of Object.entries(def.windows ?? {})) {
    if (w.days && !w.days.includes(parts.weekday)) continue;
    if (m >= w.from && m < w.to) out.add(id);
  }
  return out;
}

const on = (when: string | undefined, active: ReadonlySet<string>) => !when || active.has(when);

/** World ground height at a local point from the corner's baked grid (NaN without a grid). */
export function cornerGroundWorld(id: string, x: number, z: number): number {
  const g = CORNER_GROUND[id];
  if (!g) return NaN;
  const fx = Math.min(g.cols - 1, Math.max(0, (x - g.x0) / g.step)), fz = Math.min(g.rows - 1, Math.max(0, (z - g.z0) / g.step));
  const i = Math.min(g.cols - 2, Math.floor(fx)), j = Math.min(g.rows - 2, Math.floor(fz));
  const u = fx - i, v = fz - j, k = j * g.cols + i;
  const a = g.h[k] * (1 - u) + g.h[k + 1] * u, b = g.h[k + g.cols] * (1 - u) + g.h[k + g.cols + 1] * u;
  return (a * (1 - v) + b * v) / 100;
}

/** The corner's ground as local heights over `baseY` (its own grid; the site's when it gives one). */
export function cornerGround(def: CornerDef, baseY: number): CornerGround {
  if (def.ground) return def.ground;
  return { at: (x, z) => { const y = cornerGroundWorld(def.id, x, z); return Number.isFinite(y) ? y - baseY : 0; } };
}

// ---------------------------------------------------------------------------
// the meshes
// ---------------------------------------------------------------------------

export interface CornerMeshes { toy: THREE.Mesh | null; signs: THREE.Mesh | null; triangles: number; plaques: number }

/** Build the corner's two meshes (LOCAL frame of its site) for the windows `active`, the site mounted at `baseY`. */
export function buildCornerMeshes(def: CornerDef, baseY: number, active: ReadonlySet<string>): CornerMeshes {
  const ground = cornerGround(def, baseY);
  let triangles = 0, plaques = 0;
  const b = new TypedBatch(4096);
  def.build(b, ground, active);
  let toy: THREE.Mesh | null = null;
  if (b.vertexCount) {
    const a = b.toArrays();
    for (let i = 0; i < a.vertexCount; i++) a.info[i * 4 + 1] += baseY;
    toy = new THREE.Mesh(TypedBatch.toGeometry(a), TOY);
    toy.name = `sf:${def.site}:corner-toy`;
    toy.castShadow = false;
    toy.receiveShadow = true;
    toy.matrixAutoUpdate = false;
    triangles += a.indexCount / 3;
  }
  const sb = new SignBatch();
  for (const s of def.signs(ground, active)) sb.plaque(s.id, s.x, s.y, s.z, s.ry, s.w);
  let signs: THREE.Mesh | null = null;
  if (sb.count) {
    signs = new THREE.Mesh(sb.build(), signsMaterial());
    signs.name = `sf:${def.site}:corner-signs`;
    signs.castShadow = false;
    signs.receiveShadow = true;
    signs.matrixAutoUpdate = false;
    plaques = sb.count;
    triangles += sb.count * 2;
  }
  return { toy, signs, triangles, plaques };
}

/** What a mounted corner holds (tests and QA read it through `cornerState`). */
export interface CornerMounted { def: CornerDef; active: Set<string>; meshes: CornerMeshes; lod: THREE.LOD; crowds: string[]; soft: Obstacle[] }
const mounted = new Map<string, CornerMounted>();
/** The corners mounted now (QA: `window` console, tests). */
export function cornerState(): ReadonlyMap<string, CornerMounted> { return mounted; }

function disposeMeshes(m: CornerMeshes) { m.toy?.geometry.dispose(); m.signs?.geometry.dispose(); }

/**
 * The SiteHooks.mount of a corner's site: builds the two meshes into a THREE.LOD (drawn within CORNER_CULL u of the
 * camera: three's renderer updates a LOD as it projects it), registers the crowd groups and soft obstacles of the
 * windows on now, and re-reads the windows every WINDOW_POLL_MS. Returns the unmount.
 */
export function cornerMount(def: CornerDef): (group: THREE.Group, baseY: number) => () => void {
  return (group, baseY) => {
    const lod = new THREE.LOD();
    lod.name = `sf:${def.site}:corner`;
    const near = new THREE.Group(), far = new THREE.Object3D();
    // the LOD measures its distance from the corner's own middle (a corner may stand 40 u from its site's origin: the
    // Chinatown corner up Grant Ave from the Dragon Gate); the meshes keep the site's local frame
    const cx = (def.box[0] + def.box[2]) / 2, cz = (def.box[1] + def.box[3]) / 2;
    lod.position.set(cx, 0, cz);
    near.position.set(-cx, 0, -cz);
    lod.addLevel(near, 0);
    lod.addLevel(far, CORNER_CULL);
    group.add(lod);
    const st: CornerMounted = { def, active: new Set(), meshes: { toy: null, signs: null, triangles: 0, plaques: 0 }, lod, crowds: [], soft: [] };
    const offCrowds: (() => void)[] = [];
    const apply = (active: Set<string>) => {
      // meshes
      if (st.meshes.toy) near.remove(st.meshes.toy);
      if (st.meshes.signs) near.remove(st.meshes.signs);
      disposeMeshes(st.meshes);
      st.meshes = buildCornerMeshes(def, baseY, active);
      for (const m of [st.meshes.toy, st.meshes.signs]) if (m) { m.updateMatrix(); near.add(m); }
      near.updateMatrixWorld(true);
      // crowds
      for (const off of offCrowds.splice(0)) off();
      st.crowds = [];
      for (const c of def.crowds ?? []) {
        if (!on(c.when, active)) continue;
        const key = `corner:${def.id}:${c.key}`;
        const W = (p: Vec2) => cornerToWorld(def, p);
        const lane = c.lane ? (() => { const a = W({ x: c.lane!.ax, z: c.lane!.az }), b = W({ x: c.lane!.bx, z: c.lane!.bz }); return { ax: a.x, az: a.z, bx: b.x, bz: b.z }; })() : undefined;
        offCrowds.push(addCrowdSpots(key, c.spots.map(s => ({ ...W(s), r: s.r })), { face: c.face ? W(c.face) : undefined, count: c.count, lane }));
        st.crowds.push(key);
      }
      // soft obstacles
      st.soft = (def.soft ?? []).filter(s => on(s.when, active)).map(s => ({ ...cornerToWorld(def, s), r: s.r, kind: s.kind ?? 'static' }));
      st.active = active;
    };
    apply(activeWindows(def, bayParts(bayNow())));
    const offSoft = registerObstacleSource((out, x, z, r) => {
      for (const o of st.soft) { const d = r + o.r; if ((o.x - x) ** 2 + (o.z - z) ** 2 <= d * d) out.push(o); }
    });
    const same = (a: Set<string>, b: Set<string>) => a.size === b.size && [...a].every(k => b.has(k));
    const timer = def.windows ? setInterval(() => {
      const next = activeWindows(def, bayParts(bayNow()));
      if (!same(next, st.active)) apply(next);
    }, WINDOW_POLL_MS) : null;
    mounted.set(def.id, st);
    return () => {
      if (timer) clearInterval(timer);
      offSoft();
      for (const off of offCrowds.splice(0)) off();
      group.remove(lod);
      disposeMeshes(st.meshes);
      if (mounted.get(def.id) === st) mounted.delete(def.id);
    };
  };
}

/** A batch that draws nothing: a corner's `signs` asks `blade` where its plaques go without drawing the hardware. */
export const NO_BATCH = { add() { return this; }, beam() { return this; }, quad() { return this; } } as unknown as BatchLike;

/** Known plaque ids only (a corner's table is checked against the atlas: an unknown id would silently draw nothing). */
export const signKnown = (id: string) => signCell(id) >= 0;

// ---------------------------------------------------------------------------
// the toy pieces (LOCAL frame; y = the ground under the piece)
// ---------------------------------------------------------------------------

export const CK = {
  iron: '#3d4447',
  bracket: '#34383a',
  backing: '#2f2b28',
  crate: '#a07a52',
  canvas: '#efe6d2',
  pole: '#56605c',
  skin: ['#e9c3a0', '#c68e63', '#8d5a3b', '#f1d2b4'],
  shirt: ['#d8744a', '#2f8f88', '#e0a94a', '#7a4fa0', '#4f7fbf', '#c94f7c'],
  pants: '#4b5563',
  guitar: '#b5763f',
  guitarDark: '#5a3a22',
} as const;

/**
 * A blade sign's hardware: an iron bracket out of the wall at `yTop` and a thin dark backing board between the two faces
 * of the plaque. `x` = along the wall, the plaque's plane at x, spanning z from `z0` (near the wall) to `z1`; returns the
 * two plaques (one each way along x). `w` = the plaque width (its height w / 2), hung just under the bracket.
 */
export function bladeSign(b: BatchLike, id: string, x: number, yTop: number, z0: number, z1: number, w: number): CornerSign[] {
  const zc = (z0 + z1) / 2, len = Math.abs(z1 - z0), h = w / 2, yc = yTop - 0.05 - h / 2;
  cbox(b, x, yTop, zc, 0.05, 0.05, len + 0.15, CK.bracket);
  cbox(b, x, yc, zc, 0.03, h + 0.04, w + 0.04, CK.backing);
  return [
    { id, x: x + 0.016, y: yc, z: zc, ry: Math.PI / 2, w, blade: true },
    { id, x: x - 0.016, y: yc, z: zc, ry: -Math.PI / 2, w, blade: true },
  ];
}

/**
 * A blade sign on any wall: the wall at local (x, z) faces yaw `ry`; the bracket runs out along that facing at `yTop`,
 * the plaque (width `w`, height w / 2) hangs under it from `off` to off + w u out, readable both ways along the wall.
 */
export function blade(b: BatchLike, id: string, x: number, z: number, yTop: number, ry: number, w: number, off = 0.08): CornerSign[] {
  const fx = Math.sin(ry), fz = Math.cos(ry), rx = Math.cos(ry), rz = -Math.sin(ry), h = w / 2, yc = yTop - 0.05 - h / 2;
  const cx = x + fx * (off + w / 2), cz = z + fz * (off + w / 2);
  cbox(b, x + fx * (off + w / 2 + 0.04), yTop, z + fz * (off + w / 2 + 0.04), 0.05, 0.05, w + 0.15, CK.bracket, NONE, ry);
  cbox(b, cx, yc, cz, 0.03, h + 0.04, w + 0.04, CK.backing, NONE, ry);
  return [
    { id, x: cx + rx * 0.016, y: yc, z: cz + rz * 0.016, ry: ry + Math.PI / 2, w, blade: true },
    { id, x: cx - rx * 0.016, y: yc, z: cz - rz * 0.016, ry: ry - Math.PI / 2, w, blade: true },
  ];
}

/** A street lamp post (like the sites' lamps: post, glowing lantern, cap; ≈ 56 triangles) at local (x, y, z). */
export function lampPost(b: BatchLike, x: number, y: number, z: number) {
  b.add(CYL(6), M(x, y, z, 0, 0.1, 0.45, 0.1), '#2f3d3a');
  b.add(CYL(5), M(x, y + 0.4, z, 0, 0.06, 3.2, 0.06), '#2f3d3a');
  b.add(CYL(6, 0.7), M(x, y + 3.55, z, 0, 0.22, 0.5, 0.22), '#fff1c9', [0, 0, 0, 1.3]);
  b.add(CONE(6), M(x, y + 4.02, z, 0, 0.3, 0.3, 0.3), '#2f3d3a');
}

/** A noren (a shop's short split curtain) over a door at local (x, z) on a wall facing `ry`, its top `y` over the ground. */
export function noren(b: BatchLike, x: number, z: number, ry: number, y: number, color: ColorLike, w = 0.72) {
  const fx = Math.sin(ry), fz = Math.cos(ry), rx = Math.cos(ry), rz = -Math.sin(ry), n = 3, pw = (w - 0.04 * (n - 1)) / n;
  cbox(b, x + fx * 0.06, y, z + fz * 0.06, w + 0.1, 0.04, 0.04, CK.bracket, NONE, ry);
  for (let i = 0; i < n; i++) {
    const u = (i - (n - 1) / 2) * (pw + 0.04);
    cbox(b, x + rx * u + fx * 0.07, y - 0.27, z + rz * u + fz * 0.07, pw, 0.5, 0.015, color, SWAY(0.3), ry);
  }
}

/** A paper lantern (a squat sphere with a dark cap and foot), glowing at night; hung with its top at `y`. */
export function lantern(b: BatchLike, x: number, y: number, z: number, color: ColorLike, r = 0.16) {
  b.add(SPHERE(8, 5), M(x, y - r * 1.25, z, 0, r, r * 1.2, r), color, GLOW(0.95));
  cyl(b, x, y - 0.06, z, r * 0.45, 0.06, CK.backing, NONE, 6);
  cyl(b, x, y - r * 2.5, z, r * 0.45, 0.05, CK.backing, NONE, 6);
}

/** A string sagging from a to c (local points with their heights) with a lantern every `every` u, colours in turn. */
export function lanternString(b: BatchLike, a: THREE.Vector3, c: THREE.Vector3, colors: readonly ColorLike[], every = 0.9, sag = 0.3, seed = 0) {
  const n = Math.max(2, Math.round(a.distanceTo(c) / every));
  const pts: THREE.Vector3[] = [];
  for (let k = 0; k <= n; k++) { const t = k / n; pts.push(new THREE.Vector3(a.x + (c.x - a.x) * t, a.y + (c.y - a.y) * t - sag * 4 * t * (1 - t), a.z + (c.z - a.z) * t)); }
  for (let k = 0; k < n; k++) b.beam(pts[k], pts[k + 1], 0.025, 0.025, '#3a3431');
  for (let k = 1; k < n; k++) lantern(b, pts[k].x, pts[k].y, pts[k].z, colors[(k + seed) % colors.length]);
}

/** A string of cut-paper flags (papel-picado colours only: no words, no figures) sagging from a to c. */
export function paperString(b: BatchLike, a: THREE.Vector3, c: THREE.Vector3, colors: readonly ColorLike[], sag = 0.3, seed = 0) {
  const n = Math.max(3, Math.round(a.distanceTo(c) / 0.34));
  const pts: THREE.Vector3[] = [];
  for (let k = 0; k <= n; k++) { const t = k / n; pts.push(new THREE.Vector3(a.x + (c.x - a.x) * t, a.y + (c.y - a.y) * t - sag * 4 * t * (1 - t), a.z + (c.z - a.z) * t)); }
  const ry = Math.atan2(c.x - a.x, c.z - a.z) + Math.PI / 2;
  for (let k = 0; k < n; k++) {
    const p = pts[k], q = pts[k + 1];
    b.beam(p, q, 0.02, 0.02, '#f4efe2');
    cbox(b, (p.x + q.x) / 2, (p.y + q.y) / 2 - 0.15, (p.z + q.z) / 2, 0.24, 0.26, 0.012, colors[(k + seed) % colors.length], SWAY(0.6), ry);
  }
}

/** A row of `n` bolted iron seats (the Oakdale / Palou plaza's, facing yaw `ry`), 0.5 u apart along the row. */
export function ironSeats(b: BatchLike, x: number, y: number, z: number, ry: number, n: number) {
  const ax = Math.cos(ry), az = -Math.sin(ry);
  for (let i = 0; i < n; i++) {
    const o = (i - (n - 1) / 2) * 0.55, sx = x + ax * o, sz = z + az * o;
    cyl(b, sx, y - 0.05, sz, 0.05, 0.42, CK.iron, NONE, 5);
    cbox(b, sx, y + 0.42, sz, 0.36, 0.05, 0.34, CK.iron, NONE, ry);
    cbox(b, sx - Math.sin(ry) * 0.16, y + 0.62, sz - Math.cos(ry) * 0.16, 0.36, 0.34, 0.04, CK.iron, NONE, ry);
  }
}

/**
 * A standing guitarist (a toy figure of the crowd's proportions, ≈ 1.45 u) playing, facing yaw `ry`, with his guitar case
 * open on the ground `caseAt` u to his side (a few coins in it). Colours from `k`. ≈ 330 triangles.
 */
export function guitarist(b: BatchLike, x: number, y: number, z: number, ry: number, k = 0, caseAt = -0.75) {
  const fx = Math.sin(ry), fz = Math.cos(ry), rx = Math.cos(ry), rz = -Math.sin(ry);
  const P = (u: number, v: number) => ({ x: x + rx * u + fx * v, z: z + rz * u + fz * v });
  const V = (u: number, h: number, v: number) => { const p = P(u, v); return new THREE.Vector3(p.x, y + h, p.z); };
  const skin = CK.skin[k % CK.skin.length], shirt = CK.shirt[k % CK.shirt.length];
  for (const s of [-1, 1]) {
    const l = P(s * 0.09, 0);
    b.add(CYL(6), M(l.x, y + 0.04, l.z, ry, 0.075, 0.46, 0.075), CK.pants);
    const f = P(s * 0.09, 0.04);
    b.add(SPHERE(5, 3), M(f.x, y + 0.04, f.z, ry, 0.085, 0.055, 0.13), '#3c3a38');
  }
  b.add(CYL(8), M(x, y + 0.48, z, ry, 0.21, 0.5, 0.19), shirt);
  b.add(SPHERE(8, 6), M(x, y + 1.2, z, ry, 0.2, 0.21, 0.2), skin);
  b.add(SPHERE(6, 4), M(x - fx * 0.02, y + 1.29, z - fz * 0.02, ry, 0.205, 0.13, 0.205), '#3a2a22');
  // the guitar across the body: the body low on one side, the neck rising to the other hand
  const gb = P(0.1, 0.22);
  b.add(SPHERE(8, 5), M(gb.x, y + 0.66, gb.z, ry, 0.2, 0.25, 0.07, 0, -0.45), CK.guitar);
  b.add(CYL(6), M(gb.x - fx * 0.05, y + 0.68, gb.z - fz * 0.05, ry, 0.055, 0.02, 0.055, Math.PI / 2), CK.guitarDark);
  const nk = P(-0.2, 0.24);
  cbox(b, nk.x, y + 0.84, nk.z, 0.62, 0.05, 0.05, CK.guitarDark, NONE, ry, 0, -0.45);
  // arms: one strums over the body, the other holds the neck
  b.beam(V(0.2, 0.93, 0), V(0.16, 0.7, 0.26), 0.09, 0.09, shirt);
  b.beam(V(-0.2, 0.93, 0), V(-0.36, 0.9, 0.26), 0.09, 0.09, shirt);
  for (const [u, h] of [[0.16, 0.7], [-0.36, 0.92]]) { const p = P(u, 0.28); b.add(SPHERE(5, 3), M(p.x, y + h, p.z, 0, 0.06, 0.06, 0.06), skin); }
  // the open case beside him, along the wall, with a few coins
  const cs = P(caseAt, 0.05);
  box(b, cs.x, y, cs.z, 0.9, 0.08, 0.34, CK.backing, NONE, ry);
  box(b, cs.x, y + 0.02, cs.z, 0.82, 0.07, 0.27, '#8a2f3a', NONE, ry);
  for (const [du, dv] of [[-0.12, 0.03], [0.1, -0.05], [0.24, 0.04]]) { const c = P(caseAt + du, 0.05 + dv); cyl(b, c.x, y + 0.09, c.z, 0.035, 0.01, '#e7c25a', GLOW(0.2), 6); }
}

/**
 * A shop awning over a sidewalk: a sloped slab out of the wall, its wall edge centred at local (cx, cz) and `y` over the
 * ground, `w` wide along the wall, reaching `d` u out toward the way the shop faces (yaw `ry`, three.js); a valance
 * along its front. ≈ 24 triangles.
 */
export function awning(b: BatchLike, cx: number, cz: number, w: number, ry: number, y: number, d: number, color: ColorLike, valance: ColorLike = '#f4efe2') {
  const fx = Math.sin(ry), fz = Math.cos(ry), tilt = 0.3, dz = Math.cos(tilt) * d, dy = Math.sin(tilt) * d;
  cbox(b, cx + (fx * dz) / 2, y - dy / 2, cz + (fz * dz) / 2, w, 0.06, d, color, NONE, ry, tilt);
  cbox(b, cx + fx * (dz + 0.01), y - dy - 0.1, cz + fz * (dz + 0.01), w, 0.2, 0.03, valance, NONE, ry);
}

/**
 * A painted shopfront on a plain city wall (the storefront band in one colour, a lit window, a door, a trim band), its
 * foot centred at local (cx, cz) and `y`, `w` wide, facing yaw `ry`. 48 triangles.
 */
export function shopfront(b: BatchLike, cx: number, cz: number, w: number, ry: number, y: number, color: ColorLike, trim: ColorLike = '#f4efe2') {
  const fx = Math.sin(ry), fz = Math.cos(ry), rx = Math.cos(ry), rz = -Math.sin(ry);
  const at = (u: number, off: number) => ({ x: cx + rx * u + fx * off, z: cz + rz * u + fz * off });
  const p = at(0, 0.02);
  box(b, p.x, y - 0.1, p.z, w, 2.45, 0.04, color, NONE, ry);
  const t = at(0, 0.05);
  box(b, t.x, y + 2.2, t.z, w + 0.06, 0.14, 0.05, trim, NONE, ry);
  const win = at(-w * 0.17, 0.05);
  box(b, win.x, y + 0.55, win.z, w * 0.5, 1.2, 0.03, '#3f4a52', LIT(y), ry);
  const door = at(w * 0.3, 0.05);
  box(b, door.x, y, door.z, Math.min(0.5, w * 0.24), 1.55, 0.03, '#4a3a30', LIT(y), ry);
}

/** A neighbour sitting on a seat (the crowd's figure, seated; hands on the knees), facing yaw `ry`; seat height `sh`. */
export function sitter(b: BatchLike, x: number, y: number, z: number, ry: number, k = 0, sh = 0.44) {
  const fx = Math.sin(ry), fz = Math.cos(ry), rx = Math.cos(ry), rz = -Math.sin(ry);
  const P = (u: number, v: number) => ({ x: x + rx * u + fx * v, z: z + rz * u + fz * v });
  const skin = CK.skin[(k + 1) % CK.skin.length], shirt = CK.shirt[(k + 2) % CK.shirt.length];
  for (const s of [-1, 1]) {
    const t = P(s * 0.1, 0.16), f = P(s * 0.1, 0.34);
    cbox(b, t.x, y + sh + 0.05, t.z, 0.14, 0.13, 0.36, CK.pants, NONE, ry);
    cbox(b, f.x, y + (sh + 0.05) / 2, f.z, 0.12, sh + 0.05, 0.13, CK.pants, NONE, ry);
    const shoe = P(s * 0.1, 0.4);
    b.add(SPHERE(5, 3), M(shoe.x, y + 0.03, shoe.z, ry, 0.08, 0.05, 0.12), '#3c3a38');
    const h = P(s * 0.2, 0.24);
    b.add(SPHERE(5, 3), M(h.x, y + sh + 0.16, h.z, 0, 0.06, 0.06, 0.06), skin);
  }
  b.add(CYL(8), M(x, y + sh, z, ry, 0.2, 0.52, 0.18), shirt);
  b.add(SPHERE(8, 6), M(x, y + sh + 0.72, z, ry, 0.19, 0.2, 0.19), skin);
  b.add(SPHERE(6, 4), M(x - fx * 0.02, y + sh + 0.8, z - fz * 0.02, ry, 0.195, 0.12, 0.195), '#2f2622');
}

/** A market stall: four posts, a canopy in `color`, a trestle with crates of produce. `w` × `d`, front facing yaw `ry`. */
export function stall(b: BatchLike, x: number, y: number, z: number, ry: number, color: ColorLike, crates: readonly ColorLike[], w = 1.3, d = 1.0) {
  const fx = Math.sin(ry), fz = Math.cos(ry), rx = Math.cos(ry), rz = -Math.sin(ry);
  const P = (u: number, v: number) => ({ x: x + rx * u + fx * v, z: z + rz * u + fz * v });
  for (const [u, v] of [[-w / 2 + 0.05, -d / 2 + 0.05], [w / 2 - 0.05, -d / 2 + 0.05], [w / 2 - 0.05, d / 2 - 0.05], [-w / 2 + 0.05, d / 2 - 0.05]]) {
    const p = P(u, v);
    box(b, p.x, y - 0.1, p.z, 0.05, 1.65, 0.05, '#dcd8cf', NONE, ry);
  }
  cbox(b, x, y + 1.6, z, w + 0.1, 0.1, d + 0.1, color, SWAY(0.15), ry);
  const t = P(0, d / 2 - 0.3);
  box(b, t.x, y - 0.05, t.z, w - 0.1, 0.62, 0.5, '#8a6a4a', NONE, ry);
  for (let c = 0; c < 3; c++) { const p = P((c - 1) * ((w - 0.2) / 3), d / 2 - 0.3); box(b, p.x, y + 0.57, p.z, (w - 0.2) / 3 - 0.06, 0.16, 0.4, crates[c % crates.length], NONE, ry); }
}

/** A café table with two chairs (the square on a weekday), facing yaw `ry`. */
export function cafeTable(b: BatchLike, x: number, y: number, z: number, ry: number, top: ColorLike = '#2f6f4a') {
  cyl(b, x, y - 0.05, z, 0.05, 0.62, CK.iron, NONE, 5);
  cyl(b, x, y + 0.57, z, 0.3, 0.04, top, NONE, 10);
  for (const s of [-1, 1]) {
    const cx = x + Math.cos(ry) * s * 0.45, cz = z - Math.sin(ry) * s * 0.45;
    for (const [dx, dz] of [[-0.1, -0.1], [0.1, -0.1], [0.1, 0.1], [-0.1, 0.1]]) cyl(b, cx + dx, y - 0.05, cz + dz, 0.02, 0.4, CK.iron, NONE, 4);
    cbox(b, cx, y + 0.36, cz, 0.3, 0.04, 0.3, top, NONE, ry);
    cbox(b, cx + Math.cos(ry) * s * 0.14, y + 0.55, cz - Math.sin(ry) * s * 0.14, 0.03, 0.34, 0.3, top, NONE, ry);
  }
}

/**
 * A Chinatown dragon lamp (toy of the 1925 Grant Avenue design: a cast base, a green shaft with gold bands, two gold
 * dragons under a pagoda lantern hung with bells, a red roof and a gold finial; the lantern glows at night), its foot at
 * local (x, y, z), turned `ry`. 134 triangles.
 */
export function dragonLamp(b: BatchLike, x: number, y: number, z: number, ry = 0) {
  const GREEN = '#2f6b4f', GOLD = '#d7a53c', RED = '#b8432f', rx = Math.cos(ry), rz = -Math.sin(ry);
  cyl(b, x, y - 0.05, z, 0.12, 0.42, '#2b3531', NONE, 6);
  cyl(b, x, y + 0.37, z, 0.055, 2.28, GREEN, NONE, 5);
  for (const h of [0.9, 1.85]) cyl(b, x, y + h, z, 0.075, 0.07, GOLD, NONE, 5);
  // the two dragons: gold curls leaning out either side of the shaft's head
  for (const s of [-1, 1]) cbox(b, x + rx * s * 0.12, y + 2.6, z + rz * s * 0.12, 0.25, 0.07, 0.07, GOLD, NONE, ry, 0, s * 0.65);
  // the lantern in its gold frame, two bells under the frame's corners
  cbox(b, x, y + 2.98, z, 0.28, 0.4, 0.28, '#ffb45e', GLOW(1), ry);
  cbox(b, x, y + 2.76, z, 0.36, 0.05, 0.36, GOLD, NONE, ry);
  for (const s of [-1, 1]) cbox(b, x + (rx + rz) * s * 0.15, y + 2.68, z + (rz - rx) * s * 0.15, 0.05, 0.09, 0.05, GOLD, NONE, ry);
  // the red pagoda roof and its finial
  pyramid(b, x, y + 3.18, z, 0.6, 0.6, 0.26, RED, ry);
  cbox(b, x, y + 3.5, z, 0.06, 0.14, 0.06, GOLD, NONE, ry);
}

/**
 * A row of red paper lanterns with gold caps on a wire strung between two fronts: from local a to c (the wire's ends,
 * `y` over the ground at both), sagging `sag` in the middle, a lantern at each of `at` (0..1 along the wire), glowing at
 * night. 24 triangles a lantern, 6 a wire segment.
 */
export function lanternWire(b: BatchLike, a: Vec2, c: Vec2, y: number, at: readonly number[], sag = 0.35, color: ColorLike = '#c8322a') {
  const P = (t: number) => new THREE.Vector3(a.x + (c.x - a.x) * t, y - sag * 4 * t * (1 - t), a.z + (c.z - a.z) * t);
  const ry = Math.atan2(c.x - a.x, c.z - a.z);
  const ts = [0, ...at, 1];
  for (let k = 0; k + 1 < ts.length; k++) b.beam(P(ts[k]), P(ts[k + 1]), 0.018, 0.018, '#3a2c22');
  for (const t of at) {
    const p = P(t);
    cbox(b, p.x, p.y - 0.3, p.z, 0.26, 0.3, 0.26, color, GLOW(0.85), ry);
    box(b, p.x, p.y - 0.17, p.z, 0.14, 0.06, 0.14, '#d7a53c', NONE, ry);
  }
}

/**
 * A rainbow banner on a lamp pole (the district's pole banners: the six-stripe pride flag, no text), its top at `y`,
 * hung from a bracket running `off` u along (cos ry, −sin ry) from the pole; `w` wide along the bracket, 0.78 tall.
 */
export function rainbowBanner(b: BatchLike, x: number, y: number, z: number, ry: number, off = 0.32, w = 0.5) {
  const RAINBOW = ['#e40303', '#ff8c00', '#ffed00', '#008026', '#004dff', '#750787'];
  const ox = Math.cos(ry) * off, oz = -Math.sin(ry) * off, sh = 0.13;
  cbox(b, x + ox / 2, y + 0.04, z + oz / 2, off + w / 2, 0.035, 0.035, CK.bracket, NONE, ry);
  RAINBOW.forEach((c, i) => cbox(b, x + ox, y - sh * (i + 0.5), z + oz, 0.02, sh, w, c, SWAY(0.4), ry + Math.PI / 2));
}
