import type { Vec2 } from '../../../core/types';
import { CITY_PAL } from '../../palette';
import type { LandmarkGround, WalkBlocker } from './index';
import { SETTING_DATA } from './settingData';
import type { SiteGround } from './siteKit';

/**
 * Landmark settings (lane D2, D2-09): the ground a landmark's own plazas, street strips and furniture stand on, and
 * the city streets its exclusion clips, restored as ground strips. DECLARATIVE like the registry (data and maths, node
 * safe). Everything in the landmark's LOCAL frame (y above its base, as world/sf/sites.ts places it).
 *
 *   settingGround(id)       the measured drawn city ground (landmarks/settingData.ts, generated by
 *                           scripts/opus-sf/assets/landmark-settings.ts): a SiteGround, so lane L's plaza kit
 *                           (landmarks/siteKit.ts gfill / gstrip / crosswalk, benches, lamps, trees) drapes on it
 *   streetStrips(id, keep)  the clipped streets as the city draws them (build.ts streetsL0: sidewalk band, asphalt, kerbs,
 *                           centre dashes, footways, rails), draped along their own centreline heights, so a street runs
 *                           on through a gate or past a plaza instead of stopping at the exclusion
 *   plazaSpots(polys)       evenly spaced points on plaza polygons (context.ts landmarkPlazaSpots, lane F's crowd)
 */

/** Street lifts over the ground, as the city draws them (world/sf/build.ts LIFT) */
const LIFT = { walk: 0.035, asphalt: 0.055, rail: 0.075, dash: 0.07 } as const;
/** core/geo CURB_BAND: the sidewalk band on each side of a street's asphalt */
const CURB_BAND = 0.6;
const P = { none: 0, stone: 2, asphalt: 5, cobble: 6, earth: 7 } as const;

interface StreetStyle { walk: string; walkPat: number; asphalt?: string; dash?: boolean }
/** world/sf/build.ts STREET, with the running-bond pavers as plaza stone (a polygon pattern) */
const STREET: Record<string, StreetStyle> = {
  motorway: { walk: CITY_PAL.curb, walkPat: P.none, asphalt: CITY_PAL.motorway, dash: true },
  trunk: { walk: CITY_PAL.sidewalk, walkPat: P.stone, asphalt: CITY_PAL.asphaltMajor, dash: true },
  primary: { walk: CITY_PAL.sidewalk, walkPat: P.stone, asphalt: CITY_PAL.asphaltMajor, dash: true },
  secondary: { walk: CITY_PAL.sidewalk, walkPat: P.stone, asphalt: CITY_PAL.asphalt, dash: true },
  tertiary: { walk: CITY_PAL.sidewalk, walkPat: P.stone, asphalt: CITY_PAL.asphalt, dash: true },
  residential: { walk: CITY_PAL.sidewalk, walkPat: P.stone, asphalt: CITY_PAL.asphalt },
  service: { walk: CITY_PAL.asphalt, walkPat: P.asphalt },
  pedestrian: { walk: CITY_PAL.pedestrian, walkPat: P.stone },
  footway: { walk: CITY_PAL.footway, walkPat: P.stone },
  path: { walk: CITY_PAL.path, walkPat: P.earth },
  cycleway: { walk: CITY_PAL.cycleway, walkPat: P.earth },
  steps: { walk: CITY_PAL.steps, walkPat: P.stone },
  track: { walk: CITY_PAL.track, walkPat: P.earth },
};

/** The measured drawn ground under landmark `id` (0 everywhere when it has no row). */
export function settingGround(id: string): SiteGround {
  const d = SETTING_DATA[id];
  if (!d) return { base: 0, grid: null, at: () => 0 };
  const { x0, z0, step, cols, rows, h } = d.grid;
  const at = (x: number, z: number) => {
    const fx = Math.min(cols - 1, Math.max(0, (x - x0) / step)), fz = Math.min(rows - 1, Math.max(0, (z - z0) / step));
    const i = Math.min(cols - 2, Math.floor(fx)), j = Math.min(rows - 2, Math.floor(fz));
    const u = fx - i, v = fz - j, k = j * cols + i;
    const a = h[k] * (1 - u) + h[k + 1] * u, b = h[k + cols] * (1 - u) + h[k + cols + 1] * u;
    return (a * (1 - v) + b * v) / 100;
  };
  return { base: d.base, grid: { base: d.base, ...d.grid }, at };
}

export type P3 = { x: number; y: number; z: number };

/**
 * One quad per segment of a ribbon along `pts` (mitred joints, square ends), width w, offset sideways, + lift: level
 * across at the centreline's y, or each corner on `drape(x, z)` (a street laid on a cross slope).
 */
function ribbon(pts: readonly P3[], w: number, lift: number, color: string, pattern: number, offset = 0, drape?: (x: number, z: number) => number): LandmarkGround[] {
  const n = pts.length;
  if (n < 2) return [];
  const side: Vec2[] = [];
  for (let i = 0; i < n; i++) {
    const a = pts[Math.max(0, i - 1)], b = pts[Math.min(n - 1, i + 1)];
    let tx = b.x - a.x, tz = b.z - a.z;
    const tl = Math.hypot(tx, tz) || 1;
    tx /= tl; tz /= tl;
    // miter: scale by 1 / cos of the half turn (limited to 1.6)
    let k = 1;
    if (i > 0 && i < n - 1) {
      const p = pts[i - 1], q = pts[i + 1], c = pts[i];
      const ux = c.x - p.x, uz = c.z - p.z, vx = q.x - c.x, vz = q.z - c.z, lu = Math.hypot(ux, uz) || 1, lv = Math.hypot(vx, vz) || 1;
      const cos = (ux * vx + uz * vz) / (lu * lv);
      k = Math.min(1.6, 1 / Math.max(0.1, Math.sqrt((1 + cos) / 2)));
    }
    side.push({ x: -tz * k, z: tx * k });
  }
  const out: LandmarkGround[] = [];
  const lo = offset - w / 2, hi = offset + w / 2;
  for (let i = 0; i + 1 < n; i++) {
    const a = pts[i], b = pts[i + 1], sa = side[i], sb = side[i + 1];
    const poly = [
      { x: a.x + sa.x * lo, z: a.z + sa.z * lo }, { x: b.x + sb.x * lo, z: b.z + sb.z * lo },
      { x: b.x + sb.x * hi, z: b.z + sb.z * hi }, { x: a.x + sa.x * hi, z: a.z + sa.z * hi },
    ].map(p => ({ x: Math.round(p.x * 1000) / 1000, z: Math.round(p.z * 1000) / 1000 }));
    const ya = +(a.y + lift).toFixed(3), yb = +(b.y + lift).toFixed(3);
    const ys = drape ? poly.map(p => +(drape(p.x, p.z) + lift).toFixed(3)) : [ya, yb, yb, ya];
    out.push({ poly, y: ys.reduce((q, y) => q + y, 0) / 4, ys, color, pattern, angle: Math.atan2(b.x - a.x, b.z - a.z) });
  }
  return out;
}

/** Centre dashes (on / period u along the line), as world/sf/mesh.ts dashes. */
function dashes(pts: readonly P3[], w: number, lift: number, color: string, on: number, period: number, drape?: (x: number, z: number) => number): LandmarkGround[] {
  const out: LandmarkGround[] = [];
  let acc = 0;
  for (let k = 0; k + 1 < pts.length; k++) {
    const a = pts[k], b = pts[k + 1], L = Math.hypot(b.x - a.x, b.z - a.z);
    if (L < 1e-4) continue;
    for (let m = Math.floor(acc / period); m * period < acc + L; m++) {
      const t0 = Math.max(0, m * period - acc), t1 = Math.min(L, m * period + on - acc);
      if (t1 - t0 < 0.2) continue;
      const at = (t: number): P3 => ({ x: a.x + ((b.x - a.x) * t) / L, y: a.y + ((b.y - a.y) * t) / L, z: a.z + ((b.z - a.z) * t) / L });
      out.push(...ribbon([at(t0), at(t1)], w, lift, color, P.none, 0, drape));
    }
    acc += L;
  }
  return out;
}

/**
 * The streets landmark `id`'s exclusion clips, as ground strips drawn the city's way (build.ts streetsL0). `keep`
 * drops segments by their midpoint (LOCAL x, z) and class (a lagoon, a building footprint the landmark covers): a
 * piece splits into the runs that stay.
 */
export function streetStrips(id: string, keep: (x: number, z: number, cls: string) => boolean = () => true): LandmarkGround[] {
  const d = SETTING_DATA[id];
  if (!d) return [];
  const runs: { c: string; w: number; pts: P3[] }[] = [];
  for (const s of d.streets) {
    let run: P3[] = [];
    for (let k = 0; k + 5 < s.p.length; k += 3) {
      const a = { x: s.p[k], y: s.p[k + 1], z: s.p[k + 2] }, b = { x: s.p[k + 3], y: s.p[k + 4], z: s.p[k + 5] };
      if (keep((a.x + b.x) / 2, (a.z + b.z) / 2, s.c)) { if (!run.length) run.push(a); run.push(b); continue; }
      if (run.length >= 2) runs.push({ c: s.c, w: s.w, pts: run });
      run = [];
    }
    if (run.length >= 2) runs.push({ c: s.c, w: s.w, pts: run });
  }
  const walk: LandmarkGround[] = [], top: LandmarkGround[] = [];
  for (const s of runs) streetGround(s.c, s.w, s.pts, walk, top);
  return [...walk, ...top];
}

/**
 * One street (ROAD_CLASSES name, right-of-way w) along LOCAL x / y / z points, drawn the city's way: its walk-level
 * polygons go to `walk`, the asphalt, kerbs, dashes and rails to `top` (draw all of `walk` first at junctions).
 * `drape` lays every corner on a surface instead of keeping the street level across its centreline.
 */
export function streetGround(cls: string, w: number, pts: readonly P3[], walk: LandmarkGround[], top: LandmarkGround[], drape?: (x: number, z: number) => number) {
  if (pts.length < 2) return;
  if (cls === 'tram' || cls === 'rail') {
    if (cls === 'rail') walk.push(...ribbon(pts, 2.2, LIFT.walk + 0.004, CITY_PAL.ballast, P.cobble, 0, drape));
    for (const o of [-0.72, 0.72]) {
      top.push(...ribbon(pts, 0.16, LIFT.rail, CITY_PAL.rail, P.none, o, drape));
      top.push(...ribbon(pts, 0.07, LIFT.rail + 0.004, CITY_PAL.railTop, P.none, o, drape));
    }
    return;
  }
  const st = STREET[cls];
  if (!st) return;
  if (!st.asphalt) { walk.push(...ribbon(pts, w, cls === 'service' ? LIFT.asphalt - 0.004 : LIFT.walk + 0.002, st.walk, st.walkPat, 0, drape)); return; }
  const aw = Math.max(1.6, w - CURB_BAND * 2);
  walk.push(...ribbon(pts, aw + CURB_BAND * 2, LIFT.walk, st.walk, st.walkPat, 0, drape));
  top.push(...ribbon(pts, aw, LIFT.asphalt, st.asphalt, P.asphalt, 0, drape));
  for (const sd of [-1, 1]) top.push(...ribbon(pts, 0.12, LIFT.asphalt + 0.002, CITY_PAL.curb, P.none, sd * (aw / 2 - 0.06), drape));
  if (st.dash && aw > 3.2) top.push(...dashes(pts, 0.14, LIFT.dash, CITY_PAL.dash, 1.6, 4, drape));
}

/**
 * A band around a closed LOCAL polygon between the offsets d0 and d1 (u, + = outward, mitred), draped: `y(x, z, d)`
 * gives the height at each band vertex (d = d0 or d1). One quad per edge (a lagoon's coping, its bank).
 */
export function ringBand(poly: readonly Vec2[], d0: number, d1: number, y: (x: number, z: number, d: number) => number, color: string, pattern: number): LandmarkGround[] {
  const n = poly.length;
  let area = 0;
  for (let i = 0; i < n; i++) { const p = poly[i], q = poly[(i + 1) % n]; area += p.x * q.z - q.x * p.z; }
  const sgn = area > 0 ? 1 : -1;
  // outward vertex normals (the mean of the two edge normals, mitred, limited to 2.5 × the offset)
  const nrm = poly.map((p, i) => {
    const a = poly[(i + n - 1) % n], b = poly[(i + 1) % n];
    const e0 = { x: p.x - a.x, z: p.z - a.z }, e1 = { x: b.x - p.x, z: b.z - p.z };
    const l0 = Math.hypot(e0.x, e0.z) || 1, l1 = Math.hypot(e1.x, e1.z) || 1;
    const n0 = { x: (-e0.z / l0) * -sgn, z: (e0.x / l0) * -sgn }, n1 = { x: (-e1.z / l1) * -sgn, z: (e1.x / l1) * -sgn };
    let mx = n0.x + n1.x, mz = n0.z + n1.z;
    const ml = Math.hypot(mx, mz) || 1;
    mx /= ml; mz /= ml;
    const k = Math.min(2.5, 1 / Math.max(0.4, mx * n1.x + mz * n1.z));
    return { x: mx * k, z: mz * k };
  });
  const at = (i: number, d: number) => ({ x: Math.round((poly[i].x + nrm[i].x * d) * 1000) / 1000, z: Math.round((poly[i].z + nrm[i].z * d) * 1000) / 1000 });
  const out: LandmarkGround[] = [];
  for (let i = 0; i < n; i++) {
    const j = (i + 1) % n, q = [at(i, d0), at(j, d0), at(j, d1), at(i, d1)], ds = [d0, d0, d1, d1];
    const ys = q.map((p, k) => +y(p.x, p.z, ds[k]).toFixed(3));
    out.push({ poly: q, y: ys.reduce((a, b) => a + b, 0) / 4, ys, color, pattern });
  }
  return out;
}

const inPoly = (x: number, z: number, poly: readonly Vec2[]) => {
  let c = false;
  for (let i = 0, j = poly.length - 1; i < poly.length; j = i++) {
    const a = poly[i], b = poly[j];
    if ((a.z > z) !== (b.z > z) && x < ((b.x - a.x) * (z - a.z)) / (b.z - a.z) + a.x) c = !c;
  }
  return c;
};

/** A streetStrips `keep` that drops what runs under the landmark's own blockers (its buildings, walls, basins). */
export function clearOf(blockers: readonly WalkBlocker[]): (x: number, z: number) => boolean {
  return (x, z) => !blockers.some(b => ('poly' in b ? inPoly(x, z, b.poly) : Math.hypot(x - b.x, z - b.z) < b.r));
}

/** Points on a grid of `spacing` u inside the polygons (LOCAL), at most `max`, spread over the whole list. */
export function plazaSpots(polys: readonly (readonly Vec2[])[], spacing = 3, max = 12): Vec2[] {
  const inside = (x: number, z: number, poly: readonly Vec2[]) => {
    let c = false;
    for (let i = 0, j = poly.length - 1; i < poly.length; j = i++) {
      const a = poly[i], b = poly[j];
      if ((a.z > z) !== (b.z > z) && x < ((b.x - a.x) * (z - a.z)) / (b.z - a.z) + a.x) c = !c;
    }
    return c;
  };
  const all: Vec2[] = [];
  for (const poly of polys) {
    // at least one row / column however thin the polygon (a sidewalk strip under a gate)
    const xs = poly.map(p => p.x), zs = poly.map(p => p.z), x0 = Math.min(...xs), z0 = Math.min(...zs);
    const wx = Math.max(...xs) - x0, wz = Math.max(...zs) - z0;
    const nx = Math.max(1, Math.floor(wx / spacing)), nz = Math.max(1, Math.floor(wz / spacing));
    for (let j = 0; j < nz; j++) for (let i = 0; i < nx; i++) {
      const x = x0 + (wx * (i + 0.5)) / nx, z = z0 + (wz * (j + 0.5)) / nz;
      if (inside(x, z, poly)) all.push({ x: Math.round(x * 100) / 100, z: Math.round(z * 100) / 100 });
    }
  }
  if (all.length <= max) return all;
  const out: Vec2[] = [];
  for (let k = 0; k < max; k++) out.push(all[Math.floor(((k + 0.5) * all.length) / max)]);
  return out;
}
