import type { SiteTerrainGrid } from './siteTerrain';

/**
 * Baked ground of the wave-4 tier-3 sites (lane L3, W4-L9). GENERATED by scripts/opus-sf/sites3-terrain.mts from the
 * published city (public/opus-bay/sf/v1: the walked ground raster), exactly as siteTerrain.ts is for lane L's sites: do
 * not edit by hand, re-run the script after changing a site's exclusion or terrain box. Per site: `base` = the site's
 * numeric base (world y, the lowest walked ground inside its exclusion) and the ground over it on a LOCAL grid (x0, z0,
 * step, cols × rows, row-major, heights in 1/100 u above the base). tests/opus-bay-sf-sites-w4t3.test.ts re-measures it.
 */
export const SITE_TERRAIN3: Readonly<Record<string, SiteTerrainGrid>> = {
  'balmy-alley': {
    base: 3.26, x0: -3, z0: -12, step: 2, cols: 4, rows: 13,
    h: [
      3, 0, -1, -3,
      12, 4, 4, 2,
      19, 10, 10, 9,
      23, 14, 14, 15,
      23, 19, 19, 19,
      25, 24, 24, 23,
      27, 25, 25, 24,
      27, 25, 25, 22,
      29, 23, 23, 21,
      31, 22, 22, 22,
      30, 21, 21, 23,
      25, 20, 19, 17,
      25, 20, 18, 17,
    ],
  },
  'bayview-opera-house': {
    base: 3.89, x0: -3, z0: -4, step: 2, cols: 7, rows: 7,
    h: [
      9, 43, 65, 73, 83, 100, 135,
      5, 45, 66, 73, 87, 108, 137,
      4, 32, 62, 71, 86, 111, 140,
      23, 28, 61, 68, 83, 111, 138,
      29, 35, 58, 66, 84, 108, 131,
      39, 41, 52, 61, 79, 101, 124,
      45, 47, 54, 59, 78, 98, 113,
    ],
  },
  'crane-cove-park': {
    base: 0, x0: -11, z0: -6, step: 2, cols: 13, rows: 7,
    h: [
      30, 27, 24, 25, 27, 28, 26, 26, 26, 19, 1, 1, 0,
      21, 22, 21, 22, 21, 21, 23, 25, 24, 14, 2, 1, 0,
      19, 18, 16, 15, 16, 19, 20, 19, 16, 11, 3, 1, 0,
      17, 17, 17, 16, 14, 15, 17, 15, 12, 10, 3, 0, 0,
      15, 15, 16, 15, 15, 14, 15, 14, 6, 1, 0, 0, 0,
      12, 12, 12, 12, 12, 10, 9, 7, 5, 1, 0, 0, 0,
      12, 12, 12, 11, 10, 6, 2, 2, 2, 2, 1, 0, 0,
    ],
  },
  'haas-lilienthal-house': {
    base: 15.95, x0: -3, z0: -3, step: 2, cols: 5, rows: 5,
    h: [
      219, 193, 154, 119, 56,
      135, 113, 87, 65, 33,
      93, 72, 56, 35, 12,
      37, 24, 12, 0, -13,
      39, 22, 11, 0, -19,
    ],
  },
  'ingleside-terraces-sundial': {
    base: 13.76, x0: -3, z0: -3, step: 1, cols: 7, rows: 7,
    h: [
      11, 9, 8, 7, 6, 4, 3,
      9, 8, 8, 7, 6, 4, 3,
      8, 8, 8, 8, 6, 4, 2,
      7, 7, 7, 7, 5, 3, 1,
      6, 5, 5, 5, 3, 1, -1,
      5, 4, 4, 3, 1, 0, -1,
      4, 3, 2, 1, 0, -1, -2,
    ],
  },
  'lyon-street-steps': {
    base: 18.41, x0: -2.6, z0: -2.2, step: 1, cols: 6, rows: 15,
    h: [
      456, 461, 460, 460, 457, 455,
      454, 456, 454, 454, 454, 452,
      451, 452, 450, 450, 449, 442,
      435, 426, 422, 422, 419, 418,
      408, 397, 390, 390, 390, 393,
      380, 369, 351, 349, 361, 368,
      346, 330, 308, 308, 325, 339,
      297, 288, 284, 285, 290, 308,
      239, 236, 237, 237, 250, 274,
      178, 172, 184, 187, 199, 233,
      111, 105, 119, 124, 122, 180,
      72, 81, 89, 94, 95, 143,
      31, 47, 48, 54, 62, 111,
      -21, 2, 3, 7, 25, 80,
      -66, -24, -18, -13, -5, 41,
    ],
  },
  'octagon-house': {
    base: 6.16, x0: -2, z0: -2, step: 1, cols: 5, rows: 5,
    h: [
      26, 18, 9, 0, -12,
      31, 22, 13, 5, -10,
      34, 23, 16, 10, -2,
      30, 21, 16, 12, 3,
      27, 21, 16, 12, 4,
    ],
  },
  'seward-street-slides': {
    base: 20.71, x0: -2, z0: -3, step: 1, cols: 5, rows: 12,
    h: [
      -17, -2, 11, 17, 25,
      -7, 10, 30, 47, 67,
      21, 32, 60, 82, 97,
      61, 75, 109, 130, 144,
      94, 119, 140, 149, 156,
      127, 130, 146, 162, 182,
      162, 164, 183, 204, 208,
      198, 199, 213, 235, 244,
      237, 233, 239, 259, 262,
      297, 285, 286, 290, 294,
      323, 322, 322, 316, 306,
      323, 322, 322, 318, 312,
    ],
  },
};
