import type { SiteTerrainGrid } from './siteTerrain';

/**
 * Baked ground of the wave-4 tier-3 sites (lane L3, W4-L9). GENERATED by scripts/opus-sf/sites3-terrain.mts from the
 * published city (public/opus-bay/sf/v1: the walked ground raster), exactly as siteTerrain.ts is for lane L's sites: do
 * not edit by hand, re-run the script after changing a site's exclusion or terrain box. Per site: `base` = the site's
 * numeric base (world y, the lowest walked ground inside its exclusion) and the ground over it on a LOCAL grid (x0, z0,
 * step, cols × rows, row-major, heights in 1/100 u above the base). tests/opus-bay-sf-sites-w4t3.test.ts re-measures it.
 */
export const SITE_TERRAIN3: Readonly<Record<string, SiteTerrainGrid>> = {
  'balmy-alley': {
    base: 3.26, x0: -3, z0: -12, step: 2, cols: 4, rows: 13,
    h: [
      3, 0, -1, -3,
      12, 4, 4, 2,
      19, 10, 10, 9,
      23, 14, 14, 15,
      23, 19, 19, 19,
      25, 24, 24, 23,
      27, 25, 25, 24,
      27, 25, 25, 22,
      29, 23, 23, 21,
      31, 22, 22, 22,
      30, 21, 21, 23,
      25, 20, 19, 17,
      25, 20, 18, 17,
    ],
  },
  'bayview-opera-house': {
    base: 3.89, x0: -3, z0: -4, step: 2, cols: 7, rows: 7,
    h: [
      9, 43, 65, 73, 83, 100, 135,
      5, 45, 66, 73, 87, 108, 137,
      4, 32, 62, 71, 86, 111, 140,
      23, 28, 61, 68, 83, 111, 138,
      29, 35, 58, 66, 84, 108, 131,
      39, 41, 52, 61, 79, 101, 124,
      45, 47, 54, 59, 78, 98, 113,
    ],
  },
};
