import type { SiteTerrainGrid } from './siteTerrain';

/**
 * Baked ground of the wave-4 tier-3 sites (lane L3, W4-L9). GENERATED by scripts/opus-sf/sites3-terrain.mts from the
 * published city (public/opus-bay/sf/v1: the walked ground raster), exactly as siteTerrain.ts is for lane L's sites: do
 * not edit by hand, re-run the script after changing a site's exclusion or terrain box. Per site: `base` = the site's
 * numeric base (world y, the lowest walked ground inside its exclusion) and the ground over it on a LOCAL grid (x0, z0,
 * step, cols × rows, row-major, heights in 1/100 u above the base). tests/opus-bay-sf-sites-w4t3.test.ts re-measures it.
 */
export const SITE_TERRAIN3: Readonly<Record<string, SiteTerrainGrid>> = {
  'balmy-alley': {
    base: 3.26, x0: -3, z0: -12, step: 2, cols: 4, rows: 13,
    h: [
      3, 0, -1, -3,
      12, 4, 4, 2,
      19, 10, 10, 9,
      23, 14, 14, 15,
      23, 19, 19, 19,
      25, 24, 24, 23,
      27, 25, 25, 24,
      27, 25, 25, 22,
      29, 23, 23, 21,
      31, 22, 22, 22,
      30, 21, 21, 23,
      25, 20, 19, 17,
      25, 20, 18, 17,
    ],
  },
  'bayview-opera-house': {
    base: 3.89, x0: -3, z0: -4, step: 2, cols: 7, rows: 7,
    h: [
      9, 43, 65, 73, 83, 100, 135,
      5, 45, 66, 73, 87, 108, 137,
      4, 32, 62, 71, 86, 111, 140,
      23, 28, 61, 68, 83, 111, 138,
      29, 35, 58, 66, 84, 108, 131,
      39, 41, 52, 61, 79, 101, 124,
      45, 47, 54, 59, 78, 98, 113,
    ],
  },
  'crane-cove-park': {
    base: 0, x0: -11, z0: -6, step: 2, cols: 13, rows: 7,
    h: [
      30, 27, 24, 25, 27, 28, 26, 26, 26, 19, 1, 1, 0,
      21, 22, 21, 22, 21, 21, 23, 25, 24, 14, 2, 1, 0,
      19, 18, 16, 15, 16, 19, 20, 19, 16, 11, 3, 1, 0,
      17, 17, 17, 16, 14, 15, 17, 15, 12, 10, 3, 0, 0,
      15, 15, 16, 15, 15, 14, 15, 14, 6, 1, 0, 0, 0,
      12, 12, 12, 12, 12, 10, 9, 7, 5, 1, 0, 0, 0,
      12, 12, 12, 11, 10, 6, 2, 2, 2, 2, 1, 0, 0,
    ],
  },
  'haas-lilienthal-house': {
    base: 15.95, x0: -3, z0: -3, step: 2, cols: 5, rows: 5,
    h: [
      219, 193, 154, 119, 56,
      135, 113, 87, 65, 33,
      93, 72, 56, 35, 12,
      37, 24, 12, 0, -13,
      39, 22, 11, 0, -19,
    ],
  },
  'ingleside-terraces-sundial': {
    base: 13.76, x0: -3, z0: -3, step: 1, cols: 7, rows: 7,
    h: [
      11, 9, 8, 7, 6, 4, 3,
      9, 8, 8, 7, 6, 4, 3,
      8, 8, 8, 8, 6, 4, 2,
      7, 7, 7, 7, 5, 3, 1,
      6, 5, 5, 5, 3, 1, -1,
      5, 4, 4, 3, 1, 0, -1,
      4, 3, 2, 1, 0, -1, -2,
    ],
  },
};
