// GENERATED by scripts/opus-sf/assets/landmark-tops.ts from the drawn lod 0 (the shipped AI swaps included): do not
// edit. Re-run it after changing a landmark's model, swap or walk data (tests/opus-bay-sf-landmark-context checks it).

/**
 * Measured tops (LOCAL y above the landmark's base, rounded up to 0.1 u) of each landmark's `walk.blockers` and `tall`
 * parts, in their declaration order (lane D2, D2-10). A blocker's own `top` wins over its row here.
 */
export const LANDMARK_TOPS: Record<string, { blockers: readonly number[]; tall: readonly number[] }> = {
  'golden-gate-bridge': { blockers: [42.5, 15.9, 42.5, 15.9, 42.5, 15.9, 42.5, 15.9, 41.2, 41.3, 41.4, 41.2, 41.3, 41.4], tall: [42.5, 42.5, 42.5, 42.5, 19.8, 18.5, 20, 21.6, 23.3, 25, 26.7, 28.6, 30.4, 32.3, 34.2, 36.2, 38.3, 40.4, 42.5, 41, 38.3, 35.7, 33.3, 31.1, 29, 27.1, 25.3, 23.7, 22.3, 21, 19.9, 18.9, 18.1, 17.5, 17, 16.7, 17.5, 16.7, 16.9, 17.5, 18, 18.7, 19.7, 20.8, 22, 23.4, 25, 26.7, 28.6, 30.6, 32.9, 35.2, 37.7, 40.5, 42.5, 40.4, 37.7, 35.1, 32.6, 30.1, 27.8, 25.4, 23.2, 21.1, 19, 19.8] },
  'sutro-tower': { blockers: [49.7, 49.7, 49.7, 49.7], tall: [49.7] },
  'city-hall': { blockers: [6.2, 6.2], tall: [17.7] },
  'de-young-tower': { blockers: [2.9, 11.2], tall: [11.2] },
  'palace-of-fine-arts': { blockers: [9.1, 8.9, 8.9, 8.8, 8.9, 9.3, 9.1, 8.7, 5.2, 5.2, 5.2, 5.2, 5.3, 5.2, 5.2, 5.2, 5.2, 5.3, 4.9, 4.9, 4.9, 4.9, 4.9, 4.9, 4.9, 4.9, 5.2], tall: [11.1] },
  'twin-peaks': { blockers: [3.8, 3.8, 7.2], tall: [] },
  'painted-ladies': { blockers: [8.1, 7.8, 7.6, 7.4, 7.1, 6.8, 5.7], tall: [] },
  'dragon-gate': { blockers: [5.9, 4.4, 5.9, 4.4], tall: [] },
  'conservatory-of-flowers': { blockers: [6, 4.9, 4.7, 0.5, 0.5, 0.5], tall: [] },
  'dutch-windmill': { blockers: [10.3, 10, 10], tall: [10.3] },
  'mission-dolores': { blockers: [6.4, 3.5], tall: [] },
  'grace-cathedral': { blockers: [7.9, 7.9], tall: [13, 9.9, 9.8] },
  'legion-of-honor': { blockers: [5.1, 4.9, 4.2, 4.2, 4, 4, 2], tall: [5.7] },
  'fort-point': { blockers: [8.7, 0.3], tall: [] },
  'castro-theatre': { blockers: [5.9, 4.3], tall: [] },
  'oracle-park': { blockers: [7.5], tall: [12.4, 12.4, 12.4, 12.4] },
  'peace-pagoda': { blockers: [7.9], tall: [] },
  'ghirardelli-square': { blockers: [10.6, 10.8, 9.3, 14.2, 7, 7, 10.8, 6.2, 4.3, 6.2], tall: [14.2] },
  'fishermans-wharf': { blockers: [5.2], tall: [] },
  'sutro-baths': { blockers: [0.7, 1.7, 1.3, 1.4, 3], tall: [] },
  'cliff-house': { blockers: [5.4, 4.9, 0.5, 0.5], tall: [] },
  'cable-car-turntable': { blockers: [2.4, 1, 2.4, 0.8], tall: [] },
  'lombard-crooked-street': { blockers: [7.9, 6.9, 6.1, 5.1, 4.3, 3.3, 2.5, 1.6, 8.3, 8.3], tall: [] },
  'chase-center': { blockers: [9.2], tall: [] },
};
