/**
 * Wave 6 · lane H (W6-H3) · GENERATED by scripts/opus-sf/muertos-place.mts on the published city (sf/v1) — do not edit
 * by hand; re-run the script (it carries the sources). Día de los Muertos in the Mission: the papel picado strings over
 * the procession's first legs (24th St Bryant → Mission, Bryant 22nd → 24th), the marigold pots along 24th St, the
 * altars (Potrero del Sol Park's Festival of Altars, Acción Latina on 24th St) and the procession's gathering point at
 * 22nd & Bryant. n = the reward number (muertos:n).
 */
/** x0, z0, x1, z1 (curb to curb), y (the string's height at the ends) */
export const PICADO: readonly (readonly number[])[] = [[472.8,617.02,469.81,614.53,7.25],[465.77,625.48,462.77,622.98,7.25],[458.73,633.93,455.74,631.44,7.25],[451.73,642.41,448.72,639.93,7.37],[444.73,650.89,441.72,648.41,7.52],[437.71,659.36,434.71,656.88,7.75],[430.69,667.83,427.68,665.34,8.02],[423.66,676.3,420.66,673.81,8.17],[416.63,684.76,413.63,682.27,8.3],[409.61,693.23,406.61,690.74,8.55],[438.5,582.26,436.01,585.26,6.86],[447.72,589.8,445.37,592.91,7.22],[457.25,597.4,454.63,600.29,7.51],[466.28,605.16,463.79,608.16,7.38]];
/** x, z, ground y */
export const MARIGOLDS: readonly (readonly number[])[] = [[462.81,623.01,3.06],[450.85,636.49,3.13],[439.77,650.69,3.34],[437.11,660.17,3.58],[427.13,663.58,3.82],[416.79,678.39,4.05],[405.45,692.37,4.37]];
export const MUERTOS_SPOTS: readonly { n: number; x: number; z: number; y: number; f: number; kind: 'altar' | 'arch'; where: string }[] = [ { "n": 1, "x": 535.82, "z": 610.78, "y": 1.5, "f": -2.88, "kind": "altar", "where": "potrero-del-sol" }, { "n": 2, "x": 540.58, "z": 606.64, "y": 1.04, "f": -2.05, "kind": "altar", "where": "potrero-del-sol" }, { "n": 3, "x": 538.51, "z": 597.95, "y": 1.24, "f": -0.75, "kind": "altar", "where": "potrero-del-sol" }, { "n": 4, "x": 531.68, "z": 596.4, "y": 2.16, "f": 0.3, "kind": "altar", "where": "potrero-del-sol" }, { "n": 5, "x": 526.92, "z": 601.54, "y": 2.11, "f": 1.35, "kind": "altar", "where": "potrero-del-sol" }, { "n": 6, "x": 529.49, "z": 608.23, "y": 1.74, "f": 2.45, "kind": "altar", "where": "potrero-del-sol" }, { "n": 7, "x": 450.49, "z": 630.92, "y": 3.05, "f": 1.25, "kind": "altar", "where": "accion-latina" }, { "n": 8, "x": 437.34, "z": 576.89, "y": 2.72, "f": -0.45, "kind": "arch", "where": "procession-start" } ];
/** 24th & Mission · 24th & Bryant · 22nd & Bryant (the route's corners) */
export const ROUTE_CORNERS = {"mission24":{"x":399.81,"z":701.98},"bryant24":{"x":473.22,"z":613.47},"bryant22":{"x":434.95,"z":581.84}} as const;
