import type { TreatStreetId } from './treatStreets';

/**
 * Wave 6 · lane G (W6-G2) · the decorated doors of trick-or-treat, generated by scripts/opus-sf/halloween-doors.mts on
 * the published city (2026-09-29): each on the street face of a real building of a TREAT_STREETS block (the middle of
 * the wall, 0.02 u out), `f` = the way the door faces (toward (sin f, cos f): the street), `y` = the ground 0.3 u out.
 * The knock spot is KNOCK_OUT (0.9 u) out from the wall, standable, never the roadway (tests/opus-bay-w6-g-doors.test.ts
 * re-checks every door on the published city).
 *
 * APPEND-ONLY: door `n` is paid through `halloween:door:<n>` (and `halloween:night:<n>` on 31 October), so a door never
 * changes its number; a door that has to go stays with `gone: true`. W8-H: a door may MOVE along its own street (same
 * number, its old spot in a comment) when it fails the door-to-street rule (tests/opus-bay-w8-h-doorcheck.ts).
 */
export interface TreatDoor { n: number; street: TreatStreetId; x: number; z: number; y: number; f: number; gone?: true }

export const TREAT_DOORS: readonly TreatDoor[] = [
  // Belvedere Street (17th Street → Parnassus Avenue)
  { n: 1, street: 'belvedere', x: 55.14, z: 860.12, y: 28.68, f: -0.653 },
  { n: 2, street: 'belvedere', x: 47.92, z: 869.97, y: 27.43, f: 2.978 },
  // (W8-H-review: door 3 stood behind a neighbour's house on the 17th St corner — its knock spot reaches Belvedere St only
  // by a 10.8 u walk round that house for 1.5 u straight (tests/opus-bay-w8-h-doorcheck.ts DETOUR_MAX) — gone; every
  // other Belvedere face within 80 u is a door already or within 2.8 u of one)
  { n: 3, street: 'belvedere', x: 49.63, z: 857.6, y: 27.94, f: -0.625, gone: true },
  { n: 4, street: 'belvedere', x: 25.55, z: 854.16, y: 24.3, f: 2.555 },
  { n: 5, street: 'belvedere', x: 21.45, z: 851.19, y: 23.59, f: 2.531 },
  { n: 6, street: 'belvedere', x: 16.91, z: 848.04, y: 23.31, f: 2.559 },
  { n: 7, street: 'belvedere', x: 10.64, z: 843.73, y: 22.46, f: 2.471 },
  // (W7-G7: door 8 was a Clayton Street face at the Parnassus end — 3.3 u from Clayton's centreline, 6.7 from
  // Belvedere's; the W6 run only asked for a face parallel to Belvedere within 7 u — gone)
  { n: 8, street: 'belvedere', x: 8.83, z: 827.46, y: 23.49, f: -0.785, gone: true },
  // (W8-H: door 9's knock spot stood in a courtyard inside the block, walled in by houses: Belvedere St is not reachable
  // from it on foot within 18 u (tests/opus-bay-w8-h-doors.test.ts) — gone; no face within 30 u passes the rule)
  { n: 9, street: 'belvedere', x: 1.18, z: 838.3, y: 22.33, f: 2.53, gone: true },
  // Chenery Street (Elk Street → Diamond Street)
  { n: 10, street: 'chenery', x: 419.46, z: 1051.29, y: 16.54, f: 0.678 },
  { n: 11, street: 'chenery', x: 427.37, z: 1048.99, y: 15.93, f: 0.4 },
  { n: 12, street: 'chenery', x: 443.39, z: 1049.92, y: 13.45, f: -2.643 },
  { n: 13, street: 'chenery', x: 441.95, z: 1039.96, y: 14.8, f: 0.677 },
  { n: 14, street: 'chenery', x: 453.09, z: 1044.02, y: 13, f: -2.703 },
  { n: 15, street: 'chenery', x: 464.42, z: 1038.46, y: 12.18, f: -2.595 },
  { n: 16, street: 'chenery', x: 462.15, z: 1028.94, y: 12.26, f: 0.526 },
  { n: 17, street: 'chenery', x: 480.38, z: 1021.08, y: 12.65, f: -2.542 },
  { n: 18, street: 'chenery', x: 474.38, z: 1009.25, y: 16.14, f: 1.064 },
  { n: 19, street: 'chenery', x: 482.68, z: 982.6, y: 18.04, f: 1.656 },
  // Fair Oaks Street (21st Street → 26th Street)
  // (W8-H-review: door 20 faced a gap between two houses — no roadway within 6 u straight out of it, the place chip says
  // 21st Street — and door 21 stood behind a neighbour's house: a 12.8 u walk round it to Fair Oaks St for 2.4 u straight
  // — both gone; no free Fair Oaks face within 80 u passes)
  { n: 20, street: 'fair-oaks', x: 294.22, z: 707.48, y: 12.83, f: 2.434, gone: true },
  { n: 21, street: 'fair-oaks', x: 354.76, z: 744.92, y: 8.37, f: -0.697, gone: true },
  { n: 22, street: 'fair-oaks', x: 366.44, z: 754.89, y: 9.55, f: -0.693 },
  { n: 23, street: 'fair-oaks', x: 369.81, z: 768.51, y: 10.69, f: 2.581 },
  { n: 24, street: 'fair-oaks', x: 374.62, z: 766.82, y: 10.38, f: -1.118 },
  { n: 25, street: 'fair-oaks', x: 381.24, z: 768.14, y: 9.34, f: -0.638 },
  { n: 26, street: 'fair-oaks', x: 374.32, z: 776.86, y: 12.18, f: 2.447 },
  { n: 27, street: 'fair-oaks', x: 395.8, z: 780.3, y: 7.85, f: -0.718 },
  { n: 28, street: 'fair-oaks', x: 388.76, z: 788.96, y: 9.19, f: 2.654 },
  // Jordan Avenue (Geary Boulevard → California Street)
  { n: 29, street: 'jordan', x: -260.43, z: 721.91, y: 14.86, f: 2.423 },
  { n: 30, street: 'jordan', x: -257.72, z: 718.72, y: 14.86, f: -0.734 },
  { n: 31, street: 'jordan', x: -261.19, z: 715.49, y: 14.75, f: -0.524 },
  { n: 32, street: 'jordan', x: -274.47, z: 710.02, y: 14.21, f: 1.937 },
  { n: 33, street: 'jordan', x: -271.48, z: 706.53, y: 14.21, f: -0.736 },
  { n: 34, street: 'jordan', x: -276.21, z: 702.66, y: 13.95, f: -0.707 },
  { n: 35, street: 'jordan', x: -280.91, z: 695.01, y: 14.14, f: -0.747 },
  // (W8-H: door 36 faced Jordan Ave from behind the front row; its knock spot opens onto a yard that reaches Jordan Ave
  // only round the block — gone; no face within 30 u passes the rule)
  { n: 36, street: 'jordan', x: -281.51, z: 691.74, y: 14.36, f: -0.709, gone: true },
  // Sea Cliff Avenue
  { n: 37, street: 'sea-cliff', x: -576.18, z: 901.44, y: 4.94, f: -2.29 },
  // (W8-H: door 38 stood in a pocket between houses its knock spot could not leave (was x -583.74, z 910.05, f -2.593):
  // moved, same number, to the nearest face that fronts Sea Cliff Ave — scripts/opus-sf/halloween-doors.mts --fix)
  // (W8-H-review: that face is a 25th Avenue corner — 3.0 u from 25th Ave's centreline, 5.7 from Sea Cliff Ave's, facing
  // into the junction, the place chip says 25th Avenue (the W7-G7 door 8 / W8-H door 46 case) — gone; the two other free
  // faces within 80 u face a gap between houses)
  { n: 38, street: 'sea-cliff', x: -580.2, z: 890.6, y: 3.94, f: 1.01, gone: true },
  { n: 39, street: 'sea-cliff', x: -592.9, z: 919.3, y: 5.33, f: -1.687 },
  { n: 40, street: 'sea-cliff', x: -603.13, z: 925.46, y: 5.97, f: 1.052 },
  { n: 41, street: 'sea-cliff', x: -608.77, z: 931.74, y: 6, f: 0.851 },
  { n: 42, street: 'sea-cliff', x: -610.64, z: 934.65, y: 6.18, f: 0.853 },
  { n: 43, street: 'sea-cliff', x: -613.43, z: 934.98, y: 5.92, f: 0.859 },
  { n: 44, street: 'sea-cliff', x: -615.62, z: 937.13, y: 5.93, f: 0.857 },
  { n: 45, street: 'sea-cliff', x: -612.33, z: 943.11, y: 6.45, f: 2.477 },
  // (W8-H: door 46 was a 29th Avenue face — 2.1 u from 29th Ave's centreline, 3.6 from Sea Cliff Ave's, facing 29th —
  // gone; no Sea Cliff Ave face within 30 u passes the rule)
  { n: 46, street: 'sea-cliff', x: -604.45, z: 946.71, y: 7.2, f: -1.396, gone: true },
  // Hearst Avenue (Edna Street → Congo Street)
  // (W8-H-review: doors 47 and 48 stood behind the front row at the Edna St end — a 6.5 u / 11.6 u walk round a
  // neighbour's house to Hearst Ave for 2.2 / 2.4 u straight — gone; no free Hearst face within 80 u passes)
  { n: 47, street: 'hearst', x: 343.44, z: 1231.74, y: 24.32, f: 0.784, gone: true },
  { n: 48, street: 'hearst', x: 346.65, z: 1228.06, y: 24.11, f: 0.813, gone: true },
  { n: 49, street: 'hearst', x: 362.75, z: 1217.27, y: 23.02, f: 1.334 },
  { n: 50, street: 'hearst', x: 391.83, z: 1193.83, y: 20.42, f: -2.386 },
  { n: 51, street: 'hearst', x: 395.04, z: 1192.93, y: 20.14, f: -2.333 },
  { n: 52, street: 'hearst', x: 408, z: 1163.76, y: 16.94, f: 0.785 },
  { n: 53, street: 'hearst', x: 437.33, z: 1146.31, y: 14.78, f: -2.414 },
  { n: 54, street: 'hearst', x: 457.21, z: 1130.79, y: 13.05, f: -2.338 },
];
