// Measured blocker tops and tall-part tops of every San Francisco landmark and wave-4 site (SF_SITES; lane D2, D2-10), written to
// src/opus-bay/world/sf/landmarks/tops.ts. Re-run after changing a landmark's model, AI swap or walk data (the
// landmark-context test fails until you do):
//
//   npx tsx --tsconfig tsconfig.app.json scripts/opus-sf/assets/landmark-tops.ts
//
// The drawn lod 0 (procedural, or the shipped AI swap with its GLBs decoded here: glbNode.ts) is rasterised into a
// top-surface grid; see topsMeasure.ts for the rules.
import fs from 'node:fs';
import path from 'node:path';
import { ASSETS } from '../../../src/opus-bay/data/assets';
import { SF_SITES, usesAi } from '../../../src/opus-bay/world/sf/landmarks/index';
import { type GlbMesh, readGlbMesh } from './glbNode';
import { measureTops } from './topsMeasure';

const ROOT = path.resolve(import.meta.dirname, '../../..');
const OUT = path.join(ROOT, 'src/opus-bay/world/sf/landmarks/tops.ts');

async function main() {
  const rows: string[] = [];
  for (const l of SF_SITES) {
    const models = new Map<string, GlbMesh>();
    if (usesAi(l)) for (const p of l.swap!.parts) if (!models.has(p.model)) models.set(p.model, await readGlbMesh(ASSETS.models[p.model].url, path.join(ROOT, 'public')));
    const t = measureTops(l, models);
    rows.push(`  '${l.id}': { blockers: [${t.blockers.join(', ')}], tall: [${t.tall.join(', ')}] },`);
    console.log(l.id.padEnd(26), 'blockers', t.blockers.length, 'max', Math.max(0, ...t.blockers), 'tall', t.tall.length, 'max', Math.max(0, ...t.tall));
  }
  const src = [
    '// GENERATED by scripts/opus-sf/assets/landmark-tops.ts from the drawn lod 0 (the shipped AI swaps included): do not',
    '// edit. Re-run it after changing a landmark\'s model, swap or walk data (tests/opus-bay-sf-landmark-context checks it).',
    '',
    '/**',
    ' * Measured tops (LOCAL y above the landmark\'s base, rounded up to 0.1 u) of each landmark\'s `walk.blockers` and `tall`',
    ' * parts, in their declaration order (lane D2, D2-10). A blocker\'s own `top` wins over its row here.',
    ' */',
    'export const LANDMARK_TOPS: Record<string, { blockers: readonly number[]; tall: readonly number[] }> = {',
    ...rows,
    '};',
    '',
  ].join('\n');
  fs.writeFileSync(OUT, src);
  console.log('wrote', path.relative(ROOT, OUT));
}

void main();
