/**
 * Lane X (W6-X4): wave 6's BAYBAY lines for the voice — the Halloween lines of lanes G (halloween/lines.ts HALLOWEEN_LINES)
 * and H (halloween/worldLines.ts ALL_WORLD_LINES), and the TTS take list.
 *
 *   npx tsx --tsconfig tsconfig.app.json scripts/opus-sf/voice/w6/lines.ts                      the inventory: every line,
 *        its lane and id, "rec" when data/sf/voiceW6.ts has it, "NEW" when not, and the recorded lines no source says
 *   npx tsx --tsconfig tsconfig.app.json scripts/opus-sf/voice/w6/lines.ts --takes <work>/takes.json [--batch <n>]
 *        the take list of the NEW lines (zh + en, one take each at speech_rate 1.0; post.py asks for retakes)
 *
 * The lanes say these lines as BAYBAY bubbles with exactly these texts (their tables are fixed); the clip id is the lane's
 * own line id (`w6g-*`, `w6-h-*`), so a line keeps its clip while its text stays; a changed word in either language is
 * simply not matched any more (game/voiceW5.ts matches zh + en exactly) until the next batch records it.
 * The runtime side: data/sf/voiceW6.ts (generated by post.py) and game/voiceW5.ts (BAYBAY's bubble → its clip).
 */
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Z]:)/, '$1')), '../../../..');

export interface W6Line { id: string; lane: string; zh: string; en: string; source: string; mood: string }

/** A mood note for the instruction, from the line's id and punctuation. */
export function moodOf(id: string, zh: string): string {
  if (id.includes('muertos')) return 'gentle';
  if (id.startsWith('w6g-street')) return 'secret';
  if (/[？?]$/.test(zh)) return 'ask';
  if (/[！!]$/.test(zh)) return 'excited';
  if (/[。…]$/.test(zh)) return 'calm';
  return 'happy';
}

const load = async <T>(rel: string): Promise<T> => import(new URL(`file:///${path.join(ROOT, rel).replace(/\\/g, '/')}`).href) as Promise<T>;

export async function w6Lines(): Promise<W6Line[]> {
  const out: W6Line[] = [];
  const G = await load<{ HALLOWEEN_LINES: readonly { id: string; zh: string; en: string }[] }>('src/opus-bay/halloween/lines.ts');
  for (const l of G.HALLOWEEN_LINES) out.push({ id: l.id, lane: 'g', zh: l.zh, en: l.en, source: `halloween/lines.ts ${l.id}`, mood: moodOf(l.id, l.zh) });
  const H = await load<{ ALL_WORLD_LINES: readonly { id: string; zh: string; en: string }[] }>('src/opus-bay/halloween/worldLines.ts');
  for (const l of H.ALL_WORLD_LINES) out.push({ id: l.id, lane: 'h', zh: l.zh, en: l.en, source: `halloween/worldLines.ts ${l.id}`, mood: moodOf(l.id, l.zh) });
  const ids = new Set<string>();
  for (const l of out) { if (ids.has(l.id)) throw new Error(`duplicate id ${l.id}`); ids.add(l.id); }
  return out;
}

// --- the take list ----------------------------------------------------------------------------------------------------

export const PIXIE = '0178ef57-ada4-43d9-992b-8d9221045bb4';
export const MAX_INSTRUCTION = 128;
/** BAYBAY in a speech bubble (W5-V7's instruction, verbatim) + a mood note */
export const BUBBLE_INSTRUCTION = 'Cute otter mascot talking to a friend: warm, cheerful, natural, clear, easy chatty pace.';
const MOOD_NOTE: Record<string, string> = {
  excited: 'Bright, playful Halloween fun.',
  happy: 'Happy and warm, relaxed.',
  ask: 'Curious and playful.',
  calm: 'Calm and warm, a little cosy-spooky.',
  secret: 'Sharing a fun local fact.',
  gentle: 'Soft, gentle and respectful.',
};

export interface Take { index: number; clip: string; line: string; lane: string; text: string; language: 'zh' | 'en'; instruction: string; speechRate: number }

export function takesFor(lines: readonly W6Line[], rate = 1.0, start = 0): Take[] {
  const takes: Take[] = [];
  for (const l of lines) {
    for (const language of ['zh', 'en'] as const) {
      const instruction = `${BUBBLE_INSTRUCTION} ${MOOD_NOTE[l.mood] ?? MOOD_NOTE.happy}`;
      if (instruction.length > MAX_INSTRUCTION) throw new Error(`instruction too long for ${l.id}`);
      takes.push({ index: start + takes.length, clip: `${language}-${l.id}`, line: l.id, lane: l.lane, text: l[language], language, instruction, speechRate: rate });
    }
  }
  return takes;
}

/** The recorded line ids (data/sf/voiceW6.ts, generated), read as text so this script runs before the table exists. */
function recorded(): Set<string> {
  const file = path.join(ROOT, 'src/opus-bay/data/sf/voiceW6.ts');
  if (!fs.existsSync(file)) return new Set();
  return new Set([...fs.readFileSync(file, 'utf8').matchAll(/\bid: "([a-z0-9-]+)"/g)].map(m => m[1]));
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === path.resolve(new URL(import.meta.url).pathname.replace(/^\/([A-Z]:)/, '$1'));
if (isMain) {
  const lines = await w6Lines();
  const rec = recorded();
  const arg = (k: string) => { const i = process.argv.indexOf(k); return i > 0 ? process.argv[i + 1] : undefined; };
  const out = arg('--takes');
  if (out) {
    const fresh = lines.filter(l => !rec.has(l.id));
    const start = Number(arg('--start') ?? 0);
    const takes = takesFor(fresh, 1.0, start);
    fs.writeFileSync(out, JSON.stringify({ voice: PIXIE, batch: Number(arg('--batch') ?? 1), live: lines.map(l => l.id), lines: fresh, takes }, null, 1) + '\n');
    console.log(`${fresh.length} new lines, ${takes.length} takes → ${out}`);
  } else {
    for (const l of lines) console.log(`${rec.has(l.id) ? 'rec' : 'NEW'}  ${l.id.padEnd(26)} ${l.zh}  |  ${l.en}  (${l.source})`);
    const live = new Set(lines.map(l => l.id));
    const gone = [...rec].filter(id => !live.has(id));
    console.log(`${lines.length} lines (${lines.filter(l => !rec.has(l.id)).length} new); recorded but no longer said: ${gone.length ? gone.join(' ') : 'none'}`);
  }
}
