import { useCallback, useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, CalendarDays, Flag, MapPin, RefreshCw, Users } from 'lucide-react';
import type { AppContextValue } from '../../app/context';
import { outings, safeOutingUrl, type Outing, type OutingAction, type OutingDraft, type OutingMemberStatus } from '../../lib/outings';
import { OutingForm } from './OutingForm';
import { OutingCover } from './OutingCover';
import { OutingDiscussion, OutingReport } from './OutingDiscussion';
import { OutingTimePoll } from './OutingTimePoll';
import { useOutingCopy, useOutingNow, type OutingTranslate } from './outing-copy';
import { outingError, useOutingSession } from './outing-session';
import { canExportOutingCalendar, downloadOutingCalendar } from '../../lib/outing-calendar';

export const outingEligible = (app: Pick<AppContextValue, 'user'>) => !!app.user && (app.user.isPhoneVerified || app.user.officialVerification?.status === 'approved' || (app.user.isOfficialVerified && (!app.user.officialVerification?.status || app.user.officialVerification.status === 'none')));
export const memberLabel = (status: OutingMemberStatus, t: OutingTranslate, waitlisted = false) => status === 'requested' && waitlisted ? t('候补中，尚未加入','Waitlisted — not yet joined') : ({ requested:t('待发起人确认','Awaiting host'), confirmed:t('已加入','Confirmed'), declined:t('申请未通过','Declined'), left:t('已退出','Left'), removed:t('已移出','Removed') })[status];
export const outingLabel = (outing: Outing, t: OutingTranslate, now: number) => outing.status === 'cancelled' ? t('已取消','Cancelled') : outing.status === 'completed' || outing.endAt <= now ? t('已结束','Ended') : outing.startAt <= now ? t('进行中','In progress') : outing.confirmedCount >= outing.capacity ? t('已满员 · 可候补','Full · waitlist available') : t('招募同行','Open for requests');

export function OutingDetail({ id, app, onBack }: { id: string; app: AppContextValue; onBack: () => void }) {
  const { t, locale } = useOutingCopy(), session = useOutingSession(app.user);
  const [outing, setOuting] = useState<Outing | null>(null), [loading, setLoading] = useState(true), [error, setError] = useState(''), [notice, setNotice] = useState('');
  const [edit, setEdit] = useState(false), [report, setReport] = useState(false), [busy, setBusy] = useState(false), [note, setNote] = useState(''), [adult, setAdult] = useState(false);
  const [waitlistConsent,setWaitlistConsent] = useState(false), [acknowledgedVersion,setAcknowledgedVersion] = useState<number | null>(null);
  const [confirm, setConfirm] = useState<{ action: OutingAction; userId?: string } | null>(null);
  const now = useOutingNow(), serial = useRef(0), lock = useRef(false);
  const load = useCallback(async () => {
    const version = ++serial.current, controller = session.controller(); setLoading(true);
    try {
      const response = await outings.get(id, controller.signal);
      if (response.outing.me && response.outing.me.userId !== app.user?.id) throw new Error('Unexpected outing account');
      if (session.current() && !controller.signal.aborted && version === serial.current) { setOuting(response.outing); setError(''); return true; }
    } catch (reason) { if (session.current() && !controller.signal.aborted && version === serial.current) setError(outingError(reason, t, true)); }
    finally { session.release(controller); if (session.current() && version === serial.current) setLoading(false); }
    return false;
  }, [id, app.user, session, t]);
  useEffect(() => { void load(); }, [load]);
  const action = async (kind: OutingAction, userId?: string) => {
    if (!outing || lock.current || !session.current()) return;
    const full = outing.confirmedCount >= outing.capacity, currentConsent = acknowledgedVersion === outing.planVersion;
    if ((kind === 'request' && !(currentConsent && (full ? waitlistConsent : adult))) || (kind === 'reconfirm' && !(currentConsent && adult))) return;
    const options = { ...(userId ? { userId } : {}), ...(kind === 'request' ? { note: note.trim(), adultConsent: currentConsent && (full ? waitlistConsent : adult), ...(full && waitlistConsent ? { waitlist:true } : {}) } : {}), ...(kind === 'reconfirm' ? { adultConsent: currentConsent && adult } : {}) };
    const payload = { mode:'action', id: outing.id, action:kind, ...options }, key = session.key(payload), controller = session.controller();
    lock.current = true; ++serial.current; setBusy(true); setError(''); setNotice('');
    try {
      const response = await outings.action(outing, kind, options, key, controller.signal);
      if (!session.current()) return;
      if (response.outing.me && response.outing.me.userId !== app.user?.id) throw new Error('Unexpected outing account');
      setOuting(response.outing); setConfirm(null); setAdult(false); setWaitlistConsent(false); setAcknowledgedVersion(null); session.clearKey(payload);
      setNotice(response.notificationWarning ? t('记录已更新，但通知暂未确认发送。请以本页状态为准，并提醒成员刷新。','The record was updated, but notifications could not be confirmed. Use this page’s status and ask members to refresh.') : t('记录已更新，请查看下面的最新状态。','The record was updated. Check the latest status below.'));
    } catch (reason) { if (session.current()) setError(outingError(reason, t)); }
    finally { session.release(controller); if (session.current()) { lock.current = false; setBusy(false); setLoading(false); } }
  };
  const login = () => app.setShowLogin(true);
  const exportCalendar = async () => {
    if (!outing || !app.user || lock.current || loading || !session.current() || !canExportOutingCalendar(outing, app.user.id, Date.now())) return;
    const previous = outing, controller = session.controller(), version = ++serial.current;
    lock.current = true; setBusy(true); setError(''); setNotice('');
    try {
      const latest = (await outings.get(previous.id, controller.signal)).outing;
      if (!session.current() || controller.signal.aborted || version !== serial.current) return;
      if (latest.me && latest.me.userId !== app.user.id) throw new Error('Unexpected outing account');
      setOuting(latest);
      if (latest.planVersion !== previous.planVersion || latest.startAt !== previous.startAt || latest.endAt !== previous.endAt || !canExportOutingCalendar(latest, app.user.id, Date.now())) {
        setNotice(t('小队安排或你的参加状态已变化。请先核对最新内容，确认后再存入日历。','The plan or your membership has changed. Review the latest details before saving a calendar file.'));
        return;
      }
      downloadOutingCalendar(latest, app.user.id, Date.now(), locale);
      setNotice(t('已生成日历文件。文件不会自动同步后续变更，出发前请回小队核对最新安排。','Calendar file created. It will not sync later changes automatically; check the outing again before leaving.'));
    } catch (reason) { if (session.current() && !controller.signal.aborted && version === serial.current) setError(outingError(reason, t, true)); }
    finally { session.release(controller); if (session.current()) { lock.current = false; setBusy(false); } }
  };
  const draftOf = (row: Outing): OutingDraft => ({ title:row.title,description:row.description,eventId:row.eventId,date:row.date,startTime:row.startTime,endTime:row.endTime,city:row.city,venue:row.venue,capacity:row.capacity,costNote:row.costNote,transport:row.transport,language:row.language,...(row.cover ? { cover:row.cover } : {}) });
  if (!outing) return <><button className="outing-link-button" onClick={onBack}><ArrowLeft size={16}/>{t('返回小队','Back to outings')}</button>{loading && <p role="status" className="outing-read-status">{t('正在读取小队…','Loading outing…')}</p>}{error && <div className="outing-error" role="alert"><p>{error}</p><button className="outing-secondary" onClick={() => void load()}>{t('重新读取','Try again')}</button></div>}</>;
  const host = outing.host.id === app.user?.id, member = outing.me, canChange = outing.status === 'open' && outing.endAt > now;
  const needsReconfirm = member?.status === 'confirmed' && member.confirmedVersion < outing.planVersion;
  const canJoinEdit = canChange && outing.startAt > now;
  const full = outing.confirmedCount >= outing.capacity, available = Math.max(0,outing.capacity - outing.confirmedCount);
  const consentIsCurrent = acknowledgedVersion === outing.planVersion;
  const requestable = canJoinEdit && !['requested','confirmed','removed','declined'].includes(member?.status || '');
  // Hosts retain membership controls after blocking; ordinary members still hide blocked people.
  const people = (host || member?.status === 'confirmed') ? (outing.members || []).filter(person => host || (person.status === 'confirmed' && !app.blockedUserIds.includes(person.userId))) : [];
  if (edit) return <OutingForm key={outing.id} initial={draftOf(outing)} outing={outing} session={session} onCancel={() => setEdit(false)} onRefresh={() => void load()} onSaved={result => { setOuting(result.outing); setEdit(false); setNotice(result.notificationWarning ? t('安排已保存，但通知暂未确认发送。请提醒成员查看最新安排。','The plan was saved, but notifications could not be confirmed. Ask members to review it.') : result.outing.planVersion > outing.planVersion ? t('安排已保存。涉及关键变更的成员需重新确认。','The plan was saved. Members affected by key changes need to reconfirm.') : t('小队已更新，成员无需重新确认。','Outing updated. Members do not need to reconfirm.')); }} />;
  return <><div className="outing-toolbar"><button className="outing-link-button" onClick={onBack}><ArrowLeft size={16}/>{t('返回小队','Back to outings')}</button><button className="outing-secondary" disabled={busy || loading} onClick={() => void load()}><RefreshCw size={15}/>{t('刷新小队','Refresh outing')}</button></div>
    {error && <div className="outing-error" role="alert">{error}</div>}{notice && <p className="outing-notice" role="status">{notice}</p>}
    <div className="outing-detail-grid"><article className="outing-surface outing-detail-head"><OutingCover outing={outing} variant="detail" /><span className="outing-badge">{outingLabel(outing,t,now)}</span><h1>{outing.title}</h1><p className="outing-detail-description">{outing.description}</p>
      <dl className="outing-facts"><div><dt><CalendarDays size={15}/> {t('集合与结束','Meet and finish')}</dt><dd>{outing.date}<br/>{outing.startTime}–{outing.endTime}</dd><span className="outing-footnote">{t('湾区当地时间','Bay Area local time')}</span></div><div><dt><MapPin size={15}/> {t('公共集合地点','Public meeting place')}</dt><dd>{outing.city}<br/>{outing.venue}</dd></div><div><dt><Users size={15}/> {t('已确认人数','Confirmed members')}</dt><dd>{outing.confirmedCount} / {outing.capacity}</dd><span className="outing-footnote">{t('包含发起人，申请不占名额','Includes host; requests do not reserve a place')}</span></div><div><dt>{t('出行与语言','Transport and language')}</dt><dd>{outing.transport === 'own' ? t('各自到场','Arrive independently') : outing.transport === 'transit' ? t('公共交通同行','Public transit together') : t('步行同行','Walk together')}<br/>{outing.language === 'any' ? t('语言不限','Any language') : outing.language === 'zh' ? t('中文','Chinese') : t('英文','English')}</dd></div></dl>
      <h2>{t('费用与报名说明','Costs and registration')}</h2><p className="outing-detail-description">{outing.costNote}</p>
      {outing.eventId && <div className="outing-associated"><Link to={`/events/${encodeURIComponent(outing.eventId)}`}>{outing.eventTitle || t('查看关联活动','View linked event')}</Link><p>{t('小队由个人发起，与主办方报名和门票分开。','This is an independently organized team, separate from official registration and tickets.')}</p>{outing.officialUrl && safeOutingUrl(outing.officialUrl) && <a href={outing.officialUrl} target="_blank" rel="noopener noreferrer">{t('去主办方核对报名与购票 ↗','Check registration and tickets with the organizer ↗')}</a>}</div>}
      <div className="outing-inline-actions"><Link className="outing-secondary" to={`/plan?date=${outing.date}${outing.eventId ? `&stops=event:${encodeURIComponent(outing.eventId)}` : ''}`}>{t('安排这天的行程','Plan this day')}</Link><button className="outing-link-button" onClick={() => app.user ? setReport(!report) : login()}><Flag size={15}/>{t('举报小队','Report outing')}</button></div><p className="outing-footnote">{t('行程是你自己的出游草稿，不会替小队确认时间，也不自动更改成员安排。','The itinerary is your own draft. It does not confirm or change the team’s arrangements.')}</p>
      {canExportOutingCalendar(outing, app.user?.id, now) && <div className="outing-associated"><button type="button" className="outing-secondary" disabled={busy || loading} onClick={() => void exportCalendar()}><CalendarDays size={16}/>{t('将集合时间存入日历','Save meeting time to calendar')}</button><p className="outing-footnote">{t('仅导出这次已确认的同行安排。下载的日历文件不会自动同步取消或改期；出发前请回小队核对。','Exports this confirmed outing only. The downloaded file does not sync cancellations or changes; check the outing again before leaving.')}</p></div>}
      {report && <OutingReport outingId={outing.id} session={session} onClose={() => setReport(false)} />}
    </article><aside className="outing-surface"><p className="outing-eyebrow">{t('个人发起 · 非主办方','Independent host · not the organizer')}</p><button className="outing-person" onClick={() => app.openUserProfile(outing.host.id)}><Users size={18}/>{outing.host.nickname}</button><p className="outing-footnote">{outing.host.verified ? t('已通过手机或平台资料验证；这不保证身份、资质或线下安全。','Phone or platform profile verification does not guarantee identity, qualifications or in-person safety.') : t('自行核对发起人的资料与安排。','Review the host’s profile and plan yourself.')}</p>
      {!host && <button className="outing-link-button" onClick={() => app.user ? app.handleToggleBlockUser(outing.host.id) : login()}>{app.blockedUserIds.includes(outing.host.id) ? t('取消屏蔽发起人','Unblock host') : t('屏蔽发起人','Block host')}</button>}
      {member && <p className="outing-notice">{host ? t('你是发起人','You are the host') : memberLabel(member.status,t,member.waitlisted)}</p>}
      {needsReconfirm && canJoinEdit && <div className="outing-notice"><strong>{t('安排有变化，请重新确认','The plan changed — please reconfirm')}</strong><p>{t('请重新核对日期、时间、地点、费用和人数。','Review the date, times, place, costs and capacity again.')}</p><label className="outing-check"><input type="checkbox" checked={adult && consentIsCurrent} onChange={event => { setAdult(event.target.checked); setAcknowledgedVersion(outing.planVersion); }} />{t('我已年满18岁，已重新核对并接受当前安排。','I am 18 or older and have reviewed and accept the current plan.')}</label><button className="outing-primary" disabled={busy || loading || !adult || !consentIsCurrent} onClick={() => void action('reconfirm')}>{t('确认新的安排','Confirm the new plan')}</button></div>}
      {host && canChange && <div className="outing-inline-actions"><button className="outing-secondary" disabled={busy || loading || !canJoinEdit} onClick={() => setEdit(true)}>{t('编辑安排','Edit plan')}</button><button className="outing-link-button outing-danger" disabled={busy || loading} onClick={() => setConfirm({action:'cancel'})}>{t('取消小队','Cancel outing')}</button></div>}
      {host && canJoinEdit && available > 0 && (outing.waitlistReviewNeeded || (outing.waitlistCount || 0) > 0) && <div className="outing-notice outing-waitlist-review"><strong>{t('有候补申请待审核','Waitlist requests need your review')}</strong><p>{t(`目前还可接受 ${available} 人。请查看下方候补申请，再决定是否接受；系统不会自动补位。`,`${available} ${available === 1 ? 'place is' : 'places are'} open. Review the waitlist below and choose whom to accept. No one is added automatically.`)}</p><a className="outing-link-button" href="#outing-members">{t('查看候补申请','Review waitlist requests')}</a></div>}
      {!app.user && <div className="outing-notice"><p>{t('登录后可以申请同行；仅浏览不会公开你的资料。','Sign in to request a place. Browsing does not publish your profile.')}</p><button className="outing-primary" onClick={login}>{t('登录后继续','Sign in to continue')}</button></div>}
      {app.user && !host && requestable && (!outingEligible(app) ? <div className="outing-notice"><p>{t('申请前请先验证手机号或完成平台资料核验。','Verify your phone or complete platform profile review before applying.')}</p><Link className="outing-secondary" to="/me">{t('前往个人页验证','Go to profile to verify')}</Link></div> : <form className="outing-join-form" onSubmit={event => { event.preventDefault(); void action('request'); }}>
        {full ? <div className="outing-notice"><strong>{t('现在已满员，可以申请候补','Currently full — you can request the waitlist')}</strong><p>{t('候补不占名额、不保证顺序，也不会自动加入。有空位后仍由发起人审核确认；确认前不能查看成员讨论。','The waitlist does not reserve a place or guarantee an order. Joining is never automatic: the host must approve when a place opens. Team discussion stays private until then.')}</p></div> : <p className="outing-availability">{t(`还可接受 ${available} 人，发起人确认后加入`,`${available} ${available === 1 ? 'place' : 'places'} open; host approval required`)}</p>}
        <label>{t('给发起人的说明（可选）','Note for the host (optional)')}<textarea maxLength={500} value={note} onChange={e => setNote(e.target.value)} /></label>
        {full ? <label className="outing-check"><input type="checkbox" checked={waitlistConsent && consentIsCurrent} onChange={event => { setWaitlistConsent(event.target.checked); setAcknowledgedVersion(outing.planVersion); }}/>{t('我已年满18岁，已阅读安排，同意申请候补；候补不占名额，需发起人确认后才能加入，且不包含门票。','I am 18 or older, have read the plan and agree to request the waitlist. This reserves no place; the host must confirm before I join, and tickets are separate.')}</label> : <label className="outing-check"><input type="checkbox" checked={adult && consentIsCurrent} onChange={event => { setAdult(event.target.checked); setAcknowledgedVersion(outing.planVersion); }}/>{t('我已年满18岁，已阅读安排，了解申请需发起人确认，且不包含门票。','I am 18 or older, have read the plan and understand that the host must approve my request and tickets are separate.')}</label>}
        <button className="outing-primary" disabled={busy || loading || !consentIsCurrent || !(full ? waitlistConsent : adult)} type="submit">{busy ? t('正在提交…','Submitting…') : full ? t('申请候补','Request waitlist') : t('申请加入','Request to join')}</button>
      </form>)}
      {!host && member?.status === 'requested' && <><p className="outing-footnote">{member.waitlisted ? t('你还未加入小队。出现空位后仍需发起人审核，不会自动加入；你可以随时退出候补。','You have not joined. When a place opens the host still needs to approve you; joining is not automatic. You can leave the waitlist at any time.') : t('发起人确认后才算加入。可先保存活动，等待时不需要付款。','You have a place only after the host confirms. No payment is needed while waiting.')}</p><button className="outing-secondary" disabled={busy || loading} onClick={() => setConfirm({action:'withdraw'})}>{member.waitlisted ? t('退出候补','Leave waitlist') : t('撤回申请','Withdraw request')}</button></>}
      {!host && member?.status === 'confirmed' && <button className="outing-link-button outing-danger" disabled={busy || loading} onClick={() => setConfirm({action:'withdraw'})}>{t('退出小队','Leave outing')}</button>}
      {confirm && <div className="outing-notice"><p>{confirm.action === 'cancel' ? t('取消后成员不能继续加入或发消息，已有讨论保留。确定取消这次同行？','Cancelling closes joining and new messages. Existing discussion stays available. Cancel this outing?') : confirm.action === 'remove' ? t('移除后对方无法查看成员讨论。请先在站内说明原因。','Removing this member ends their discussion access. Explain the reason through the site first.') : confirm.action === 'decline' ? t('婉拒这位用户的申请？','Decline this request?') : t('退出或撤回后，发起人会看到更新；活动门票需自行向主办方处理。','The host will see your withdrawal. Handle any event tickets with the organizer separately.')}</p><div className="outing-inline-actions"><button className="outing-secondary outing-danger" disabled={busy || loading} onClick={() => void action(confirm.action,confirm.userId)}>{t('确认操作','Confirm action')}</button><button className="outing-link-button" disabled={busy} onClick={() => setConfirm(null)}>{t('保留当前状态','Keep current state')}</button></div></div>}
      {people.length > 0 && <><h2 className="outing-toolbar">{t('成员与申请','Members and requests')}</h2><ul className="outing-members" id="outing-members">{people.map(person => <li key={person.userId}><div className="outing-person-row"><button className="outing-person" onClick={() => app.openUserProfile(person.userId)}>{person.nickname}</button><span className="outing-footnote">{person.role === 'host' ? t('发起人','Host') : memberLabel(person.status,t,person.waitlisted)}</span></div>{person.status === 'confirmed' && person.confirmedVersion < outing.planVersion && <p className="outing-footnote">{t('待重新确认安排','Awaiting reconfirmation')}</p>}{host && app.blockedUserIds.includes(person.userId) && <p className="outing-footnote"><span className="outing-badge is-muted">{t('已屏蔽','Blocked')}</span> {t('仍可婉拒或移除；接受申请前请先取消屏蔽。','You can still decline or remove this member. Unblock before accepting a request.')}</p>}{host && person.note && <p className="outing-card-summary">{person.note}</p>}<div className="outing-member-actions">{host && canJoinEdit && person.role !== 'host' && person.status === 'requested' && <><button className="outing-secondary" disabled={busy || loading || outing.confirmedCount >= outing.capacity || app.blockedUserIds.includes(person.userId)} onClick={() => void action('accept',person.userId)}>{t('接受','Accept')}</button><button className="outing-link-button" disabled={busy || loading} onClick={() => setConfirm({action:'decline',userId:person.userId})}>{t('婉拒','Decline')}</button></>}{host && canJoinEdit && person.role !== 'host' && person.status === 'confirmed' && <button className="outing-link-button outing-danger" disabled={busy || loading} onClick={() => setConfirm({action:'remove',userId:person.userId})}>{t('移除成员','Remove member')}</button>}{person.userId !== app.user?.id && <button className="outing-link-button" onClick={() => app.handleToggleBlockUser(person.userId)}>{app.blockedUserIds.includes(person.userId) ? t('取消屏蔽','Unblock') : t('屏蔽','Block')}</button>}</div></li>)}</ul></>}
    </aside></div><OutingTimePoll outing={outing} session={session} disabled={busy || loading} onUpdated={result => { ++serial.current; setLoading(false); setOuting(current => current && current.revision > result.outing.revision ? current : result.outing); }} onRefresh={load}/><OutingDiscussion outing={outing} app={app} session={session} refreshOuting={load} />
  </>;
}
