// Lane G (wave 4, W4-G7): bake the lucide-react icon nodes of the flag glyphs into
// src/opus-bay/world/sf/flagGlyphs.ts (the in-world flags draw them into one canvas atlas, 512² since wave 5; lucide-react 0.460 does
// not export the raw nodes, and importing the React components into the world code is not wanted).
//
//   node scripts/opus-sf/flag-glyphs.mjs            write the file
//   node scripts/opus-sf/flag-glyphs.mjs --check    exit 1 when the file differs from what would be written
//
// Deterministic: the glyph list is game/flags.ts FLAG_GLYPHS (kept in sync by tests/opus-bay-sf-flags.test.ts).
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const GLYPHS = ['Landmark', 'Palette', 'Trees', 'PawPrint', 'Mountain', 'Binoculars', 'Waves', 'Sailboat', 'GraduationCap', 'ShoppingBag', 'Trophy', 'Church', 'Theater', 'Castle', 'Signpost', 'MapPin', 'Coins', 'CalendarDays', 'Sparkles', 'Music'];
const kebab = name => name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

const pkg = JSON.parse(readFileSync(join(root, 'node_modules/lucide-react/package.json'), 'utf8'));
const nodes = {};
for (const name of GLYPHS) {
  const src = readFileSync(join(root, 'node_modules/lucide-react/dist/esm/icons', `${kebab(name)}.js`), 'utf8');
  const m = src.match(/createLucideIcon\(\s*"([^"]+)",\s*(\[[\s\S]*\])\s*\);/);
  if (!m) throw new Error(`no icon node in ${name}`);
  // the node array is a plain JS literal (strings, numbers, objects): evaluate it in isolation
  const arr = Function(`"use strict"; return (${m[2]});`)();
  nodes[name] = arr.map(([tag, attrs]) => {
    const a = { ...attrs };
    delete a.key;
    return [tag, a];
  });
}

const body = GLYPHS.map(name => `  ${name}: ${JSON.stringify(nodes[name])},`).join('\n');
const out = `// GENERATED by scripts/opus-sf/flag-glyphs.mjs from lucide-react ${pkg.version} (do not edit by hand).
//
// Lucide icons: ISC License. Copyright (c) for portions of Lucide are held by Cole Bemis 2013-2022 as part of Feather
// (MIT). All other copyright (c) for Lucide are held by Lucide Contributors 2022. Permission to use, copy, modify, and/or
// distribute this software for any purpose with or without fee is hereby granted, provided that the above copyright
// notice and this permission notice appear in all copies. (Full text: node_modules/lucide-react/LICENSE.)

/** One SVG element of a 24 × 24 lucide icon (stroke 2, round caps and joins, no fill). */
export type GlyphNode = [tag: 'path' | 'circle' | 'rect' | 'line' | 'polyline' | 'polygon' | 'ellipse', attrs: Record<string, string | number>];

/** The flag glyphs (game/flags.ts FLAG_GLYPHS order = the atlas cell order). */
export const FLAG_GLYPH_NODES: Readonly<Record<string, readonly GlyphNode[]>> = {
${body}
};
`;
const file = join(root, 'src/opus-bay/world/sf/flagGlyphs.ts');
if (process.argv.includes('--check')) {
  const cur = readFileSync(file, 'utf8');
  if (cur.replace(/\r\n/g, '\n') !== out) { console.error('flagGlyphs.ts is stale: run node scripts/opus-sf/flag-glyphs.mjs'); process.exit(1); }
  console.log('flagGlyphs.ts up to date');
} else {
  writeFileSync(file, out);
  console.log(`wrote ${file} (${GLYPHS.length} glyphs, lucide-react ${pkg.version})`);
}
