/**
 * Wave 5 · lane V · W5-V7: BAYBAY says her recorded wave-5 lines.
 *
 * The lanes say their lines as speech bubbles (game/flow.ts `bubble`, eggs `say`, lane C's pacer…) and none of them has
 * to know about the voice: every new BAYBAY bubble whose text (zh + en, exactly) was recorded
 * (data/sf/voiceW5.ts, generated by scripts/opus-sf/voice/w5/post.py from the lanes' fixed lines) emits
 * `{ type: 'voice-line', id }`, and audio/audio.ts plays `<lang>-<id>` (or the chirp while the clip loads, like every
 * recorded city line). A line whose text changed is simply not matched any more (text only, as before), a clip the owner
 * has not approved yet (W5_VOICE_CHECK) stays text only, and a line a lane voices itself (`own`, e.g. lane R's
 * `realsf-fire-season-end`) is left to that lane. Residents' bubbles are never voiced (Pixie is BAYBAY's voice).
 *
 * City mode only: world/sf/cityWorld.ts starts it from the city chunk (a dynamic import); nothing here is in the
 * main graph.
 */
import { getLocale } from '../../i18n/locale';
import type { Bilingual } from '../core/types';
import { emit } from '../core/events';
import { W5_VOICE_CHECK, W5_VOICE_LINES } from '../data/sf/voiceW5';
import { flow } from './flowStore';
import { BAYBAY_ID } from './interactables';

const textKey = (zh: string, en: string) => `${zh.trim()}\n${en.trim()}`;
let byText: Map<string, string> | null = null;

/** The recorded line for a bubble's text (the lanes' own `voice-line` ids excluded), or null. */
export function w5VoiceFor(text: Bilingual): string | null {
  if (!byText) byText = new Map(W5_VOICE_LINES.filter(l => !l.own).map(l => [textKey(l.zh, l.en), l.id]));
  return byText.get(textKey(text.zh ?? '', text.en ?? '')) ?? null;
}

/** Start voicing BAYBAY's recorded bubbles; returns the off. */
export function initW5Voice(): () => void {
  let last = flow.get().bubble?.key ?? -1;
  return flow.subscribe(() => {
    const b = flow.get().bubble;
    if (!b || b.key === last) return;
    last = b.key;
    if (b.who !== BAYBAY_ID) return;
    const id = w5VoiceFor(b.text);
    if (!id || W5_VOICE_CHECK.includes(`${getLocale() === 'en' ? 'en' : 'zh'}-${id}`)) return;
    emit({ type: 'voice-line', id });
  });
}
