import { useState, type CSSProperties } from 'react';
import { ArrowUpRight, Check, ChevronDown, Map, Stamp } from 'lucide-react';
import { translateText, useLocale } from '../../i18n/locale';
import { BAY_REGIONS, BAY_WORLD_PLACE_IDS, visitedInRegion, type BayJourney, type BayRegionId } from './bay-journey';

const pins:Record<BayRegionId,[number,number]>={sf:[134,75],peninsula:[182,191],'south-bay':[300,298],'east-bay':[350,112]};
export default function BayTravelAtlas({region,onTravel,journey,persistent}: {region:string;onTravel:(region:BayRegionId)=>void;journey:BayJourney;persistent:boolean}) {
  const locale=useLocale();const t=(zh:string,en:string)=>locale==='en'?en:translateText(zh,locale);
  const [open,setOpen]=useState(false);
  const total=Object.keys(journey.visits).length;
  return <section className={`bay-atlas ${open?'is-open':''}`} aria-label={t('全湾区旅行图','Bay Area travel atlas')}>
    <div className="bay-atlas-top"><button className="bay-atlas-toggle" type="button" onClick={()=>setOpen(value=>!value)} aria-expanded={open} aria-controls="bay-atlas-map"><Map size={18}/><span><strong>{t('一张地图，四段小旅行','One bay, four little adventures')}</strong><small>{t('换个地区，带着 BAYBAY 继续探索','Take BAYBAY to another corner of the bay')}</small></span><ChevronDown size={17}/></button><div className="bay-atlas-progress"><Stamp size={17}/><strong>{total}</strong><span>{t('处游戏足迹','virtual visits')}</span></div></div>
    <div className="bay-atlas-regions">{BAY_REGIONS.map(item=>{const count=visitedInRegion(journey,item.id).length;return <button key={item.id} type="button" aria-pressed={region===item.id} onClick={()=>onTravel(item.id)} style={{'--region-color':item.color} as CSSProperties}><span className="bay-atlas-region-symbol" aria-hidden="true">{item.symbol}</span><span><strong>{t(item.zh,item.en)}</strong><small>{count} / {BAY_WORLD_PLACE_IDS[item.id].length} {t('处发现','places')}</small></span>{region===item.id?<Check size={15}/>:<ArrowUpRight size={15}/>}</button>;})}</div>
    {open&&<div className="bay-atlas-detail" id="bay-atlas-map">
      <div className="bay-atlas-map"><svg viewBox="0 0 500 350" aria-label={t('旧金山、半岛、南湾与东湾的位置示意','Schematic positions of San Francisco, Peninsula, South Bay and East Bay')} role="group"><defs><pattern id="bay-water-lines" width="24" height="24" patternUnits="userSpaceOnUse"><path d="M2 12q5-4 10 0t10 0" fill="none" stroke="#93b7b0" strokeWidth="1" opacity=".32"/></pattern></defs><rect width="500" height="350" rx="22" fill="#deebe3"/><rect width="500" height="350" fill="url(#bay-water-lines)"/><path d="M0 0H132l-7 36 34 21 8 44 36 33 11 30 17 21 7 39 27 36 25 19 25 16 12 55H0Z" fill="#e5e4c9" stroke="#bfccac" strokeWidth="2"/><path d="M224 0H500v350H329l-12-40 37-19 20-32-16-41-31-41-10-33-5-31-14-35-19-15-29-20Z" fill="#e5e4c9" stroke="#bfccac" strokeWidth="2"/><path d="M134 75Q152 140 182 191T300 298Q352 230 350 112Q254 48 134 75" stroke="#bc9471" strokeWidth="2.5" strokeDasharray="5 7" fill="none"/><path d="M134 75L350 112" stroke="#fffaf0" strokeWidth="6"/><path d="M134 75L350 112" stroke="#809c8a" strokeWidth="1.5" strokeDasharray="3 5"/><text x="244" y="163" textAnchor="middle" fill="#688e89" fontSize="11" letterSpacing="3">SAN FRANCISCO</text><text x="251" y="182" textAnchor="middle" fill="#688e89" fontSize="12" letterSpacing="5">BAY</text><text x="34" y="205" fill="#8b9f92" fontSize="9" transform="rotate(-78 34 205)">PACIFIC OCEAN</text>{BAY_REGIONS.map(item=>{const [x,y]=pins[item.id];return <g key={item.id} role="button" tabIndex={0} aria-label={t(`前往${item.zh}`,`Travel to ${item.en}`)} onClick={()=>onTravel(item.id)} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();onTravel(item.id);}}}><rect x={x-24} y={y-24} width="48" height="48" rx="24" fill="transparent"/><circle cx={x} cy={y} r={region===item.id?15:11} fill={item.color} stroke="#fffbef" strokeWidth="4"/><text x={x} y={y-23} textAnchor="middle" fontSize="12" fill="#36594d" fontWeight="600">{t(item.zh,item.en)}</text></g>;})}</svg><span>{t('区域与旅行连接示意 · 非导航路线','Regions & game connections · not a navigation route')}</span></div>
      <div className="bay-atlas-itinerary"><span className="bay-atlas-eyebrow">YOUR NEXT LITTLE CHAPTER</span><h3>{t('绕着海湾，慢慢收集好奇心','Follow your curiosity around the bay')}</h3><p>{t('校园、花园、科技馆、海岸和红杉。每次只载入一个地区，车票和探索足迹会跟着你一起旅行。','Campuses, gardens, science, coastlines and redwoods. One region loads at a time; your getaway ticket and virtual visits travel with you.')}</p><ol>{BAY_REGIONS.map(item=><li key={item.id}><span style={{background:item.color}}/><button type="button" onClick={()=>onTravel(item.id)}><strong>{t(item.zh,item.en)}</strong><small>{t(item.tagZh,item.tagEn)}</small><ArrowUpRight size={15}/></button></li>)}</ol><small>{persistent?t('游戏足迹保存在此浏览器，不代表现实到访。','Virtual visits stay in this browser and do not record real attendance.'):t('浏览器储存不可用，探索记录只保留在当前会话。','Browser storage is unavailable; discoveries last for this session.')}</small></div>
    </div>}
  </section>;
}
