import type { SfExplorationStop } from './sf-exploration';
const text = (zh: string, en: string) => ({zh,en});
const option = (id:string, zh:string,en:string,memoryZh:string,memoryEn:string) => ({id,label:text(zh,en),memory:text(memoryZh,memoryEn)});

export const SF_EXTRA_DISCOVERIES: readonly SfExplorationStop[] = [
  {id:'exploratorium',name:text('Exploratorium 探索馆','Exploratorium'),stamp:text('一束好奇心','A beam of curiosity'),symbol:'☀',color:'#bb905e',challenge:'light',prompt:text('码头边有一座迷你光实验台。BAYBAY 想让它亮起来。','A tiny light lab stands beside the pier. Help BAYBAY switch it on.'),choices:[option('beacon','把光装进明信片','Save the light','你把三束光汇在一起，为海湾点亮一盏小灯。','Three beams meet, lighting a tiny beacon for the bay.'),option('question','带走一个新问题','Keep a new question','今天的纪念品是一个问题：光还会带我们发现什么？','Today’s souvenir is a question: what else can light help us discover?')]},
  {id:'sf-state',name:text('旧金山州立大学','San Francisco State'),stamp:text('校园小暗号','A campus code'),symbol:'✦',color:'#9c81aa',challenge:'echo',prompt:text('BAYBAY 在校园笔记本里藏了四个图案。按照线索解开暗号。','BAYBAY hid four symbols in a campus notebook. Follow the clue to reveal the code.'),choices:[option('notebook','留在校园笔记里','Keep a campus note','贝壳、星星、海浪、贝壳：好奇心成了我们的校园暗号。','Shell, star, wave, shell: curiosity becomes our campus code.'),option('friend','送给未来的同学','For a future classmate','BAYBAY 在小纸条上画了招呼：希望下次有新朋友一起探索。','BAYBAY draws a greeting on a little note: bring a new friend next time.')]},
  {id:'city-hall',name:text('旧金山市政厅','San Francisco City Hall'),stamp:text('天际线建筑师','Skyline maker'),symbol:'⌂',color:'#ad9260',challenge:'skyline',prompt:text('三个迷你建筑轮廓散落在广场上，试着拼成一排城市风景。','Three tiny building silhouettes are waiting in the plaza. Arrange a little city view.'),choices:[option('gold','留下一颗金色星星','Leave a golden star','圆顶、高塔与街角，在你的旅行本里有了自己的位置。','Domes, towers and street corners find a place in your travel journal.'),option('draw','画一张建筑速写','Sketch the buildings','BAYBAY 画得不太直，却把整座城市的温柔都画进去了。','BAYBAY’s lines are a little wobbly, but the city’s warmth shines through.')]},
  {id:'ucsf-parnassus',name:text('UCSF Parnassus','UCSF Parnassus'),stamp:text('山坡上的好奇心','Hillside curiosity'),symbol:'❋',color:'#728d96',prompt:text('在迷你校园外，BAYBAY 找到一架写满问题的纸飞机。','Outside the miniature campus, BAYBAY finds a paper plane covered in questions.'),choices:[option('plane','让问题飞远一点','Let a question fly','纸飞机越过树梢。你的下一个问题，也许就是新发现的起点。','A paper plane drifts above the trees. A new question might begin your next discovery.'),option('note','记下今天的发现','Write a discovery','BAYBAY 记下：认真观察一片叶子，也是在练习科学。','BAYBAY notes that observing a leaf carefully is a little practice in science.')]},
  {id:'ucsf-mission-bay',name:text('UCSF Mission Bay','UCSF Mission Bay'),stamp:text('海湾研究手记','Bay curiosity notes'),symbol:'✧',color:'#6c9695',prompt:text('BAYBAY 的迷你研究任务：观察身边的一件小事。','BAYBAY has a tiny research mission: notice one small thing nearby.'),choices:[option('cloud','观察云的形状','Look at cloud shapes','你找到一朵像海獭的云，BAYBAY 把它郑重记进研究手册。','You spot an otter-shaped cloud. BAYBAY carefully records the discovery.'),option('leaf','描一片树叶','Trace a leaf','一片树叶的线条，变成了今天最好看的地图。','The lines of a leaf become today’s most beautiful map.')]},
  {id:'stonestown',name:text('Stonestown Galleria','Stonestown Galleria'),stamp:text('街区寻宝员','Neighborhood finder'),symbol:'◒',color:'#bc906a',prompt:text('BAYBAY 找到了遗落的小贝壳。为它选一个新去处。','BAYBAY found a tiny lost shell. Choose a new place for it.'),choices:[option('pocket','放进旅行口袋','Keep it in the travel pocket','小贝壳安静躺在口袋里，下一站也想跟你一起走。','The tiny shell rests in a pocket, ready for the next stop.'),option('bench','放在迷你长椅旁','Leave it by a tiny bench','你留下一点小惊喜，希望下一位小镇访客也会微笑。','You leave a small surprise for the next visitor to find.')]},
  {id:'salesforce',name:text('Salesforce Tower 与公园','Salesforce Tower & Park'),stamp:text('云端小花园','A garden above the streets'),symbol:'❀',color:'#7e9b6b',prompt:text('BAYBAY 的想象花园长在城市上方，种下一种愿望吧。','BAYBAY’s imaginary garden grows above the city. Plant a little wish.'),choices:[option('seed','种下一颗旅行种子','Plant a travel seed','一颗虚拟种子长出两片叶子，上面写着下一次出发。','A virtual seed sprouts two leaves, each promising another adventure.'),option('shade','给朋友留一片树荫','Save some shade for a friend','城市很热闹，而这片小树荫正好容得下两位慢慢聊天的朋友。','The city is busy, but a little patch of shade leaves room for two friends.')]},
  {id:'transamerica',name:text('泛美金字塔','Transamerica Pyramid'),stamp:text('三角形的城市','A triangular city'),symbol:'△',color:'#a5957b',prompt:text('BAYBAY 在天际线里找到一个大大的三角形。','BAYBAY spots a great big triangle in the skyline.'),choices:[option('triangle','画三个不同的三角形','Sketch three triangles','房顶、纸飞机、远处的尖塔，原来都是城市给出的几何线索。','A roof, a paper plane, a distant spire: the city is full of little geometry clues.'),option('fog','给尖塔披上薄雾','Wrap the spire in fog','一缕想象中的薄雾，把尖塔变成藏在云里的铅笔。','A little imaginary fog turns the tower into a pencil tucked among clouds.')]},
  {id:'oracle-park',name:text('Oracle Park','Oracle Park'),stamp:text('海湾加油声','A cheer by the bay'),symbol:'◉',color:'#c48d67',prompt:text('迷你看台空着两个座位。今天为谁加油？','Two seats await in the miniature stands. Who will you cheer for today?'),choices:[option('baybay','为 BAYBAY 加油','Cheer for BAYBAY','BAYBAY 接住了一颗想象中的棒球，又把它轻轻抛向下一个冒险。','BAYBAY catches an imaginary baseball and gently tosses it toward the next adventure.'),option('friend','为同行的朋友加油','Cheer for your friend','你送出一声加油，整片小海湾都像是在回应。','You give a little cheer, and the miniature bay seems to answer.')]},
];
