import type { Bilingual } from '../../core/types';
import { ROUTE_PATHS } from './routePaths';

/**
 * The three finished walking routes of the city (lane D2, D2-11; plan sf-research-tech.md §7 "Finished routes gate
 * expansion", checkpoint §5.9): each one tied to BAYLINK content that exists (planner places and guides), with a named
 * place at least every 225 u of walking (≈ 30 s of running, gate G5) and a T1 / T2 landmark in view along the way.
 *
 *   R1  Chinatown → North Beach → Coit Tower      the Dragon Gate, Waverly Place, Portsmouth Square, Washington Square
 *   R2  Marina Green → the Golden Gate            the Palace, Crissy Field, Fort Point, the bridge's south tower
 *   R3  Golden Gate Park → Ocean Beach            the Conservatory, the de Young, Blue Heron Lake, the windmill
 *
 * DATA ONLY (no landmark library: GameRoot may import it). A stop's (x, z) is a walkable world spot on the route: a
 * landmark stop is its arrival (world/sf/landmarks/context.ts sfLandmarkAnchor, written out; the sf-routes test checks
 * them) — except Fort Point, whose arrival slot beside the bridge deck is boxed in (W5-L, the mid-wave checkpoint's
 * CP-8: its stop stands on Marine Drive's end loop in front of the fort, 7.9 u away, where every way is open) —, a place
 * stop its places.json point (or, for a big place such as the Polo Field, the walk's spot beside it, ≤ 20 u away; the
 * Tea Garden's is its gate, not the pond's middle), an attraction-only stop the attraction's arrival. Every stop passes
 * the walk sweep's judge (tests/opus-bay-w5-landmarks.test.ts). `placeId` = its places.json row
 * (lane G1's map, discovery, fast travel); `attraction` = its row in lane P's data/sf/attractions.ts when places.json has
 * none yet (the wave-4 extra places). Consumers: G1 (discovery / map lines), G2 (stop slots, lines), F (crowd).
 *
 * The walk itself (ROUTE_PATHS, generated by scripts/opus-sf/assets/routes-build.ts on the published walk graph) is the
 * A* route from stop to stop, simplified to 1 u; `stopAt` is each stop's arc position along it. Re-run the script after
 * changing a stop (the sf-routes test fails until you do). scripts/opus-sf/routes-qa.mjs walks the finished routes in the
 * app (D2-14).
 */

export type SfRouteId = 'r1' | 'r2' | 'r3';

export interface SfRouteStop {
  /** stable id within the city (`<route>-<slug>`) */
  id: string;
  name: Bilingual;
  /** landmark: a T1 / T2 landmark stop; place: a named place; filler: a smaller named place that keeps the gaps short */
  kind: 'landmark' | 'place' | 'filler';
  /** SF landmark registry id (world/sf/landmarks) for landmark stops, or the landmark a place stop belongs to */
  landmark?: string;
  /** places.json row (public/opus-bay/sf/v1/places.json) */
  placeId?: string;
  /** lane P's attraction id (data/sf/attractions.ts) */
  attraction?: string;
  /** world spot on the walk */
  x: number;
  z: number;
  /** one line for the stop (where you are, which way the walk goes) */
  line: Bilingual;
  /** unnamed waypoints (world x, z) the walk takes on its way TO this stop (the street the route means, e.g. Grant Ave) */
  via?: readonly (readonly [number, number])[];
}

export interface SfRoute {
  id: SfRouteId;
  name: Bilingual;
  blurb: Bilingual;
  /** BAYLINK: /planner-catalog.json place ids and /baybay-guides.json slugs this route belongs to */
  planner: readonly string[];
  guides: readonly string[];
  /** in walking order */
  stops: readonly SfRouteStop[];
}

const bi = (zh: string, en: string): Bilingual => ({ zh, en });

/** gate G5: a named place at least every this many units of walking */
export const ROUTE_GAP_MAX = 225;

export const SF_ROUTES: readonly SfRoute[] = [
  {
    id: 'r1',
    name: bi('唐人街 → 北滩 → 科伊特塔', 'Chinatown → North Beach → Coit Tower'),
    blurb: bi('从龙门走进唐人街，经过天后庙街和正在整修的花园角，穿过北滩的华盛顿广场，最后爬上电报山到科伊特塔。', 'Through the Dragon Gate into Chinatown, past Waverly Place and Portsmouth Square (closed for its rebuild), across North Beach\'s Washington Square and up Telegraph Hill to Coit Tower.'),
    planner: ['chinatown'],
    guides: ['sf-chinatown-north-beach-walk-guide'],
    stops: [
      { id: 'r1-dragon-gate', kind: 'landmark', landmark: 'dragon-gate', placeId: 'chinatown-dragon-gate', name: bi('唐人街龙门', 'Chinatown Dragon Gate'), x: 86.7, z: 177.11, line: bi('从龙门出发，沿都板街往北走，头顶是一串串红灯笼。', 'Start at the Dragon Gate and walk north up Grant Ave under the red lanterns.') },
      { id: 'r1-tin-how', kind: 'filler', attraction: 'tin-how-temple', name: bi('天后古庙（天后庙街）', 'Tin How Temple (Waverly Place)'), x: 26.6, z: 145.1, line: bi('天后庙街：彩色阳台的小街，天后古庙就在楼上。', 'Waverly Place: the lane of painted balconies, with Tin How Temple upstairs.') },
      { id: 'r1-portsmouth', kind: 'place', placeId: 'osm-r14547583', attraction: 'portsmouth-square', name: bi('花园角', 'Portsmouth Square'), x: 37.73, z: 128.11, line: bi('花园角是唐人街的客厅，2026 年 6 月起封闭整修，预计 2028 年重开，这回隔着围栏看看。', 'Portsmouth Square, Chinatown\'s living room, is fenced off for its rebuild from June 2026 until about 2028: a look through the fence this time.') },
      { id: 'r1-washington-sq', kind: 'place', placeId: 'north-beach-washington-sq', name: bi('北滩 · 华盛顿广场', 'North Beach · Washington Square'), x: -69.19, z: 105.91, via: [[2, 119], [-9.8, 110.7], [-34.1, 93.8], [-45.3, 86.0]], line: bi('到北滩了：华盛顿广场的草坪，对面是白色双塔教堂。', 'North Beach: the lawn of Washington Square, the white twin-spired church across it.') },
      { id: 'r1-peter-paul', kind: 'filler', attraction: 'saints-peter-and-paul-church', name: bi('圣彼得圣保罗教堂', 'Saints Peter and Paul Church'), x: -76.1, z: 100.1, line: bi('从教堂门前往东，朝电报山的坡走。', 'From the church steps, head east for the slope of Telegraph Hill.') },
      { id: 'r1-coit', kind: 'landmark', placeId: 'coit-tower', attraction: 'coit-tower', name: bi('科伊特塔', 'Coit Tower'), x: -52.75, z: 53.1, line: bi('电报山顶的科伊特塔：回头看，唐人街和海湾都在脚下。', 'Coit Tower on Telegraph Hill: look back over Chinatown and the Bay.') },
    ],
  },
  {
    id: 'r2',
    name: bi('马里纳区 → 金门大桥', 'Marina Green → the Golden Gate'),
    blurb: bi('沿着海湾往西：码头绿地、艺术宫的湖、克里西场的海滩，经 Fort Point 炮台爬上桥头，走到金门大桥南塔下。', 'West along the Bay: Marina Green, the Palace lagoon, Crissy Field\'s beach, Fort Point, then up to the bridge and out to its south tower.'),
    planner: ['palace', 'presidio', 'golden-gate'],
    guides: ['sf-palace-fine-arts-marina-guide', 'sf-golden-gate-bridge-fort-point-guide', 'presidio-picnic-day-guide'],
    stops: [
      { id: 'r2-marina-green', kind: 'place', placeId: 'marina-green', attraction: 'marina-green', name: bi('码头绿地', 'Marina Green'), x: -382.06, z: 300.71, line: bi('码头绿地：放风筝的大草坪，往西就能看见金门大桥。', 'Marina Green: the kite lawn, with the Golden Gate in view to the west.') },
      { id: 'r2-palace', kind: 'landmark', landmark: 'palace-of-fine-arts', placeId: 'palace-of-fine-arts', name: bi('艺术宫', 'Palace of Fine Arts'), x: -409.64, z: 409.63, line: bi('艺术宫：绕着湖边走，天鹅在圆顶下游。', 'The Palace of Fine Arts: walk round the lagoon, swans under the rotunda.') },
      { id: 'r2-east-beach', kind: 'filler', placeId: 'osm-w69342329', name: bi('克里西场东滩', 'Crissy Field East Beach'), x: -482.45, z: 414.18, line: bi('东滩：沙滩从这里开始，沿水边一路往西。', 'East Beach: the sand starts here; follow the water west.') },
      { id: 'r2-crissy', kind: 'place', placeId: 'crissy-field', attraction: 'crissy-field', name: bi('克里西场', 'Crissy Field'), x: -576.15, z: 546.38, line: bi('克里西场：以前的机场跑道，现在是海边的草地和沙滩。', 'Crissy Field: a former airfield, now meadow and beach by the water.') },
      { id: 'r2-coast-guard', kind: 'filler', placeId: 'osm-w934681747', name: bi('海岸警卫队旧站', 'Fort Point Coast Guard Station'), x: -610.94, z: 553.41, line: bi('海岸警卫队旧站：白色木楼，桥越来越近了。', 'The old Coast Guard station: white timber houses, the bridge getting close.') },
      { id: 'r2-fort-point', kind: 'landmark', landmark: 'fort-point', placeId: 'fort-point', name: bi('Fort Point 炮台', 'Fort Point'), x: -743.94, z: 591.88, line: bi('Fort Point 炮台就在大桥的拱下，砖墙上还有炮位。', 'Fort Point sits right under the bridge\'s arch, cannons still on its roof.') },
      { id: 'r2-battery-east', kind: 'filler', placeId: 'osm-n11991078747', name: bi('东炮台', 'Battery East'), x: -679.54, z: 586.43, line: bi('东炮台：沿步道往上，去桥头。', 'Battery East: take the trail up toward the bridge.') },
      { id: 'r2-welcome', kind: 'filler', placeId: 'osm-w164569681', name: bi('大桥游客中心', 'Bridge Welcome Center'), x: -700.36, z: 604.59, line: bi('桥头的游客中心，前面就是大桥的人行道。', 'The bridge\'s welcome center; the walkway starts just ahead.') },
      { id: 'r2-overlook', kind: 'filler', placeId: 'osm-n10682270352', landmark: 'golden-gate-bridge', name: bi('金门大桥观景台', 'Golden Gate Bridge overlook'), x: -681, z: 670, line: bi('桥头观景台：从这里走上桥面。', 'The overlook at the bridge end: step onto the deck from here.') },
      { id: 'r2-south-tower', kind: 'place', placeId: 'ggb-south-tower', landmark: 'golden-gate-bridge', attraction: 'golden-gate-bridge', name: bi('金门大桥 · 南塔', 'Golden Gate Bridge · south tower'), x: -796.12, z: 564.38, line: bi('南塔脚下：抬头看塔，低头看海峡。', 'At the foot of the south tower: the tower above, the strait below.') },
    ],
  },
  {
    id: 'r3',
    name: bi('金门公园 → 海洋海滩', 'Golden Gate Park → Ocean Beach'),
    blurb: bi('从花卉温室穿过整座金门公园：迪扬博物馆、日本茶园、蓝鹭湖、野牛围场和荷兰风车，一直走到太平洋边。', 'Across the whole of Golden Gate Park from the Conservatory: the de Young, the Tea Garden, Blue Heron Lake, the bison and the Dutch Windmill, out to the Pacific.'),
    planner: ['golden-gate-park'],
    guides: ['golden-gate-park-free-car-free-day-guide'],
    stops: [
      { id: 'r3-conservatory', kind: 'landmark', landmark: 'conservatory-of-flowers', placeId: 'conservatory-of-flowers', name: bi('花卉温室', 'Conservatory of Flowers'), x: -177.51, z: 858.11, line: bi('从花卉温室前的花坛出发，往西走进公园。', 'Start at the flower beds before the Conservatory and head west into the park.') },
      { id: 'r3-de-young', kind: 'landmark', landmark: 'de-young-tower', placeId: 'de-young', name: bi('迪扬博物馆 · 观景塔', 'de Young Museum · Hamon Tower'), x: -243.9, z: 928.6, line: bi('迪扬博物馆：扭转的铜塔，对面是音乐广场。', 'The de Young: the twisting copper tower across the Music Concourse.') },
      { id: 'r3-tea-garden', kind: 'filler', placeId: 'japanese-tea-garden', attraction: 'japanese-tea-garden', name: bi('日本茶园', 'Japanese Tea Garden'), x: -236, z: 962, line: bi('日本茶园的门口，再往西就是湖。', 'The Japanese Tea Garden\'s gate; the lake lies further west.') },
      { id: 'r3-lake', kind: 'place', placeId: 'stow-lake', attraction: 'blue-heron-lake', name: bi('蓝鹭湖（原斯托湖）', 'Blue Heron Lake (Stow Lake)'), x: -269.74, z: 1032.25, line: bi('蓝鹭湖：绕着草莓山的湖，可以租船。', 'Blue Heron Lake circles Strawberry Hill; the boathouse is on the shore.') },
      { id: 'r3-meadows', kind: 'filler', placeId: 'golden-gate-park', name: bi('金门公园草地', 'Golden Gate Park meadows'), x: -334.84, z: 1080.6, line: bi('公园的中段：一片片草地和小湖，继续往西。', 'The middle of the park: meadows and small lakes; keep heading west.') },
      { id: 'r3-polo', kind: 'filler', placeId: 'osm-w476267889', name: bi('马球场', 'Polo Field'), x: -427.7, z: 1181.1, line: bi('马球场的看台，野牛就在前面。', 'The Polo Field\'s stands; the bison are just ahead.') },
      { id: 'r3-bison', kind: 'filler', attraction: 'bison-paddock', name: bi('野牛围场', 'Bison Paddock'), x: -464.9, z: 1220, line: bi('野牛围场：公园里养着一小群美洲野牛。', 'The Bison Paddock: the park keeps a small herd of American bison.') },
      { id: 'r3-windmill', kind: 'landmark', landmark: 'dutch-windmill', placeId: 'dutch-windmill', name: bi('荷兰风车', 'Dutch Windmill'), x: -584.3, z: 1315.67, line: bi('荷兰风车和郁金香花园，海风从西边吹来。', 'The Dutch Windmill and its tulip garden, the sea wind from the west.') },
      { id: 'r3-beach-chalet', kind: 'filler', attraction: 'beach-chalet', name: bi('海滩小屋', 'Beach Chalet'), x: -578.6, z: 1330.9, line: bi('海滩小屋就在公园的西头，对面就是大海。', 'The Beach Chalet at the park\'s west end, the ocean across the road.') },
      { id: 'r3-murphy', kind: 'filler', placeId: 'murphy-windmill', attraction: 'murphy-windmill', name: bi('墨菲风车', 'Murphy Windmill'), x: -515.02, z: 1367.36, line: bi('公园南角的墨菲风车，沿海边往南走。', 'The Murphy Windmill in the park\'s south corner; walk south by the sea.') },
      { id: 'r3-ocean-beach', kind: 'place', placeId: 'ocean-beach', attraction: 'ocean-beach', name: bi('海洋海滩', 'Ocean Beach'), x: -430.99, z: 1474.99, line: bi('到太平洋了：海洋海滩的沙滩一眼望不到头。', 'The Pacific: Ocean Beach runs on as far as you can see.') },
    ],
  },
];

export function sfRoute(id: SfRouteId): SfRoute | undefined { return SF_ROUTES.find(r => r.id === id); }

/** A route's generated walk: the polyline (world x, z pairs), its length and each stop's arc position. */
export function routePath(id: SfRouteId): { points: readonly number[]; length: number; stopAt: readonly number[] } | undefined {
  return ROUTE_PATHS[id];
}

/** Walking distance between consecutive stops (u), from the generated walk. */
export function routeGaps(id: SfRouteId): number[] {
  const p = ROUTE_PATHS[id];
  if (!p) return [];
  return p.stopAt.slice(1).map((a, i) => Math.round((a - p.stopAt[i]) * 10) / 10);
}

/** The point and heading (world yaw of the walking direction) at arc position `s` along a route's walk. */
export function routePointAt(id: SfRouteId, s: number): { x: number; z: number; heading: number } | null {
  const p = ROUTE_PATHS[id];
  if (!p || p.points.length < 4) return null;
  const pts = p.points;
  let acc = 0;
  for (let k = 0; k + 3 < pts.length; k += 2) {
    const ax = pts[k], az = pts[k + 1], bx = pts[k + 2], bz = pts[k + 3], L = Math.hypot(bx - ax, bz - az);
    if (acc + L >= s || k + 4 >= pts.length) {
      const t = L > 0 ? Math.min(1, Math.max(0, (s - acc) / L)) : 0;
      return { x: ax + (bx - ax) * t, z: az + (bz - az) * t, heading: Math.atan2(bx - ax, bz - az) };
    }
    acc += L;
  }
  return null;
}
