/**
 * GENERATED by scripts/opus-sf/voice/w7/post.py — do not edit by hand.
 * BAYBAY's recorded wave-7 lines (lane X, W7-X2): the fixed bubble lines no earlier table had (waves 5–7: play/, eggs/,
 * economy/, lanes G / H's Halloween tables, W2's activities — scripts/opus-sf/voice/w7/lines.ts), zh + en, qwen_audio_tts
 * preset "Pixie" (the wave-4…6 voice), trimmed, two-pass loudnorm −18 LUFS / TP −1.5, AAC 64k .m4a + Opus 48k .ogg.
 * game/voiceW5.ts matches BAYBAY's bubbles against this table too (zh + en exactly; an earlier recording of the same
 * words wins). W7_RETAKE_CLIPS: new takes of wave-6 clips the recogniser missed, under the wave-6 clip ids — this module
 * registers them before data/sf/voiceW6.ts does (the binder imports it first), so the retake plays. Measurements, picks
 * and the owner's listening sheet: docs/opus-bay/qa/w7/X/voice/.
 */
import { type VoiceClip, registerVoiceClips } from '../assets';

export interface W7VoiceLine { id: string; lane: string; zh: string; en: string; /** seconds: zh, en */ s: readonly [number, number]; /** the lane plays it (a voice-line event with this id): never matched by text */ own?: 1 }

export const W7_VOICE_LINES: readonly W7VoiceLine[] = [
  { id: "w5-a-760e436e", lane: "a", zh: "我先发球！轮到你时，等影子变金色就点它～", en: "I’ll serve! On your turn, tap the shadow when it turns gold!", s: [3.96, 4.7] },
  { id: "w5-a-e5c9d3d8", lane: "a", zh: "还高着呢，等它落下来～", en: "Still high — let it come down!", s: [2.75, 2.66] },
  { id: "w5-a-6a5edde8", lane: "a", zh: "哎呀，落地啦！", en: "Oops, it landed!", s: [1.29, 1.78] },
  { id: "w5-a-83b85919", lane: "a", zh: "好球！", en: "Nice one!", s: [1.0, 1.01] },
  { id: "w5-a-8be2fa97", lane: "a", zh: "呜呼——飞起来啦！插小旗的就是坡顶！", en: "Woohoo — we flew! The pennants mark the crests!", s: [3.9, 4.41] },
  { id: "w5-a-0ade6a62", lane: "a", zh: "再飞一次！", en: "Up we go again!", s: [1.02, 1.21] },
  { id: "w5-a-d6da08f3", lane: "a", zh: "全城 12 个坡顶都飞过啦！", en: "All 12 crests in the city — hopped!", s: [2.73, 3.35] },
  { id: "w5-a-4a04af8b", lane: "a", zh: "九曲花街的路牌建议每小时 5 英里——慢慢开，别碰到花坛！", en: "Lombard’s sign says 5 mph — nice and slow, mind the flower beds!", s: [4.83, 5.88] },
  { id: "w5-a-baa3f3d8", lane: "a", zh: "佛蒙特街只有 7 个弯，可坡更陡——慢一点！", en: "Vermont has seven bends but a steeper hill — slowly!", s: [4.7, 4.19] },
  { id: "w5-a-4a24dc9b", lane: "a", zh: "九曲花街这一段有 8 个急弯，而且只能往下开哦！", en: "Eight hairpins on this block — and it’s one way, downhill!", s: [4.86, 4.46] },
  { id: "w5-a-c3fe95c7", lane: "a", zh: "有人量过，佛蒙特街其实更弯：弯曲度 1.56 比 1.2！", en: "Someone measured it: Vermont Street is curvier — 1.56 to 1.2!", s: [6.0, 6.48] },
  { id: "w5-a-7f1eaa1c", lane: "a", zh: "佛蒙特街只有 7 个弯，却被量出比九曲花街还弯！", en: "Only seven bends, yet measured curvier than Lombard!", s: [5.22, 4.45] },
  { id: "w5-a-774352f1", lane: "a", zh: "两条都开过啦！论弯，佛蒙特街赢；论花，九曲花街赢～", en: "Both done! Vermont wins on bends, Lombard on flowers!", s: [5.09, 5.08] },
  { id: "w5-a-5d9dcf9c", lane: "a", zh: "哎哟，碰到啦～", en: "Oops — a bump!", s: [2.27, 1.54] },
  { id: "w5-a-f394a25d", lane: "a", zh: "点一下地面，扔到那儿！我去接～", en: "Tap the ground to throw — I’ll fetch!", s: [3.02, 3.33] },
  { id: "w5-a-f87a967e", lane: "a", zh: "接住啦！", en: "Got it!", s: [0.82, 0.5] },
  { id: "w5-a-c225f73e", lane: "a", zh: "飞身接住！", en: "Diving catch!", s: [1.13, 1.25] },
  { id: "w5-a-6807a93e", lane: "a", zh: "差一点！我去捡回来～", en: "So close! I’ll fetch it!", s: [3.38, 2.82] },
  { id: "w5-a-d4a250de", lane: "a", zh: "扔到那边就捡不回来啦，换个地方～", en: "Can’t fetch it from there — pick another spot!", s: [3.72, 3.07] },
  { id: "w5-a-dac00abb", lane: "a", zh: "好好玩！再扔几次也行～", en: "That was fun! Throw some more any time!", s: [2.88, 3.05] },
  { id: "w5-a-60c324fe", lane: "a", zh: "金门大桥金圈！绕着两座桥塔飞～", en: "Golden Gate rings! Round both towers!", s: [4.0, 3.48] },
  { id: "w5-a-471a2270", lane: "a", zh: "桥塔比海面高 227 米，1937 年就通车啦！", en: "The towers stand 227 m over the water — open since 1937!", s: [4.03, 6.63] },
  { id: "w5-a-bf57e7df", lane: "a", zh: "大桥这种橙色，名字叫“国际橙”！", en: "That orange has a name: International Orange!", s: [3.98, 4.57] },
  { id: "w5-a-80ad9d1b", lane: "a", zh: "骑上鹈鹕飞到大桥边，有金圈等你！", en: "Glide out to the bridge — there are rings!", s: [3.67, 3.14] },
  { id: "w5-a-05f0c830", lane: "a", zh: "跟着我喊：嘿——咻！咻的时候推！", en: "Shout with me: heave — ho! Push on the \"ho\"!", s: [3.55, 3.07] },
  { id: "w5-a-b95c4fe2", lane: "a", zh: "咻！正好！", en: "Ho! Spot on!", s: [1.26, 2.28] },
  { id: "w5-a-ebed5c01", lane: "a", zh: "叮当车终点的转盘是人力推的，车就这样掉头！", en: "The cable-car turntables are pushed by hand — that’s how the cars turn!", s: [4.3, 5.08] },
  { id: "w5-a-910cdcd4", lane: "a", zh: "三个转盘都推过啦！盖个章～", en: "All three turntables pushed! A stamp for you!", s: [2.95, 4.34] },
  { id: "w5-a-0b992197", lane: "a", zh: "好烫！就在附近！", en: "Hot! Really close!", s: [2.09, 2.36] },
  { id: "w5-a-22deff78", lane: "a", zh: "暖了！", en: "Warmer!", s: [0.79, 0.75] },
  { id: "w5-a-eed09ded", lane: "a", zh: "冷了…", en: "Colder…", s: [0.66, 0.83] },
  { id: "w5-a-c44fdeb8", lane: "a", zh: "等一下再玩捉迷藏吧～", en: "Let’s play hide and seek in a bit!", s: [2.27, 2.17] },
  { id: "w5-a-5da58c2c", lane: "a", zh: "这里没地方藏～换个地方再玩吧！", en: "Nowhere to hide here. Let’s try somewhere else!", s: [2.46, 3.46] },
  { id: "w5-a-af138c00", lane: "a", zh: "我在这儿呢～下次再来找我！", en: "Here I am! Find me next time!", s: [2.4, 3.27] },
  { id: "w5-a-70995063", lane: "a", zh: "闭上眼睛数三下，我去藏好！", en: "Close your eyes and count to three!", s: [4.11, 2.91] },
  { id: "w5-a-5aa34332", lane: "a", zh: "捉迷藏！你数到三，我去藏好～", en: "Hide and seek! You count to three, I’ll hide!", s: [3.48, 3.33] },
  { id: "w5-a-3122a12b", lane: "a", zh: "想玩捉迷藏吗？点「问 BAYBAY」，再点「捉迷藏」！", en: "Fancy hide and seek? Tap Ask, then Hide & seek!", s: [4.52, 4.56] },
  { id: "w5-a-06e95089", lane: "a", zh: "想玩捉迷藏吗？按 Q 问我，再选「捉迷藏」！", en: "Fancy hide and seek? Press Q to ask me, then Hide & seek!", s: [4.04, 4.67] },
  { id: "w5-a-5c7f6bf0", lane: "a", zh: "一只、两只……一起数数有几只海狮！", en: "One, two… let’s count the sea lions!", s: [5.36, 3.81] },
  { id: "w5-a-b5aa19f9", lane: "a", zh: "全数到啦！一只都没漏！", en: "Every one of them — none missed!", s: [2.85, 2.58] },
  { id: "w5-a-c9a06a9a", lane: "a", zh: "这些海狮 1990 年起就在 K 码头安家啦！", en: "These sea lions have lived on K-Dock since 1990!", s: [4.52, 4.28] },
  { id: "w5-a-931ea3e1", lane: "a", zh: "最多的时候来过 2100 多只呢——2024 年 5、6 月！", en: "The record: over 2,100 of them, in May–June 2024!", s: [5.45, 6.35] },
  { id: "w5-a-bbc9717c", lane: "a", zh: "坐稳啦——冲！", en: "Hold tight — go!", s: [1.2, 1.75] },
  { id: "w5-a-420d6131", lane: "a", zh: "滑了好远！草地真滑～", en: "What a slide! This grass is slippery!", s: [3.44, 4.42] },
  { id: "w5-a-ac3a7656", lane: "a", zh: "滑得真顺～", en: "Smooth ride!", s: [1.37, 1.37] },
  { id: "w5-a-c47f65e8", lane: "a", zh: "里昂街台阶大约 300 级，一路修剪整齐的树篱，正对着艺术宫！", en: "The Lyon Street Steps: about 300 of them, neat hedges, and the Palace of Fine Arts dead ahead!", s: [5.08, 7.26] },
  { id: "w5-a-6c4f2c8f", lane: "a", zh: "车要掉头啦！跟着我喊：嘿——咻！", en: "The car’s turning! Shout with me: heave — ho!", s: [4.73, 4.32] },
  { id: "w5-a-161fb877", lane: "a", zh: "前面坡顶插着小旗，开快点冲过去能飞起来！", en: "Pennants on the crest ahead — go fast and we’ll fly!", s: [4.45, 3.23] },
  { id: "w5-a-d811134b", lane: "a", zh: "看，K 码头上好多海狮！数数有几只？", en: "Look at all the sea lions on K-Dock! Shall we count them?", s: [3.56, 4.51] },
  { id: "w5-d-11b086d4", lane: "d", zh: "1989 年秋天起，海狮陆续搬到这片浮台上来了。", en: "From the autumn of 1989 the sea lions began moving onto these docks.", s: [5.39, 5.63] },
];

/** clips whose pick missed a gate (the listening sheet says "check"): muted until the owner approves them */
export const W7_VOICE_CHECK: readonly string[] = ["zh-w5-a-5d9dcf9c", "zh-w5-a-6807a93e", "zh-w5-a-b95c4fe2", "en-w5-a-b95c4fe2", "en-w5-a-0b992197", "zh-w5-a-420d6131", "zh-w5-a-6c4f2c8f"];

const DIR = '/opus-bay/w7/voice';
export const W7_VOICE_CLIPS: Record<string, VoiceClip> = Object.fromEntries(W7_VOICE_LINES.flatMap(l => (['zh', 'en'] as const).map((lang, k): [string, VoiceClip] => [
  `${lang}-${l.id}`, { m4a: `${DIR}/${lang}-${l.id}.m4a`, ogg: `${DIR}/${lang}-${l.id}.ogg`, lang, text: l[lang], duration: l.s[k] },
])));

/** retakes of wave-6 clips (their wave-6 clip ids; the new files are wave 7's) */
export const W7_RETAKE_CLIPS: Record<string, VoiceClip> = {
  "zh-w6g-street-fair-oaks": { m4a: `${DIR}/zh-w6g-street-fair-oaks.m4a`, ogg: `${DIR}/zh-w6g-street-fair-oaks.ogg`, lang: "zh", text: "Fair Oaks 街是诺伊谷的万圣节老地方，往年会封街！", duration: 4.43 },
  "zh-w6-h-hunt-all": { m4a: `${DIR}/zh-w6-h-hunt-all.m4a`, ogg: `${DIR}/zh-w6-h-hunt-all.ogg`, lang: "zh", text: "四十个全找齐啦！今年的南瓜王就是你！", duration: 3.6 },
  "en-w6-h-hunt-20": { m4a: `${DIR}/en-w6-h-hunt-20.m4a`, ogg: `${DIR}/en-w6-h-hunt-20.ogg`, lang: "en", text: "Twenty! That’s half of them found.", duration: 2.87 },
};

registerVoiceClips(W7_RETAKE_CLIPS);
registerVoiceClips(W7_VOICE_CLIPS, W7_VOICE_CHECK);
