/**
 * GENERATED by scripts/opus-sf/voice/w8/post.py — do not edit by hand.
 * BAYBAY's recorded wave-8 lines (lane X, W8-X1): the fixed bubble lines no earlier table had (lane M's wave-7 games,
 * lane K's plain bubbles, wave 8's new lines — scripts/opus-sf/voice/w8/lines.ts), zh + en, qwen_audio_tts preset
 * "Pixie" (the wave-4…7 voice), trimmed, two-pass loudnorm −18 LUFS / TP −1.5, AAC 64k .m4a + Opus 48k .ogg.
 * game/voiceW5.ts matches BAYBAY's bubbles against this table too (zh + en exactly; an earlier recording of the same
 * words wins). W8_RETAKE_CLIPS: faster takes of wave-7 clips that were muted (W7_VOICE_CHECK, the rate gate), under the
 * wave-7 clip ids — this module registers them before data/sf/voiceW7.ts (the binder imports it first) and the binder
 * no longer mutes them. Measurements, picks and the owner's listening sheet: docs/opus-bay/qa/w8/X/voice/.
 */
import { type VoiceClip, registerVoiceClips } from '../assets';

export interface W8VoiceLine { id: string; lane: string; zh: string; en: string; /** seconds: zh, en */ s: readonly [number, number]; /** the lane plays it (a voice-line event with this id): never matched by text */ own?: 1 }

export const W8_VOICE_LINES: readonly W8VoiceLine[] = [
  { id: "w5-a-692eab60", lane: "a", zh: "机械博物馆！三百多台老游戏机，玩一台抓娃娃？", en: "The Musée Mécanique! Over 300 old machines — try the claw?", s: [4.7, 5.64] },
  { id: "w5-a-20bfa352", lane: "a", zh: "五枚硬币，看准了再抓！", en: "Five quarters. Line it up, then grab!", s: [2.82, 3.54] },
  { id: "w5-a-7838c5cc", lane: "a", zh: "抓到啦！掉进出口了！", en: "Got it! Down the chute!", s: [2.46, 1.5] },
  { id: "w5-a-8ffd6654", lane: "a", zh: "哎呀，滑掉了！", en: "Oops, it slipped!", s: [1.81, 1.79] },
  { id: "w5-a-778c7dc0", lane: "a", zh: "差一点点！再对准一些～", en: "So close! Line it up a bit more.", s: [3.57, 3.39] },
  { id: "w5-a-5248e608", lane: "a", zh: "新的纪念品！又多收集了一种！", en: "A new souvenir for the collection!", s: [2.59, 2.7] },
  { id: "w5-a-d8e1d8a4", lane: "a", zh: "八种纪念品全抓齐了！你是抓娃娃大师！", en: "All eight souvenirs! You’re a claw master!", s: [3.89, 3.57] },
  { id: "w5-a-c20171ba", lane: "a", zh: "旁边的算命婆婆也想跟你说句话～", en: "The fortune teller next door wants a word too!", s: [2.88, 3.26] },
  { id: "w5-a-b38115d4", lane: "a", zh: "这里的机器都吃 25 美分硬币，进门不要钱！", en: "The machines here take quarters — and walking in is free!", s: [4.18, 2.84] },
  { id: "w5-a-416727f0", lane: "a", zh: "最老的一台是 1884 年的，比金门大桥还老！", en: "The oldest machine here is from 1884 — older than the Golden Gate Bridge!", s: [5.51, 6.38] },
  { id: "w5-a-89e99fc1", lane: "a", zh: "这些机器 2002 年才从海边的悬崖屋搬到 45 号码头。", en: "These machines moved from the Cliff House to Pier 45 in 2002.", s: [5.28, 5.37] },
  { id: "w5-a-5a04c263", lane: "a", zh: "好多人在 7 号码头捞螃蟹！我们也放个网试试？", en: "People crab off Pier 7! Shall we drop a net?", s: [4.5, 3.57] },
  { id: "w5-a-7959d7a5", lane: "a", zh: "放网！等螃蟹闻到饵爬进来～", en: "Net down! Wait for the crabs to smell the bait…", s: [3.21, 4.01] },
  { id: "w5-a-5c057864", lane: "a", zh: "绳子在动！螃蟹进网啦，快拉！", en: "The rope’s twitching — crabs in the net, pull!", s: [3.11, 3.62] },
  { id: "w5-a-893672b0", lane: "a", zh: "拉早啦，螃蟹还没进来呢～", en: "Too early — no crabs in yet.", s: [3.54, 2.8] },
  { id: "w5-a-aec5cba8", lane: "a", zh: "拉晚了，饵被吃光，螃蟹走掉了～", en: "Too late — the bait’s gone and so are the crabs.", s: [3.32, 3.63] },
  { id: "w5-a-d14a5c34", lane: "a", zh: "拉慢了，有螃蟹从网边溜走了！", en: "Too slow — one scuttled off the net!", s: [2.95, 3.01] },
  { id: "w5-a-10b83d1a", lane: "a", zh: "量一量：够大的留下，太小的放回去！", en: "Measure them: keepers stay, small ones go back!", s: [4.22, 3.93] },
  { id: "w5-a-25182d00", lane: "a", zh: "这是珍宝蟹！在旧金山湾里一只都不能带走，放回去！", en: "A Dungeness! In San Francisco Bay they always go back!", s: [4.46, 4.73] },
  { id: "w5-a-bcc6583c", lane: "a", zh: "石蟹不到 4 英寸，放回去长大吧～", en: "A rock crab under 4 inches goes back to grow!", s: [3.65, 4.06] },
  { id: "w5-a-482d1993", lane: "a", zh: "这只石蟹够 4 英寸了！", en: "This rock crab is over 4 inches!", s: [2.83, 3.47] },
  { id: "w5-a-61af8842", lane: "a", zh: "再看看尺子哦～", en: "Check the gauge again!", s: [1.95, 1.54] },
  { id: "w5-a-dc695d4d", lane: "a", zh: "量好了，拍张照——都放回海里啦！", en: "Measured and photographed — and all back in the bay!", s: [3.56, 3.72] },
  { id: "w5-a-020cb6aa", lane: "a", zh: "在加州的公共码头钓鱼捞螃蟹，不用执照！", en: "On a California public pier, you don’t need a fishing licence!", s: [4.13, 4.66] },
  { id: "w5-a-b2f94b25", lane: "a", zh: "闻到酸面包的香味了！我们也来捏一个？", en: "Smell that sourdough! Shall we shape one?", s: [3.67, 3.46] },
  { id: "w5-a-4338aef0", lane: "a", zh: "先揉面：跟着节拍折过来、压下去！", en: "Knead first: fold and press on the beat!", s: [5.29, 3.88] },
  { id: "w5-a-db6f18d1", lane: "a", zh: "选个形状！码头的面包师会捏螃蟹和乌龟！", en: "Pick a shape! The Wharf bakers make crabs and turtles!", s: [4.65, 4.37] },
  { id: "w5-a-3fab2d6f", lane: "a", zh: "划几刀，面包才会漂亮地裂开！", en: "Score it, so it opens up nicely in the oven!", s: [3.39, 3.31] },
  { id: "w5-a-a35821dc", lane: "a", zh: "进烤箱！颜色金黄就拿出来！", en: "Into the oven! Out when it’s golden!", s: [2.32, 3.09] },
  { id: "w5-a-ecac118d", lane: "a", zh: "还有点白，再烤一会儿就好了～", en: "A little pale — a bit longer next time.", s: [3.36, 3.76] },
  { id: "w5-a-2de97f72", lane: "a", zh: "烤得有点黑啦，不过闻着好香！", en: "A bit dark — but it smells great!", s: [3.33, 3.33] },
  { id: "w5-a-eb85ad0b", lane: "a", zh: "金黄酥脆！完美！", en: "Golden and crackly! Perfect!", s: [1.97, 2.53] },
  { id: "w5-a-44f5a821", lane: "a", zh: "1849 年淘金热的时候，酸面包就是旧金山的日常面包了。", en: "Since the 1849 Gold Rush, sourdough has been San Francisco’s everyday bread.", s: [5.51, 6.32] },
  { id: "w5-a-7e8dde5d", lane: "a", zh: "酸面包里有一种细菌，名字就叫“旧金山”！", en: "There’s a bacterium in sourdough named after San Francisco!", s: [4.68, 4.44] },
  { id: "w5-k-2aa6fb42", lane: "k", zh: "这条线今天没开，我们走过去吧！", en: "That line isn't running today — let's walk!", s: [2.39, 3.35] },
  { id: "w5-k-2e87c7f2", lane: "k", zh: "提前下车啦，我们走过去！", en: "Off early — we walk from here!", s: [2.57, 2.26] },
  { id: "w5-k-257c510d", lane: "k", zh: "就在这儿降落啦，我们走过去！", en: "We landed here — let’s walk the rest!", s: [2.63, 2.26] },
  { id: "w5-k-7c88ffac", lane: "k", zh: "有车来，我们先让一让～", en: "A car is coming. Let’s step aside", s: [1.81, 3.25] },
  { id: "w5-k-2a49803a", lane: "k", zh: "这段路有点难走，你来带路吧！", en: "This bit is tricky — you steer for a moment!", s: [2.29, 3.6] },
  { id: "w5-k-169f9235", lane: "k", zh: "坐过一站再下车，才算坐过哦", en: "Ride at least one stop and it counts as a ride", s: [2.68, 3.63] },
  { id: "w5-k-deef4cff", lane: "k", zh: "坐到下一站再下车，才算坐过 F 线电车哦", en: "Ride to the next stop and it counts as a streetcar ride", s: [4.24, 3.87] },
  { id: "w5-k-83579ca0", lane: "k", zh: "当——当——当！", en: "Dong — dong — dong!", s: [1.9, 1.46] },
  { id: "w5-k-eabf6332", lane: "k", zh: "嗯～好吃！", en: "Mmm, tasty!", s: [1.0, 1.29] },
  { id: "w5-k-4b1387ba", lane: "k", zh: "差一点！再来一竿，这次一定行～", en: "So close! One more cast — you’ve got this~", s: [3.56, 4.02] },
  { id: "w5-k-9124e340", lane: "k", zh: "还没咬钩，再等等～", en: "Not yet — wait for the bite!", s: [2.22, 2.6] },
  { id: "w5-k-9ae1d629", lane: "k", zh: "上车啦！上层前排视野最好，每一站我都给你讲", en: "All aboard! The front of the top deck has the best view, and I’ll tell you about every stop", s: [4.14, 6.31] },
  { id: "w5-k-00c99efb", lane: "k", zh: "叮当车在等我们让路呢，往路边站一站吧", en: "The cable car is waiting for us. Let’s step to the side", s: [3.73, 4.06] },
  { id: "w5-k-d3e5f745", lane: "k", zh: "电车在等我们让路呢，往路边站一站吧", en: "The streetcar is waiting for us. Let’s step to the side", s: [3.38, 3.72] },
  { id: "w5-k-831da4b9", lane: "k", zh: "观光巴士在等我们让路呢，往路边站一站吧", en: "The tour bus is waiting for us. Let’s step to the side", s: [3.97, 4.05] },
  { id: "w5-k-91a6801c", lane: "k", zh: "轻轨在等我们让路呢，往路边站一站吧", en: "The train is waiting for us. Let’s step to the side", s: [3.95, 3.74] },
  { id: "w5-k-3f22bdb5", lane: "k", zh: "拍得真好！这张可以当明信片了。", en: "Great shot — that could be a postcard!", s: [4.1, 3.22] },
  { id: "w5-k-7538cb4b", lane: "k", zh: "这段地铁比较长，想快点可以点「直接到站」。", en: "A long Metro leg — tap Skip to stop to get there sooner.", s: [3.93, 4.56] },
  { id: "w5-a-b2601524", lane: "a", zh: "最近的观景点我标出来啦，跟着标记走吧！", en: "I’ve marked the nearest lookout — just follow the pin!", s: [3.08, 3.56] },
  { id: "w5-k-7755a76a", lane: "k", zh: "跟我来！我带你过去～", en: "Follow me — I’ll take you there!", s: [2.79, 1.96] },
  { id: "w5-k-d77094cb", lane: "k", zh: "到啦！试试看吧～", en: "Here we are — give it a try!", s: [1.46, 2.76] },
  { id: "w5-k-23a8415a", lane: "k", zh: "到啦！就是这里～", en: "Here we are!", s: [1.79, 1.49] },
  { id: "w5-k-0d12e5c2", lane: "k", zh: "去车站，我们坐车过去！", en: "To the stop — we’ll ride there!", s: [3.12, 1.77] },
  { id: "w5-k-268761c0", lane: "k", zh: "就在这里啦！", en: "It’s right here!", s: [1.33, 1.01] },
  { id: "w5-k-6b7424b5", lane: "k", zh: "上车！出发咯～", en: "All aboard — off we go!", s: [1.87, 2.21] },
  { id: "w5-k-fce1d40b", lane: "k", zh: "坐一会儿，看看风景～", en: "Let’s sit and take in the view.", s: [3.31, 2.67] },
];

/** clips whose pick missed a gate (the listening sheet says "check"): muted until the owner approves them */
export const W8_VOICE_CHECK: readonly string[] = ["zh-w5-k-83579ca0", "zh-w5-k-7755a76a"];

const DIR = '/opus-bay/w8/voice';
export const W8_VOICE_CLIPS: Record<string, VoiceClip> = Object.fromEntries(W8_VOICE_LINES.flatMap(l => (['zh', 'en'] as const).map((lang, k): [string, VoiceClip] => [
  `${lang}-${l.id}`, { m4a: `${DIR}/${lang}-${l.id}.m4a`, ogg: `${DIR}/${lang}-${l.id}.ogg`, lang, text: l[lang], duration: l.s[k] },
])));

/** retakes of wave-7 muted clips (their wave-7 clip ids; the new files are wave 8's): they play, unmuted */
export const W8_RETAKE_CLIPS: Record<string, VoiceClip> = {
  "zh-w5-a-5d9dcf9c": { m4a: `${DIR}/zh-w5-a-5d9dcf9c.m4a`, ogg: `${DIR}/zh-w5-a-5d9dcf9c.ogg`, lang: "zh", text: "哎哟，碰到啦～", duration: 2.0 },
  "zh-w5-a-6807a93e": { m4a: `${DIR}/zh-w5-a-6807a93e.m4a`, ogg: `${DIR}/zh-w5-a-6807a93e.ogg`, lang: "zh", text: "差一点！我去捡回来～", duration: 2.46 },
  "zh-w5-a-b95c4fe2": { m4a: `${DIR}/zh-w5-a-b95c4fe2.m4a`, ogg: `${DIR}/zh-w5-a-b95c4fe2.ogg`, lang: "zh", text: "咻！正好！", duration: 1.11 },
  "en-w5-a-0b992197": { m4a: `${DIR}/en-w5-a-0b992197.m4a`, ogg: `${DIR}/en-w5-a-0b992197.ogg`, lang: "en", text: "Hot! Really close!", duration: 1.75 },
  "zh-w5-a-420d6131": { m4a: `${DIR}/zh-w5-a-420d6131.m4a`, ogg: `${DIR}/zh-w5-a-420d6131.ogg`, lang: "zh", text: "滑了好远！草地真滑～", duration: 2.63 },
  "zh-w5-a-6c4f2c8f": { m4a: `${DIR}/zh-w5-a-6c4f2c8f.m4a`, ogg: `${DIR}/zh-w5-a-6c4f2c8f.ogg`, lang: "zh", text: "车要掉头啦！跟着我喊：嘿——咻！", duration: 3.08 },
  "en-w5-a-9a2d1075": { m4a: `${DIR}/en-w5-a-9a2d1075.m4a`, ogg: `${DIR}/en-w5-a-9a2d1075.ogg`, lang: "en", text: "Not quite!", duration: 1.06 },
};

registerVoiceClips(W8_RETAKE_CLIPS);
registerVoiceClips(W8_VOICE_CLIPS, W8_VOICE_CHECK);
