/**
 * GENERATED by scripts/opus-sf/voice/w6/post.py — do not edit by hand.
 * BAYBAY's recorded wave-6 Halloween lines (lane X, W6-X4): lanes G (halloween/lines.ts) and H (halloween/worldLines.ts),
 * their fixed bubble lines (scripts/opus-sf/voice/w6/lines.ts), zh + en, qwen_audio_tts preset "Pixie" (the wave-4 / 5 voice),
 * trimmed, two-pass loudnorm −18 LUFS / TP −1.5, AAC 64k .m4a + Opus 48k .ogg. Clip id `<lang>-<id>` (the lanes' ids).
 * game/voiceW5.ts matches BAYBAY's bubbles against this table too (zh + en exactly). Measurements, picks and the owner's
 * listening sheet: docs/opus-bay/qa/w6/X/voice/. Registered in ASSETS.voice on import (the city chunk, through
 * game/voiceW5.ts); the W6_VOICE_CHECK clips stay unregistered (text only).
 */
import { type VoiceClip, registerVoiceClips } from '../assets';

export interface W6VoiceLine { id: string; lane: string; zh: string; en: string; /** seconds: zh, en */ s: readonly [number, number] }

export const W6_VOICE_LINES: readonly W6VoiceLine[] = [
  { id: "w6g-knock", lane: "g", zh: "不给糖就捣蛋！", en: "Trick or treat!", s: [1.38, 1.12] },
  { id: "w6g-thanks", lane: "g", zh: "谢谢您！万圣节快乐！", en: "Thank you! Happy Halloween!", s: [2.8, 2.61] },
  { id: "w6g-again", lane: "g", zh: "这家我们来过啦，去下一家吧！", en: "We’ve been here already — on to the next house!", s: [2.23, 3.37] },
  { id: "w6g-nobody", lane: "g", zh: "没人在家……门上贴着「出去讨糖啦」！", en: "Nobody’s home… the note says “Out trick-or-treating!”", s: [4.87, 5.57] },
  { id: "w6g-treat-hour", lane: "g", zh: "门廊的灯都亮起来了，正是讨糖的好时候！", en: "The porch lights are on — perfect time for trick-or-treating!", s: [3.69, 3.69] },
  { id: "w6g-big-night", lane: "g", zh: "今晚是万圣节！每家都开门，糖果还加倍！", en: "It’s Halloween night! Every door’s open, and the treats are doubled!", s: [3.76, 5.41] },
  { id: "w6g-bag-heavy", lane: "g", zh: "糖果袋越来越沉啦！", en: "Our candy bag’s getting heavy!", s: [2.28, 2.36] },
  { id: "w6g-not-too-much", lane: "g", zh: "糖果留着慢慢吃，一次别吃太多哦！", en: "Let’s save some candy — not too much at once!", s: [3.39, 3.56] },
  { id: "w6g-all-doors", lane: "g", zh: "哇，我们敲遍了所有的门！", en: "Wow — we’ve knocked on every single door!", s: [3.25, 3.0] },
  { id: "w6g-season-over", lane: "g", zh: "万圣节过去啦，明年再来讨糖吧！", en: "Halloween’s over — let’s come trick-or-treating again next year!", s: [3.4, 4.19] },
  { id: "w6g-street-belvedere", lane: "g", zh: "贝尔维德街是城里最有名的万圣节讨糖街之一，往年还会封街！", en: "Belvedere Street is one of the city’s best-known Halloween streets — it usually closes to cars, too!", s: [5.84, 6.55] },
  { id: "w6g-street-chenery", lane: "g", zh: "格伦公园的 Chenery 街，往年万圣节傍晚会封街讨糖。", en: "In Glen Park, Chenery Street usually closes to cars on Halloween evening for trick-or-treaters.", s: [4.68, 6.31] },
  { id: "w6g-street-fair-oaks", lane: "g", zh: "Fair Oaks 街是诺伊谷的万圣节老地方，往年会封街！", en: "Fair Oaks Street is Noe Valley’s Halloween classic — it usually closes to cars!", s: [5.14, 5.87] },
  { id: "w6g-street-jordan", lane: "g", zh: "乔丹公园这边，往年万圣节 Jordan 大道会封街讨糖。", en: "Here in Jordan Park, Jordan Avenue usually closes to cars for Halloween.", s: [4.73, 5.12] },
  { id: "w6g-street-sea-cliff", lane: "g", zh: "海崖区的大房子万圣节都装饰得好隆重，每年有好几百人来讨糖！", en: "Sea Cliff’s big houses go all out for Halloween — hundreds of trick-or-treaters come every year!", s: [5.58, 6.6] },
  { id: "w6g-street-hearst", lane: "g", zh: "阳光谷的 Hearst 大道，往年万圣节傍晚也会封街讨糖。", en: "In Sunnyside, Hearst Avenue usually closes to cars on Halloween evening too.", s: [4.55, 5.38] },
  { id: "w6g-costume-witch", lane: "g", zh: "我像不像一个小女巫？", en: "Do I look like a little witch?", s: [3.44, 1.96] },
  { id: "w6g-costume-pumpkin", lane: "g", zh: "嘿嘿，今天我是一颗南瓜！", en: "Hee hee — today I’m a pumpkin!", s: [3.22, 3.11] },
  { id: "w6g-costume-ghost", lane: "g", zh: "哇！小幽灵，吓我一跳！", en: "Whoa! A little ghost — you made me jump!", s: [3.0, 3.47] },
  { id: "w6g-costume-cat", lane: "g", zh: "喵～你的猫耳朵好可爱！", en: "Meow~ I love your cat ears!", s: [3.18, 3.2] },
  { id: "w6g-costume-first", lane: "g", zh: "穿上服装，我们就能去讨糖啦！", en: "Now we’re in costume, we can go trick-or-treating!", s: [2.44, 3.51] },
  { id: "w6g-goal-done", lane: "g", zh: "敲开了五户人家的门，糖果袋满满的！", en: "Five doors knocked — our candy bag is full!", s: [4.51, 3.55] },
  { id: "w6-h-season-hello", lane: "h", zh: "十月啦！家家门口都摆上了南瓜灯～", en: "It’s October! There are pumpkins on every doorstep.", s: [3.91, 4.51] },
  { id: "w6-h-night-glow", lane: "h", zh: "天黑了，门口的南瓜灯都亮起来啦，好温暖。", en: "It’s dark now — all the jack-o’-lanterns are glowing. So cosy.", s: [4.73, 5.66] },
  { id: "w6-h-bats", lane: "h", zh: "看天上！小蝙蝠在绕圈圈～别怕，它们只爱吃虫子。", en: "Look up! Little bats circling. Don’t worry — they only eat bugs.", s: [6.02, 5.41] },
  { id: "w6-h-ghosts", lane: "h", zh: "那边有小幽灵和小南瓜！是邻居家的小朋友扮的吧～", en: "A little ghost and a little pumpkin! The neighbours’ kids dressed up.", s: [4.19, 5.2] },
  { id: "w6-h-big-night", lane: "h", zh: "今晚是万圣节大夜晚！整条街都亮着南瓜灯。", en: "Tonight’s the big Halloween night! The whole street is glowing.", s: [4.6, 4.83] },
  { id: "w6-h-dusk", lane: "h", zh: "南瓜色的黄昏，有一点点神秘，又很温柔～", en: "A pumpkin-coloured dusk — a little spooky, and very cosy.", s: [4.82, 4.89] },
  { id: "w6-h-hunt-first", lane: "h", zh: "找到一个藏起来的南瓜灯！全城还藏着好多个呢～", en: "A hidden jack-o’-lantern! There are lots more hiding around the city.", s: [5.2, 4.79] },
  { id: "w6-h-hunt-found", lane: "h", zh: "又找到一个南瓜灯！", en: "Another jack-o’-lantern!", s: [1.87, 1.79] },
  { id: "w6-h-hunt-sniff", lane: "h", zh: "咦，附近好像有南瓜灯的光……", en: "Hm — I can see a pumpkin glow somewhere near…", s: [3.82, 4.13] },
  { id: "w6-h-hunt-night", lane: "h", zh: "藏起来的南瓜灯晚上会发光，天黑了更好找哦。", en: "The hidden lanterns glow at night — they’re easier to spot after dark.", s: [4.9, 4.57] },
  { id: "w6-h-hunt-10", lane: "h", zh: "十个南瓜灯啦！你是寻宝高手！", en: "Ten jack-o’-lanterns! You’re a real treasure hunter!", s: [3.57, 3.78] },
  { id: "w6-h-hunt-20", lane: "h", zh: "二十个了！已经找到一半啦～", en: "Twenty! That’s half of them found.", s: [2.58, 3.15] },
  { id: "w6-h-hunt-all", lane: "h", zh: "四十个全找齐啦！今年的南瓜王就是你！", en: "All forty! You’re this year’s Pumpkin King!", s: [3.83, 3.32] },
  { id: "w6-h-muertos-hello", lane: "h", zh: "今天是亡灵节！教会区挂满了彩色剪纸旗，还有万寿菊。", en: "It’s Día de los Muertos! The Mission is full of papel picado and marigolds.", s: [5.76, 6.29] },
  { id: "w6-h-muertos-altar", lane: "h", zh: "这是纪念亲人的祭坛，有照片、蜡烛和万寿菊。我们轻轻地看。", en: "An altar for loved ones — photos, candles, marigolds. Let’s look quietly.", s: [6.67, 6.91] },
  { id: "w6-h-muertos-marigold", lane: "h", zh: "传说万寿菊的橙色和香味，能给思念的人照亮回家的路。", en: "They say the marigolds’ colour and scent light the way home for those we miss.", s: [4.89, 5.23] },
  { id: "w6-h-muertos-procession", lane: "h", zh: "每年 11 月 2 日晚上，大家从 22 街和布莱恩特街口出发游行。", en: "Every 2 November, in the evening, a procession sets off from 22nd and Bryant.", s: [6.35, 6.4] },
  { id: "w6-h-muertos-all", lane: "h", zh: "每个祭坛都看过啦。谢谢你陪我一起记住大家。", en: "We’ve seen every altar. Thank you for remembering with me.", s: [4.48, 3.99] },
];

/** clips whose pick missed a gate (the listening sheet says "check"): muted until the owner approves them */
export const W6_VOICE_CHECK: readonly string[] = [];

const DIR = '/opus-bay/w6/voice';
export const W6_VOICE_CLIPS: Record<string, VoiceClip> = Object.fromEntries(W6_VOICE_LINES.flatMap(l => (['zh', 'en'] as const).map((lang, k): [string, VoiceClip] => [
  `${lang}-${l.id}`, { m4a: `${DIR}/${lang}-${l.id}.m4a`, ogg: `${DIR}/${lang}-${l.id}.ogg`, lang, text: l[lang], duration: l.s[k] },
])));

registerVoiceClips(W6_VOICE_CLIPS, W6_VOICE_CHECK);
