/**
 * GENERATED by scripts/opus-sf/voice/w9/post.py — do not edit by hand.
 * BAYBAY's recorded wave-9 lines (lane X, W9-X4): the fixed bubble lines no earlier table had (wave 8's unrecorded
 * lines, wave 9's new and reworded lines — scripts/opus-sf/voice/w9/lines.ts), zh + en, qwen_audio_tts preset
 * "Pixie" (the wave-4…8 voice), trimmed, two-pass loudnorm −18 LUFS / TP −1.5, AAC 64k .m4a + Opus 48k .ogg.
 * game/voiceW5.ts matches BAYBAY's bubbles against this table too (zh + en exactly; an earlier recording of the same
 * words wins). Measurements, picks and the owner's listening sheet: docs/opus-bay/qa/w9/X/voice/.
 */
import { type VoiceClip, registerVoiceClips } from '../assets';

export interface W9VoiceLine { id: string; lane: string; zh: string; en: string; /** seconds: zh, en */ s: readonly [number, number]; /** the lane plays it (a voice-line event with this id): never matched by text */ own?: 1 }

export const W9_VOICE_LINES: readonly W9VoiceLine[] = [
  { id: "w5-a-adfb2f33", lane: "a", zh: "这趟太短啦，下次坐远一点再拉闸！", en: "That ride was too short! Grip on a longer one next time.", s: [3.14, 4.26] },
  { id: "w5-a-ddd3b836", lane: "a", zh: "嘿嘿，找个更陡的坡试试？", en: "Hehe, try a steeper slope?", s: [2.11, 2.98] },
  { id: "w5-w2-280f73fb", lane: "w2", zh: "船屋从1893年起就租船给游客。", en: "The boathouse has rented boats to visitors since 1893.", s: [3.35, 6.15] },
  { id: "w5-al-3042cee4", lane: "al", zh: "回城啦。回头再看一眼恶魔岛，前面就是旧金山。", en: "Heading back to the city. One last look at Alcatraz — San Francisco is just ahead.", s: [4.88, 5.84] },
  { id: "w8w1-pagodas-ahead-w9", lane: "w1", zh: "往上看！路口两座宝塔楼：Sing Fat 和绿顶的 Sing Chong。", en: "Look up! The two pagoda towers at the corner: Sing Fat, and Sing Chong with the green roofs.", s: [5.31, 6.67] },
  { id: "w5-c-df86205a", lane: "c", zh: "想飞的时候，叫上鹈鹕就行～", en: "Whenever you want to fly, just call the pelican!", s: [2.88, 3.65] },
  { id: "w5-r-a13d0aed", lane: "r", zh: "今天城里有活动！旅行本「今天」里写着呢～", en: "Something’s on in the city today — it’s on the journal’s Today page!", s: [4.02, 4.57] },
  { id: "w5-r-abd86c7b", lane: "r", zh: "今天的日落时间和三件小事，都在旅行本「今天」里～", en: "Today’s sunset time and three small things are on the journal’s Today page.", s: [4.65, 5.06] },
  { id: "w5-r-7d16e184", lane: "r", zh: "旅行本「今天」里有今日三件小事，慢慢逛～", en: "Three small things for today wait on the journal’s Today page — no rush.", s: [3.99, 5.03] },
  { id: "w5-a-311ad20d", lane: "a", zh: "马路这里过不去，从斑马线过去吧！", en: "You can’t cross here. Use the zebra crossing!", s: [3.18, 4.04] },
  { id: "w9-h-today-festival", lane: "h", zh: "万圣节快乐！今天唐人街的 Waverly 巷有万圣节庆典，下午三点结束～", en: "Happy Halloween! Chinatown’s Halloween Festival is on Waverly Place today, until three o’clock.", s: [7.24, 6.35] },
  { id: "w9-h-today-big-night", lane: "h", zh: "万圣节快乐！今天讨糖街家家都开门，糖果加倍，旅行本「万圣节」页能带你去～", en: "Happy Halloween! Every treat-street door answers today, treats doubled — the Halloween page takes us there.", s: [8.66, 6.46] },
  { id: "w9-h-today-procession", lane: "h", zh: "今晚教会区有亡灵节游行，通常七点从 22 街和布莱恩特街口出发，以官网为准。", en: "The Día de los Muertos procession usually leaves 22nd & Bryant at seven tonight — check the official site.", s: [5.89, 7.76] },
  { id: "w5-n-645daeca", lane: "n", zh: "这段路被挡住了，我们怎么走？", en: "This way is blocked. How shall we go?", s: [2.69, 3.6] },
];

/** clips whose pick missed a gate (the listening sheet says "check"): muted until the owner approves them */
export const W9_VOICE_CHECK: readonly string[] = [];

const DIR = '/opus-bay/w9/voice';
export const W9_VOICE_CLIPS: Record<string, VoiceClip> = Object.fromEntries(W9_VOICE_LINES.flatMap(l => (['zh', 'en'] as const).map((lang, k): [string, VoiceClip] => [
  `${lang}-${l.id}`, { m4a: `${DIR}/${lang}-${l.id}.m4a`, ogg: `${DIR}/${lang}-${l.id}.ogg`, lang, text: l[lang], duration: l.s[k] },
])));

registerVoiceClips(W9_VOICE_CLIPS, W9_VOICE_CHECK);
