/**
 * GENERATED by scripts/opus-sf/voice/w7/post.py — do not edit by hand.
 * BAYBAY's recorded wave-7 lines (lane X, W7-X2): the fixed bubble lines no earlier table had (waves 5–7: play/, eggs/,
 * economy/, lanes G / H's Halloween tables, W2's activities — scripts/opus-sf/voice/w7/lines.ts), zh + en, qwen_audio_tts
 * preset "Pixie" (the wave-4…6 voice), trimmed, two-pass loudnorm −18 LUFS / TP −1.5, AAC 64k .m4a + Opus 48k .ogg.
 * game/voiceW5.ts matches BAYBAY's bubbles against this table too (zh + en exactly; an earlier recording of the same
 * words wins). W7_RETAKE_CLIPS: new takes of wave-6 clips the recogniser missed, under the wave-6 clip ids — this module
 * registers them before data/sf/voiceW6.ts does (the binder imports it first), so the retake plays. Measurements, picks
 * and the owner's listening sheet: docs/opus-bay/qa/w7/X/voice/.
 */
import { type VoiceClip, registerVoiceClips } from '../assets';

export interface W7VoiceLine { id: string; lane: string; zh: string; en: string; /** seconds: zh, en */ s: readonly [number, number]; /** the lane plays it (a voice-line event with this id): never matched by text */ own?: 1 }

export const W7_VOICE_LINES: readonly W7VoiceLine[] = [
  { id: "w5-a-760e436e", lane: "a", zh: "我先发球！轮到你时，等影子变金色就点它～", en: "I’ll serve! On your turn, tap the shadow when it turns gold!", s: [3.96, 4.7] },
  { id: "w5-a-e5c9d3d8", lane: "a", zh: "还高着呢，等它落下来～", en: "Still high — let it come down!", s: [2.75, 2.66] },
  { id: "w5-a-6a5edde8", lane: "a", zh: "哎呀，落地啦！", en: "Oops, it landed!", s: [1.29, 1.78] },
  { id: "w5-a-83b85919", lane: "a", zh: "好球！", en: "Nice one!", s: [1.0, 1.01] },
  { id: "w5-a-8be2fa97", lane: "a", zh: "呜呼——飞起来啦！插小旗的就是坡顶！", en: "Woohoo — we flew! The pennants mark the crests!", s: [3.9, 4.41] },
  { id: "w5-a-0ade6a62", lane: "a", zh: "再飞一次！", en: "Up we go again!", s: [1.02, 1.21] },
  { id: "w5-a-d6da08f3", lane: "a", zh: "全城 12 个坡顶都飞过啦！", en: "All 12 crests in the city — hopped!", s: [2.73, 3.35] },
  { id: "w5-a-4a04af8b", lane: "a", zh: "九曲花街的路牌建议每小时 5 英里——慢慢开，别碰到花坛！", en: "Lombard’s sign says 5 mph — nice and slow, mind the flower beds!", s: [4.83, 5.88] },
  { id: "w5-a-baa3f3d8", lane: "a", zh: "佛蒙特街只有 7 个弯，可坡更陡——慢一点！", en: "Vermont has seven bends but a steeper hill — slowly!", s: [4.7, 4.19] },
  { id: "w5-a-4a24dc9b", lane: "a", zh: "九曲花街这一段有 8 个急弯，而且只能往下开哦！", en: "Eight hairpins on this block — and it’s one way, downhill!", s: [4.86, 4.46] },
  { id: "w5-a-c3fe95c7", lane: "a", zh: "有人量过，佛蒙特街其实更弯：弯曲度 1.56 比 1.2！", en: "Someone measured it: Vermont Street is curvier — 1.56 to 1.2!", s: [6.0, 6.48] },
  { id: "w5-a-7f1eaa1c", lane: "a", zh: "佛蒙特街只有 7 个弯，却被量出比九曲花街还弯！", en: "Only seven bends, yet measured curvier than Lombard!", s: [5.22, 4.45] },
  { id: "w5-a-774352f1", lane: "a", zh: "两条都开过啦！论弯，佛蒙特街赢；论花，九曲花街赢～", en: "Both done! Vermont wins on bends, Lombard on flowers!", s: [5.09, 5.08] },
  { id: "w5-a-5d9dcf9c", lane: "a", zh: "哎哟，碰到啦～", en: "Oops — a bump!", s: [2.27, 1.54] },
  { id: "w5-a-f394a25d", lane: "a", zh: "点一下地面，扔到那儿！我去接～", en: "Tap the ground to throw — I’ll fetch!", s: [3.02, 3.33] },
  { id: "w5-a-f87a967e", lane: "a", zh: "接住啦！", en: "Got it!", s: [0.82, 0.5] },
  { id: "w5-a-c225f73e", lane: "a", zh: "飞身接住！", en: "Diving catch!", s: [1.13, 1.25] },
  { id: "w5-a-6807a93e", lane: "a", zh: "差一点！我去捡回来～", en: "So close! I’ll fetch it!", s: [3.38, 2.82] },
  { id: "w5-a-d4a250de", lane: "a", zh: "扔到那边就捡不回来啦，换个地方～", en: "Can’t fetch it from there — pick another spot!", s: [3.72, 3.07] },
  { id: "w5-a-dac00abb", lane: "a", zh: "好好玩！再扔几次也行～", en: "That was fun! Throw some more any time!", s: [2.88, 3.05] },
  { id: "w5-a-60c324fe", lane: "a", zh: "金门大桥金圈！绕着两座桥塔飞～", en: "Golden Gate rings! Round both towers!", s: [4.0, 3.48] },
  { id: "w5-a-471a2270", lane: "a", zh: "桥塔比海面高 227 米，1937 年就通车啦！", en: "The towers stand 227 m over the water — open since 1937!", s: [4.03, 6.63] },
  { id: "w5-a-bf57e7df", lane: "a", zh: "大桥这种橙色，名字叫“国际橙”！", en: "That orange has a name: International Orange!", s: [3.98, 4.57] },
  { id: "w5-a-80ad9d1b", lane: "a", zh: "骑上鹈鹕飞到大桥边，有金圈等你！", en: "Glide out to the bridge — there are rings!", s: [3.67, 3.14] },
  { id: "w5-a-05f0c830", lane: "a", zh: "跟着我喊：嘿——咻！咻的时候推！", en: "Shout with me: heave — ho! Push on the \"ho\"!", s: [3.55, 3.07] },
  { id: "w5-a-b95c4fe2", lane: "a", zh: "咻！正好！", en: "Ho! Spot on!", s: [1.26, 2.28] },
  { id: "w5-a-ebed5c01", lane: "a", zh: "叮当车终点的转盘是人力推的，车就这样掉头！", en: "The cable-car turntables are pushed by hand — that’s how the cars turn!", s: [4.3, 5.08] },
  { id: "w5-a-910cdcd4", lane: "a", zh: "三个转盘都推过啦！盖个章～", en: "All three turntables pushed! A stamp for you!", s: [2.95, 4.34] },
  { id: "w5-a-0b992197", lane: "a", zh: "好烫！就在附近！", en: "Hot! Really close!", s: [2.09, 2.36] },
  { id: "w5-a-22deff78", lane: "a", zh: "暖了！", en: "Warmer!", s: [0.79, 0.75] },
  { id: "w5-a-eed09ded", lane: "a", zh: "冷了…", en: "Colder…", s: [0.66, 0.83] },
  { id: "w5-a-c44fdeb8", lane: "a", zh: "等一下再玩捉迷藏吧～", en: "Let’s play hide and seek in a bit!", s: [2.27, 2.17] },
  { id: "w5-a-5da58c2c", lane: "a", zh: "这里没地方藏～换个地方再玩吧！", en: "Nowhere to hide here. Let’s try somewhere else!", s: [2.46, 3.46] },
  { id: "w5-a-af138c00", lane: "a", zh: "我在这儿呢～下次再来找我！", en: "Here I am! Find me next time!", s: [2.4, 3.27] },
  { id: "w5-a-70995063", lane: "a", zh: "闭上眼睛数三下，我去藏好！", en: "Close your eyes and count to three!", s: [4.11, 2.91] },
  { id: "w5-a-5aa34332", lane: "a", zh: "捉迷藏！你数到三，我去藏好～", en: "Hide and seek! You count to three, I’ll hide!", s: [3.48, 3.33] },
  { id: "w5-a-3122a12b", lane: "a", zh: "想玩捉迷藏吗？点「问 BAYBAY」，再点「捉迷藏」！", en: "Fancy hide and seek? Tap Ask, then Hide & seek!", s: [4.52, 4.56] },
  { id: "w5-a-06e95089", lane: "a", zh: "想玩捉迷藏吗？按 Q 问我，再选「捉迷藏」！", en: "Fancy hide and seek? Press Q to ask me, then Hide & seek!", s: [4.04, 4.67] },
  { id: "w5-a-5c7f6bf0", lane: "a", zh: "一只、两只……一起数数有几只海狮！", en: "One, two… let’s count the sea lions!", s: [5.36, 3.81] },
  { id: "w5-a-b5aa19f9", lane: "a", zh: "全数到啦！一只都没漏！", en: "Every one of them — none missed!", s: [2.85, 2.58] },
  { id: "w5-a-c9a06a9a", lane: "a", zh: "这些海狮 1990 年起就在 K 码头安家啦！", en: "These sea lions have lived on K-Dock since 1990!", s: [4.52, 4.28] },
  { id: "w5-a-931ea3e1", lane: "a", zh: "最多的时候来过 2100 多只呢——2024 年 5、6 月！", en: "The record: over 2,100 of them, in May–June 2024!", s: [5.45, 6.35] },
  { id: "w5-a-bbc9717c", lane: "a", zh: "坐稳啦——冲！", en: "Hold tight — go!", s: [1.2, 1.75] },
  { id: "w5-a-420d6131", lane: "a", zh: "滑了好远！草地真滑～", en: "What a slide! This grass is slippery!", s: [3.44, 4.42] },
  { id: "w5-a-ac3a7656", lane: "a", zh: "滑得真顺～", en: "Smooth ride!", s: [1.37, 1.37] },
  { id: "w5-a-c47f65e8", lane: "a", zh: "里昂街台阶大约 300 级，一路修剪整齐的树篱，正对着艺术宫！", en: "The Lyon Street Steps: about 300 of them, neat hedges, and the Palace of Fine Arts dead ahead!", s: [5.08, 7.26] },
  { id: "w5-a-6c4f2c8f", lane: "a", zh: "车要掉头啦！跟着我喊：嘿——咻！", en: "The car’s turning! Shout with me: heave — ho!", s: [4.73, 4.32] },
  { id: "w5-a-161fb877", lane: "a", zh: "前面坡顶插着小旗，开快点冲过去能飞起来！", en: "Pennants on the crest ahead — go fast and we’ll fly!", s: [4.45, 3.23] },
  { id: "w5-a-d811134b", lane: "a", zh: "看，K 码头上好多海狮！数数有几只？", en: "Look at all the sea lions on K-Dock! Shall we count them?", s: [3.56, 4.51] },
  { id: "w5-d-11b086d4", lane: "d", zh: "1989 年秋天起，海狮陆续搬到这片浮台上来了。", en: "From the autumn of 1989 the sea lions began moving onto these docks.", s: [5.39, 5.63] },
  { id: "w5-a-767ef631", lane: "a", zh: "被你找到啦！", en: "You found me!", s: [1.08, 1.07] },
  { id: "w5-a-1bac6ec4", lane: "a", zh: "放风筝咯！起风的时候按住放线，一松手它就往上爬！", en: "Kite time! Hold to let the line out in a gust, let go and it climbs!", s: [5.34, 5.73] },
  { id: "w5-a-3a1d4392", lane: "a", zh: "飞起来啦！", en: "It’s flying!", s: [0.9, 1.11] },
  { id: "w5-a-8def5145", lane: "a", zh: "放太久啦，它在往下栽！快松手！", en: "Too much line — it’s diving! Let go!", s: [3.67, 3.87] },
  { id: "w5-a-6cd4b449", lane: "a", zh: "哎呀，掉下来了！再放一次～", en: "Oops, it came down! Up it goes again!", s: [2.83, 3.31] },
  { id: "w5-a-64a470a4", lane: "a", zh: "线全放完啦，飞得好高！", en: "All the line out — look how high!", s: [2.63, 2.98] },
  { id: "w5-a-bae71f7a", lane: "a", zh: "码头绿地的海风最适合放风筝了！", en: "The sea breeze on Marina Green is made for kites!", s: [2.88, 3.86] },
  { id: "w5-a-e103a323", lane: "a", zh: "那是金门大桥！1937 年通车，桥塔高出水面 227 米。", en: "That’s the Golden Gate Bridge! It opened in 1937; its towers rise 746 feet above the water.", s: [5.27, 9.67] },
  { id: "w5-a-455782bb", lane: "a", zh: "那是苏特罗塔！1973 年建成的电视塔，高 298 米。", en: "That’s Sutro Tower, the TV tower: 977 feet tall since 1973.", s: [5.22, 7.53] },
  { id: "w5-a-fd00ff65", lane: "a", zh: "那是市政厅的圆顶！比美国国会大厦的圆顶还高 13 米。", en: "That’s City Hall’s dome, 42 feet taller than the US Capitol’s!", s: [5.71, 5.71] },
  { id: "w5-a-807355d3", lane: "a", zh: "那是科伊特塔！1933 年建成，塔里画满了壁画。", en: "That’s Coit Tower! Built in 1933, with murals painted all around inside.", s: [4.52, 6.79] },
  { id: "w5-a-bf1502d8", lane: "a", zh: "那是泛美金字塔！1972 年建成，当了四十多年全城最高楼。", en: "That’s the Transamerica Pyramid! Built in 1972, the city’s tallest for over forty years.", s: [6.12, 8.2] },
  { id: "w5-a-a4d4a432", lane: "a", zh: "那是 Salesforce 大楼，现在旧金山最高的楼，326 米！", en: "That’s Salesforce Tower, the tallest in San Francisco: 1,070 feet!", s: [4.75, 6.35] },
  { id: "w5-a-b399278c", lane: "a", zh: "那是渡轮大厦！1898 年建成，钟楼高 75 米。", en: "That’s the Ferry Building! Built in 1898, with a 245-foot clock tower.", s: [6.27, 6.29] },
  { id: "w5-a-6a54b10b", lane: "a", zh: "那是海湾大桥！1936 年通车，比金门大桥还早半年。", en: "That’s the Bay Bridge! It opened in 1936, six months before the Golden Gate.", s: [5.66, 6.83] },
  { id: "w5-a-39ce74bb", lane: "a", zh: "那是恶魔岛！岛上的灯塔是美国西海岸的第一座灯塔。", en: "That’s Alcatraz! Its lighthouse was the first on the US West Coast.", s: [4.34, 5.6] },
  { id: "w5-a-9d92be51", lane: "a", zh: "考考你！我指的那个是什么？", en: "Quiz time! What’s that I’m pointing at?", s: [3.46, 3.41] },
  { id: "w5-a-c8acb445", lane: "a", zh: "下一个！那个呢？", en: "Next one! And that?", s: [2.06, 2.19] },
  { id: "w5-a-f7ed0dce", lane: "a", zh: "答对啦！", en: "That’s right!", s: [1.19, 1.18] },
  { id: "w5-a-9a2d1075", lane: "a", zh: "差一点！", en: "Not quite!", s: [0.89, 1.56] },
  { id: "w5-a-cf12fea4", lane: "a", zh: "全答对了，你是旧金山通！", en: "All correct: you know your San Francisco!", s: [2.42, 3.55] },
  { id: "w5-a-6a011d8b", lane: "a", zh: "又认识了几个地标！", en: "A few more landmarks you know now!", s: [2.59, 2.71] },
  { id: "w5-a-3438493d", lane: "a", zh: "从这儿看不到大地标呢，去附近的观景点看看吧！", en: "No big landmarks in sight from here. Let’s try a lookout nearby!", s: [4.59, 4.81] },
  { id: "w7g-postcard-keep", lane: "g", zh: "万圣节明信片收进手帐啦，随时都能翻出来看！", en: "The Halloween postcard’s in our notebook — we can look at it any time!", s: [4.57, 4.36] },
  { id: "w7g-costume-bat-wings", lane: "g", zh: "鹈鹕也扮成小蝙蝠啦，扑扇扑扇！", en: "Our pelican’s a little bat now — flap, flap!", s: [3.15, 3.09] },
  { id: "w7-h-hunt-ahead", lane: "h", zh: "我看到南瓜灯的光了，就在前面！", en: "I can see a pumpkin glow — straight ahead!", s: [3.02, 3.27] },
  { id: "w7-h-hunt-left", lane: "h", zh: "南瓜灯的光在左边！我们去看看～", en: "A pumpkin glow off to the left! Let’s go and see.", s: [4.0, 3.2] },
  { id: "w7-h-hunt-right", lane: "h", zh: "南瓜灯的光在右边！我们去看看～", en: "A pumpkin glow off to the right! Let’s go and see.", s: [3.43, 3.47] },
  { id: "w7-h-hunt-behind", lane: "h", zh: "咦，南瓜灯的光在我们后面！", en: "Oh — the pumpkin glow is behind us!", s: [3.41, 2.81] },
  { id: "w7-h-hunt-wisp", lane: "h", zh: "看到那团橙色的小鬼火了吗？南瓜灯就藏在它下面！", en: "See that little orange wisp? A lantern is hiding right under it!", s: [5.18, 4.74] },
  { id: "w7-h-muertos-eve", lane: "h", zh: "剪纸旗和万寿菊都挂好啦。明天公园里通常会摆满祭坛，以官网为准。", en: "The papel picado and marigolds are up. Tomorrow the park usually fills with altars — check the official site.", s: [6.79, 7.25] },
  { id: "w7-h-procession-gather", lane: "h", zh: "大家戴着万寿菊花冠、捧着蜡烛在这里集合，通常七点出发，以官网为准。", en: "Marigold crowns and candles — everyone gathers here. It usually sets off at seven; check the official site.", s: [6.43, 6.95] },
  { id: "w7-h-procession-walk", lane: "h", zh: "游行的队伍过来了。我们在路边安静地看，好吗？", en: "Here comes the procession. Let’s watch quietly from the side, okay?", s: [4.04, 5.25] },
  { id: "w7-h-venue-pumpkins", lane: "h", zh: "今天这里有南瓜活动，摆了好多南瓜！时间以官网为准。", en: "A pumpkin party here today — pumpkins everywhere! Check the official site for times.", s: [5.31, 5.65] },
  { id: "realsf-calendar-alcatraz-sunrise-2026-10", lane: "s", zh: "今天是原住民日。恶魔岛上通常有一场日出聚会，大家安静地纪念。", en: "It’s Indigenous Peoples’ Day. There is usually a sunrise gathering on Alcatraz — a quiet remembrance.", s: [5.95, 7.17], own: 1 },
  { id: "realsf-calendar-chinatown-halloween-festival-2026", lane: "s", zh: "唐人街的万圣节庆典在 Waverly 巷，有手工、游戏和南瓜，去看看吧！", en: "Chinatown’s Halloween Festival is on Waverly Place — crafts, games and pumpkins. Let’s go see!", s: [6.41, 6.92], own: 1 },
  { id: "realsf-calendar-dst-end-2026", lane: "s", zh: "今天凌晨两点，钟拨回了一小时，天会黑得早一点哦。", en: "The clocks went back an hour at 2 this morning — it gets dark earlier now.", s: [4.51, 4.91], own: 1 },
  { id: "realsf-jets-blue", lane: "s", zh: "蓝天使飞行队通常下午三点左右上场，以官网为准哦。", en: "The Blue Angels usually fly around 3 pm — check the official schedule.", s: [4.99, 5.08], own: 1 },
];

/** clips whose pick missed a gate (the listening sheet says "check"): muted until the owner approves them */
export const W7_VOICE_CHECK: readonly string[] = ["zh-w5-a-5d9dcf9c", "zh-w5-a-6807a93e", "zh-w5-a-b95c4fe2", "en-w5-a-b95c4fe2", "en-w5-a-0b992197", "zh-w5-a-420d6131", "zh-w5-a-6c4f2c8f", "en-w5-a-9a2d1075"];

const DIR = '/opus-bay/w7/voice';
export const W7_VOICE_CLIPS: Record<string, VoiceClip> = Object.fromEntries(W7_VOICE_LINES.flatMap(l => (['zh', 'en'] as const).map((lang, k): [string, VoiceClip] => [
  `${lang}-${l.id}`, { m4a: `${DIR}/${lang}-${l.id}.m4a`, ogg: `${DIR}/${lang}-${l.id}.ogg`, lang, text: l[lang], duration: l.s[k] },
])));

/** retakes of wave-6 clips (their wave-6 clip ids; the new files are wave 7's) */
export const W7_RETAKE_CLIPS: Record<string, VoiceClip> = {
  "zh-w6g-street-fair-oaks": { m4a: `${DIR}/zh-w6g-street-fair-oaks.m4a`, ogg: `${DIR}/zh-w6g-street-fair-oaks.ogg`, lang: "zh", text: "Fair Oaks 街是诺伊谷的万圣节老地方，往年会封街！", duration: 4.43 },
  "zh-w6-h-hunt-all": { m4a: `${DIR}/zh-w6-h-hunt-all.m4a`, ogg: `${DIR}/zh-w6-h-hunt-all.ogg`, lang: "zh", text: "四十个全找齐啦！今年的南瓜王就是你！", duration: 3.6 },
  "en-w6-h-hunt-20": { m4a: `${DIR}/en-w6-h-hunt-20.m4a`, ogg: `${DIR}/en-w6-h-hunt-20.ogg`, lang: "en", text: "Twenty! That’s half of them found.", duration: 2.87 },
};

registerVoiceClips(W7_RETAKE_CLIPS);
registerVoiceClips(W7_VOICE_CLIPS, W7_VOICE_CHECK);
